// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYM_6z4BucWDiLaxTAcMj36zuF3W3oSSw',
    appId: '1:360727043538:web:5fdf9ea75042a3ce01bc0b',
    messagingSenderId: '360727043538',
    projectId: 'snapfit-c719d',
    authDomain: 'snapfit-c719d.firebaseapp.com',
    storageBucket: 'snapfit-c719d.firebasestorage.app',
    measurementId: 'G-6Y4PGYSH5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEu-4KDmrDgY8nZgsqZ6J60FnWvnosrCQ',
    appId: '1:360727043538:android:b8219efd5d02b20a01bc0b',
    messagingSenderId: '360727043538',
    projectId: 'snapfit-c719d',
    storageBucket: 'snapfit-c719d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChgPOriqVI4VkJj6GkFaI_iftaZPcpiIM',
    appId: '1:360727043538:ios:612effd366b2cdc301bc0b',
    messagingSenderId: '360727043538',
    projectId: 'snapfit-c719d',
    storageBucket: 'snapfit-c719d.firebasestorage.app',
    iosBundleId: 'com.devsheep.snapFit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChgPOriqVI4VkJj6GkFaI_iftaZPcpiIM',
    appId: '1:360727043538:ios:52da1665b10ae0f301bc0b',
    messagingSenderId: '360727043538',
    projectId: 'snapfit-c719d',
    storageBucket: 'snapfit-c719d.firebasestorage.app',
    iosBundleId: 'com.xxxx.xxxx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYM_6z4BucWDiLaxTAcMj36zuF3W3oSSw',
    appId: '1:360727043538:web:b3e8bc406a990b4001bc0b',
    messagingSenderId: '360727043538',
    projectId: 'snapfit-c719d',
    authDomain: 'snapfit-c719d.firebaseapp.com',
    storageBucket: 'snapfit-c719d.firebasestorage.app',
    measurementId: 'G-9R7P2K8D36',
  );
}
