import 'dart:convert';
import 'dart:io';

const _assetDir = 'assets/templates/wedding_editorial/images/sources';
const _handoffPath = 'assets/templates/wedding_editorial_handoff.json';
const _storePath = 'assets/templates/generated/wedding_editorial_store.json';

const _creamBg = '#FFFAF4E8';
const _whiteBg = '#FFFFFCF8';
const _brownBg = '#FFA06E47';
const _taupe = '#FF9A8576';
const _pale = '#FFE6D9CF';
const _charcoal = '#FF3B302A';
const _bodyTextScale = 1.14;
const _serifTextScale = 1.18;

String _asset(String fileName) => 'asset:$_assetDir/$fileName';

Map<String, dynamic> _image({
  required String id,
  required double x,
  required double y,
  required double width,
  required double height,
  required String imageUrl,
  String frame = 'free',
  int z = 10,
}) => {
  'id': id,
  'type': 'IMAGE',
  'zIndex': z,
  'x': x,
  'y': y,
  'width': width,
  'height': height,
  'scale': 1.0,
  'rotation': 0.0,
  'opacity': 1.0,
  'payload': {
    'imageBackground': frame,
    'imageTemplate': 'free',
    'imageUrl': imageUrl,
    'previewUrl': imageUrl,
    'originalUrl': imageUrl,
  },
};

Map<String, dynamic> _text({
  required String id,
  required double x,
  required double y,
  required double width,
  required double height,
  required String text,
  String align = 'left',
  String fontFamily = 'NotoSans',
  int fontWeight = 400,
  double fontSize = 16,
  String color = _taupe,
  double letterSpacing = 0,
  double lineHeight = 1.3,
  int z = 30,
}) => {
  'id': id,
  'type': 'TEXT',
  'zIndex': z,
  'x': x,
  'y': y,
  'width': width,
  'height': height,
  'scale': 1.0,
  'rotation': 0.0,
  'opacity': 1.0,
  'payload': {
    'text': text,
    'textAlign': align,
    'textStyleType': 'none',
    'textBackground': null,
    'textStyle': {
      'fontSize': fontSize * _bodyTextScale,
      'fontSizeRatio': (fontSize * _bodyTextScale) / 1080,
      'fontFamily': fontFamily,
      'fontWeight': fontWeight,
      'color': color,
      'letterSpacing': letterSpacing,
      'height': lineHeight,
      'lineHeight': lineHeight,
    },
  },
};

Map<String, dynamic> _serif({
  required String id,
  required double x,
  required double y,
  required double width,
  required double height,
  required String text,
  String align = 'left',
  double fontSize = 26,
  int fontWeight = 600,
  String color = _brownBg,
  double lineHeight = 1.0,
  double letterSpacing = 0,
  int z = 30,
}) => _text(
  id: id,
  x: x,
  y: y,
  width: width,
  height: height,
  text: text,
  align: align,
  fontFamily: 'Cormorant Garamond',
  fontWeight: fontWeight,
  fontSize: fontSize * _serifTextScale,
  color: color,
  lineHeight: lineHeight,
  letterSpacing: letterSpacing,
  z: z,
);

Map<String, dynamic> _box({
  required String id,
  required double x,
  required double y,
  required double width,
  required double height,
  String fill = _whiteBg,
  String? border,
  double? radius,
  double? borderWidth,
  int z = 2,
}) => {
  'id': id,
  'type': 'DECORATION',
  'zIndex': z,
  'x': x,
  'y': y,
  'width': width,
  'height': height,
  'scale': 1.0,
  'rotation': 0.0,
  'opacity': 1.0,
  'payload': {
    'imageBackground': 'free',
    'imageTemplate': 'free',
    'fill': fill,
    if (border != null) 'border': border,
    if (radius != null) 'cornerRadius': radius,
    if (borderWidth != null) 'borderWidth': borderWidth,
  },
};

Map<String, dynamic> _page({
  required int number,
  required String layoutId,
  required String role,
  required int photos,
  required List<Map<String, dynamic>> layers,
}) => {
  'pageNumber': number,
  'layoutId': layoutId,
  'role': role,
  'recommendedPhotoCount': photos,
  'layers': layers,
};

bool _isFullBleed(Map<String, dynamic> layer) {
  if (layer['type'] != 'IMAGE') return false;
  final x = (layer['x'] as num?)?.toDouble() ?? 0;
  final y = (layer['y'] as num?)?.toDouble() ?? 0;
  final w = (layer['width'] as num?)?.toDouble() ?? 0;
  final h = (layer['height'] as num?)?.toDouble() ?? 0;
  return x <= 0.02 && y <= 0.02 && w >= 0.98 && h >= 0.98;
}

void _adapt(List<Map<String, dynamic>> layers, String ratioType) {
  final verticalScale = ratioType == 'landscape' ? 0.72 : 0.86;
  final topInset = ratioType == 'landscape' ? 0.06 : 0.04;
  for (final layer in layers) {
    if (_isFullBleed(layer)) {
      layer['x'] = 0.0;
      layer['y'] = 0.0;
      layer['width'] = 1.0;
      layer['height'] = 1.0;
      continue;
    }
    final y = (layer['y'] as num).toDouble();
    final h = (layer['height'] as num).toDouble();
    layer['y'] = topInset + (y * verticalScale);
    layer['height'] = (h * verticalScale).clamp(0.02, 1.0);
    if (layer['type'] == 'TEXT' && ratioType == 'landscape') {
      final style =
          (layer['payload'] as Map<String, dynamic>)['textStyle']
              as Map<String, dynamic>;
      final fontSize = (style['fontSize'] as num).toDouble();
      style['fontSize'] = (fontSize * 0.92).clamp(10.0, 72.0);
    }
  }
}

List<Map<String, dynamic>> _portraitPages() {
  final ceremony = _asset('ceremony_moment.png');
  final sunset = _asset('sunset_pair.png');
  final city = _asset('city_weekend.png');
  final flower = _asset('flower_table.png');
  final hands = _asset('hands_bw.png');

  return [
    _page(
      number: 1,
      layoutId: 'cover_brown_title',
      role: 'cover',
      photos: 0,
      layers: [
        _box(id: 'bg', x: 0, y: 0, width: 1, height: 1, fill: _brownBg, z: 1),
        _serif(
          id: 'title_top',
          x: 0.403,
          y: 0.493,
          width: 0.194,
          height: 0.028,
          text: 'Together,',
          align: 'center',
          fontSize: 26,
          fontWeight: 500,
          color: _whiteBg,
        ),
        _serif(
          id: 'title_main',
          x: 0.305,
          y: 0.523,
          width: 0.39,
          height: 0.054,
          text: 'ALWAYS',
          align: 'center',
          fontSize: 62,
          fontWeight: 700,
          color: _whiteBg,
        ),
        _text(
          id: 'meta',
          x: 0.352,
          y: 0.575,
          width: 0.296,
          height: 0.018,
          text: 'MIN BIZ  ♡  PARK MIRI',
          align: 'center',
          fontSize: 13,
          color: _whiteBg,
          letterSpacing: 1.0,
        ),
      ],
    ),
    _page(
      number: 2,
      layoutId: 'date_collage',
      role: 'inner',
      photos: 3,
      layers: [
        _box(id: 'bg', x: 0, y: 0, width: 1, height: 1, fill: _creamBg, z: 1),
        _text(
          id: 'left_meta',
          x: 0.076,
          y: 0.078,
          width: 0.11,
          height: 0.014,
          text: 'BIZ  박민수의',
          fontSize: 12,
          color: _taupe,
          letterSpacing: 1.1,
        ),
        _text(
          id: 'right_meta',
          x: 0.807,
          y: 0.078,
          width: 0.12,
          height: 0.014,
          text: '김미리의 MIRI',
          align: 'right',
          fontSize: 12,
          color: _taupe,
          letterSpacing: 1.1,
        ),
        _box(
          id: 'date_chip',
          x: 0.438,
          y: 0.057,
          width: 0.124,
          height: 0.022,
          fill: _whiteBg,
          border: _taupe,
          borderWidth: 0.0018,
          radius: 0.02,
          z: 4,
        ),
        _text(
          id: 'date_chip_text',
          x: 0.463,
          y: 0.062,
          width: 0.075,
          height: 0.012,
          text: '10 / 26',
          align: 'center',
          fontSize: 12,
          color: _charcoal,
        ),
        _serif(
          id: 'title_top',
          x: 0.375,
          y: 0.124,
          width: 0.25,
          height: 0.025,
          text: 'Two lives',
          align: 'center',
          fontSize: 24,
          fontWeight: 500,
          color: _taupe,
        ),
        _serif(
          id: 'title_main',
          x: 0.28,
          y: 0.152,
          width: 0.44,
          height: 0.046,
          text: 'ONE LOVE',
          align: 'center',
          fontSize: 40,
          fontWeight: 700,
          color: _brownBg,
        ),
        _text(
          id: 'side_meta',
          x: 0.03,
          y: 0.338,
          width: 0.02,
          height: 0.18,
          text: 'FOREVER STARTS HERE',
          fontSize: 11,
          color: _taupe,
          letterSpacing: 1.2,
        ),
        _image(
          id: 'img_1',
          x: 0.185,
          y: 0.299,
          width: 0.2,
          height: 0.225,
          imageUrl: ceremony,
        ),
        _image(
          id: 'img_2',
          x: 0.4,
          y: 0.299,
          width: 0.2,
          height: 0.225,
          imageUrl: sunset,
        ),
        _image(
          id: 'img_3',
          x: 0.615,
          y: 0.299,
          width: 0.2,
          height: 0.225,
          imageUrl: city,
        ),
        _serif(
          id: 'n1',
          x: 0.185,
          y: 0.47,
          width: 0.14,
          height: 0.06,
          text: '90',
          fontSize: 74,
          fontWeight: 700,
          color: _whiteBg,
        ),
        _serif(
          id: 'n2',
          x: 0.402,
          y: 0.47,
          width: 0.14,
          height: 0.06,
          text: '10',
          fontSize: 74,
          fontWeight: 700,
          color: _whiteBg,
        ),
        _serif(
          id: 'n3',
          x: 0.617,
          y: 0.47,
          width: 0.14,
          height: 0.06,
          text: '26',
          fontSize: 74,
          fontWeight: 700,
          color: _whiteBg,
        ),
        _box(
          id: 'footer_line_left',
          x: 0.092,
          y: 0.845,
          width: 0.26,
          height: 0.0015,
          fill: _taupe,
          z: 3,
        ),
        _box(
          id: 'footer_line_right',
          x: 0.648,
          y: 0.845,
          width: 0.26,
          height: 0.0015,
          fill: _taupe,
          z: 3,
        ),
        _text(
          id: 'footer_left',
          x: 0.092,
          y: 0.858,
          width: 0.28,
          height: 0.014,
          text: 'Sunday, October 26, 2026 at 5:29 PM',
          fontSize: 12,
          color: _taupe,
        ),
        _text(
          id: 'footer_right',
          x: 0.648,
          y: 0.858,
          width: 0.25,
          height: 0.014,
          text: 'Maison de Blossom, Seoul',
          align: 'right',
          fontSize: 12,
          color: _taupe,
        ),
      ],
    ),
    _page(
      number: 3,
      layoutId: 'full_photo_meta',
      role: 'inner',
      photos: 1,
      layers: [
        _box(id: 'bg', x: 0, y: 0, width: 1, height: 1, fill: _whiteBg, z: 1),
        _text(
          id: 'meta_l',
          x: 0.074,
          y: 0.07,
          width: 0.24,
          height: 0.014,
          text: 'Sunday, October 26, 2026 at 5:29 PM',
          fontSize: 12,
          color: _taupe,
        ),
        _text(
          id: 'meta_r',
          x: 0.72,
          y: 0.07,
          width: 0.22,
          height: 0.014,
          text: 'Maison de Blossom, Seoul',
          align: 'right',
          fontSize: 12,
          color: _taupe,
        ),
        _box(
          id: 'line',
          x: 0.067,
          y: 0.084,
          width: 0.866,
          height: 0.0015,
          fill: _taupe,
          z: 3,
        ),
        _image(
          id: 'photo',
          x: 0.072,
          y: 0.101,
          width: 0.856,
          height: 0.49,
          imageUrl: ceremony,
        ),
      ],
    ),
    _page(
      number: 4,
      layoutId: 'full_photo_this_love',
      role: 'inner',
      photos: 1,
      layers: [
        _box(id: 'bg', x: 0, y: 0, width: 1, height: 1, fill: _whiteBg, z: 1),
        _text(
          id: 'left_meta',
          x: 0.068,
          y: 0.07,
          width: 0.11,
          height: 0.014,
          text: 'BIZ  박민수의',
          fontSize: 12,
          color: _taupe,
        ),
        _box(
          id: 'love_chip',
          x: 0.43,
          y: 0.062,
          width: 0.144,
          height: 0.022,
          fill: _whiteBg,
          border: _taupe,
          borderWidth: 0.0018,
          radius: 0.02,
          z: 4,
        ),
        _serif(
          id: 'love_text',
          x: 0.451,
          y: 0.066,
          width: 0.1,
          height: 0.016,
          text: 'This love',
          align: 'center',
          fontSize: 18,
          fontWeight: 500,
          color: _taupe,
        ),
        _text(
          id: 'right_meta',
          x: 0.82,
          y: 0.07,
          width: 0.11,
          height: 0.014,
          text: '김미리의 MIRI',
          align: 'right',
          fontSize: 12,
          color: _taupe,
        ),
        _image(
          id: 'photo',
          x: 0.082,
          y: 0.118,
          width: 0.837,
          height: 0.461,
          imageUrl: ceremony,
        ),
      ],
    ),
    _page(
      number: 5,
      layoutId: 'editorial_they_lived',
      role: 'inner',
      photos: 1,
      layers: [
        _box(id: 'bg', x: 0, y: 0, width: 1, height: 1, fill: _whiteBg, z: 1),
        _image(
          id: 'small_photo',
          x: 0.107,
          y: 0.133,
          width: 0.276,
          height: 0.199,
          imageUrl: sunset,
        ),
        _text(
          id: 'meta1',
          x: 0.704,
          y: 0.133,
          width: 0.22,
          height: 0.014,
          text: 'Sunday, October 26, 2026 at 5:29 PM',
          fontSize: 12,
          color: _taupe,
        ),
        _text(
          id: 'meta2',
          x: 0.739,
          y: 0.146,
          width: 0.18,
          height: 0.014,
          text: 'Maison de Blossom, Seoul',
          fontSize: 12,
          color: _taupe,
        ),
        _text(
          id: 'body',
          x: 0.087,
          y: 0.645,
          width: 0.21,
          height: 0.1,
          text:
              'The beginning of us,\nheld hands at sunset,\nfirst looked toward tomorrow,\nand promised each other\nthrough the soft light\nthat love would carry us.',
          fontSize: 12,
          color: _taupe,
          lineHeight: 1.5,
        ),
        _serif(
          id: 't1',
          x: 0.575,
          y: 0.556,
          width: 0.25,
          height: 0.04,
          text: 'THEY',
          fontSize: 50,
          fontWeight: 700,
          color: _brownBg,
        ),
        _serif(
          id: 't2',
          x: 0.498,
          y: 0.596,
          width: 0.31,
          height: 0.034,
          text: 'Happily ever after',
          fontSize: 38,
          fontWeight: 500,
          color: _taupe,
        ),
        _serif(
          id: 't3',
          x: 0.576,
          y: 0.639,
          width: 0.28,
          height: 0.044,
          text: 'LIVED',
          fontSize: 52,
          fontWeight: 700,
          color: _brownBg,
        ),
      ],
    ),
    _page(
      number: 6,
      layoutId: 'warm_full_bleed',
      role: 'inner',
      photos: 1,
      layers: [
        _image(
          id: 'hero',
          x: 0,
          y: 0,
          width: 1,
          height: 1,
          imageUrl: flower,
          z: 5,
        ),
        _text(
          id: 'meta_top',
          x: 0.067,
          y: 0.058,
          width: 0.26,
          height: 0.014,
          text: 'The beginning of us',
          fontSize: 12,
          color: _whiteBg,
          z: 20,
        ),
        _text(
          id: 'meta_bottom',
          x: 0.728,
          y: 0.916,
          width: 0.22,
          height: 0.014,
          text: 'forever starts here.',
          align: 'right',
          fontSize: 12,
          color: _whiteBg,
          z: 20,
        ),
      ],
    ),
    _page(
      number: 7,
      layoutId: 'center_card_caption',
      role: 'inner',
      photos: 1,
      layers: [
        _box(id: 'bg', x: 0, y: 0, width: 1, height: 1, fill: _creamBg, z: 1),
        _text(
          id: 'top_names',
          x: 0.281,
          y: 0.083,
          width: 0.437,
          height: 0.016,
          text: 'PARK BIZ   10 / 26   KIM MIRI',
          align: 'center',
          fontSize: 12,
          color: _taupe,
          letterSpacing: 1.1,
        ),
        _image(
          id: 'center_photo',
          x: 0.33,
          y: 0.182,
          width: 0.34,
          height: 0.338,
          imageUrl: flower,
        ),
        _text(
          id: 'caption',
          x: 0.259,
          y: 0.568,
          width: 0.482,
          height: 0.039,
          text:
              'Like a beautiful story, our beginning is written\nwith moments we hold softly and remember.\nAnd this love will last for all our days.',
          align: 'center',
          fontSize: 12,
          color: _taupe,
          lineHeight: 1.5,
        ),
      ],
    ),
    _page(
      number: 8,
      layoutId: 'grass_full_bleed',
      role: 'inner',
      photos: 1,
      layers: [
        _image(
          id: 'hero',
          x: 0,
          y: 0,
          width: 1,
          height: 1,
          imageUrl: sunset,
          z: 5,
        ),
      ],
    ),
    _page(
      number: 9,
      layoutId: 'brown_five_grid',
      role: 'inner',
      photos: 5,
      layers: [
        _box(id: 'bg', x: 0, y: 0, width: 1, height: 1, fill: _brownBg, z: 1),
        _image(
          id: 'g1',
          x: 0.157,
          y: 0.251,
          width: 0.278,
          height: 0.146,
          imageUrl: sunset,
        ),
        _image(
          id: 'g2',
          x: 0.481,
          y: 0.251,
          width: 0.306,
          height: 0.109,
          imageUrl: ceremony,
        ),
        _image(
          id: 'g3',
          x: 0.481,
          y: 0.375,
          width: 0.306,
          height: 0.109,
          imageUrl: city,
        ),
        _image(
          id: 'g4',
          x: 0.157,
          y: 0.419,
          width: 0.278,
          height: 0.146,
          imageUrl: ceremony,
        ),
        _image(
          id: 'g5',
          x: 0.481,
          y: 0.51,
          width: 0.306,
          height: 0.146,
          imageUrl: sunset,
        ),
        _text(
          id: 'cap',
          x: 0.237,
          y: 0.749,
          width: 0.528,
          height: 0.03,
          text:
              'I found the one my heart was waiting for.\nTogether, we begin forever.',
          align: 'center',
          fontSize: 12,
          color: _pale,
          lineHeight: 1.5,
        ),
      ],
    ),
    _page(
      number: 10,
      layoutId: 'brown_arch_portrait',
      role: 'inner',
      photos: 1,
      layers: [
        _box(id: 'bg', x: 0, y: 0, width: 1, height: 1, fill: _brownBg, z: 1),
        _serif(
          id: 'top',
          x: 0.38,
          y: 0.133,
          width: 0.24,
          height: 0.025,
          text: 'The beginning',
          align: 'center',
          fontSize: 20,
          fontWeight: 500,
          color: _pale,
        ),
        _serif(
          id: 'main',
          x: 0.25,
          y: 0.154,
          width: 0.5,
          height: 0.045,
          text: 'TOGETHER',
          align: 'center',
          fontSize: 42,
          fontWeight: 700,
          color: _whiteBg,
        ),
        _image(
          id: 'arch_photo',
          x: 0.307,
          y: 0.25,
          width: 0.385,
          height: 0.436,
          imageUrl: flower,
          frame: 'archOval',
        ),
      ],
    ),
    _page(
      number: 11,
      layoutId: 'three_strip_always',
      role: 'inner',
      photos: 3,
      layers: [
        _box(id: 'bg', x: 0, y: 0, width: 1, height: 1, fill: _creamBg, z: 1),
        _text(
          id: 'left_meta',
          x: 0.087,
          y: 0.074,
          width: 0.055,
          height: 0.014,
          text: 'BIZ',
          fontSize: 12,
          color: _taupe,
        ),
        _text(
          id: 'right_meta',
          x: 0.857,
          y: 0.074,
          width: 0.06,
          height: 0.014,
          text: 'MIRI',
          align: 'right',
          fontSize: 12,
          color: _taupe,
        ),
        _serif(
          id: 'title_top',
          x: 0.362,
          y: 0.104,
          width: 0.276,
          height: 0.022,
          text: 'Together,',
          align: 'center',
          fontSize: 24,
          fontWeight: 500,
          color: _taupe,
        ),
        _serif(
          id: 'title_main',
          x: 0.306,
          y: 0.126,
          width: 0.388,
          height: 0.038,
          text: 'ALWAYS',
          align: 'center',
          fontSize: 42,
          fontWeight: 700,
          color: _brownBg,
        ),
        _image(
          id: 's1',
          x: 0.094,
          y: 0.26,
          width: 0.259,
          height: 0.29,
          imageUrl: sunset,
        ),
        _image(
          id: 's2',
          x: 0.37,
          y: 0.26,
          width: 0.259,
          height: 0.29,
          imageUrl: city,
        ),
        _image(
          id: 's3',
          x: 0.646,
          y: 0.26,
          width: 0.259,
          height: 0.29,
          imageUrl: ceremony,
        ),
        _text(
          id: 'foot',
          x: 0.17,
          y: 0.61,
          width: 0.659,
          height: 0.03,
          text:
              'In this quiet, beautiful moment, we found something that will live\nfar beyond the day we stood side by side and chose forever. Our story begins here.',
          align: 'center',
          fontSize: 12,
          color: _taupe,
          lineHeight: 1.5,
        ),
      ],
    ),
    _page(
      number: 12,
      layoutId: 'editorial_collage_always',
      role: 'inner',
      photos: 5,
      layers: [
        _box(id: 'bg', x: 0, y: 0, width: 1, height: 1, fill: _whiteBg, z: 1),
        _image(
          id: 'top_center',
          x: 0.356,
          y: 0.082,
          width: 0.291,
          height: 0.156,
          imageUrl: city,
        ),
        _image(
          id: 'left_top',
          x: 0.122,
          y: 0.281,
          width: 0.2,
          height: 0.194,
          imageUrl: flower,
        ),
        _image(
          id: 'mid',
          x: 0.376,
          y: 0.389,
          width: 0.233,
          height: 0.135,
          imageUrl: city,
        ),
        _image(
          id: 'right_top',
          x: 0.676,
          y: 0.281,
          width: 0.2,
          height: 0.194,
          imageUrl: sunset,
        ),
        _image(
          id: 'bottom_mid',
          x: 0.376,
          y: 0.55,
          width: 0.233,
          height: 0.128,
          imageUrl: ceremony,
        ),
        _text(
          id: 'meta',
          x: 0.743,
          y: 0.082,
          width: 0.174,
          height: 0.036,
          text:
              'Sunday, October 26,\n2026 at 5:29 PM\nMaison de Blossom, Seoul',
          fontSize: 11,
          color: _taupe,
          lineHeight: 1.45,
        ),
        _text(
          id: 'small_body',
          x: 0.122,
          y: 0.699,
          width: 0.17,
          height: 0.05,
          text: 'This is not the end,\njust the beginning of our\nforever.',
          fontSize: 12,
          color: _taupe,
          lineHeight: 1.45,
        ),
        _serif(
          id: 'title_top',
          x: 0.702,
          y: 0.694,
          width: 0.166,
          height: 0.025,
          text: 'Just us',
          fontSize: 28,
          fontWeight: 500,
          color: _taupe,
        ),
        _serif(
          id: 'title_main',
          x: 0.635,
          y: 0.719,
          width: 0.248,
          height: 0.038,
          text: 'ALWAYS',
          fontSize: 42,
          fontWeight: 700,
          color: _brownBg,
        ),
      ],
    ),
    _page(
      number: 13,
      layoutId: 'simple_center_photo',
      role: 'inner',
      photos: 1,
      layers: [
        _box(id: 'bg', x: 0, y: 0, width: 1, height: 1, fill: _whiteBg, z: 1),
        _text(
          id: 'tl',
          x: 0.065,
          y: 0.078,
          width: 0.205,
          height: 0.014,
          text: 'FOREVER STARTS HERE',
          fontSize: 12,
          color: _taupe,
          letterSpacing: 0.8,
        ),
        _text(
          id: 'tr',
          x: 0.741,
          y: 0.078,
          width: 0.205,
          height: 0.014,
          text: 'THE BEGINNING OF US',
          align: 'right',
          fontSize: 12,
          color: _taupe,
          letterSpacing: 0.8,
        ),
        _image(
          id: 'center_photo',
          x: 0.387,
          y: 0.222,
          width: 0.226,
          height: 0.226,
          imageUrl: hands,
        ),
        _text(
          id: 'bl',
          x: 0.065,
          y: 0.859,
          width: 0.25,
          height: 0.014,
          text: 'IN THIS MOMENT, WE FOUND FOREVER',
          fontSize: 12,
          color: _taupe,
        ),
        _text(
          id: 'br',
          x: 0.666,
          y: 0.859,
          width: 0.268,
          height: 0.014,
          text: 'TWO HEARTS, ONE FOREVER.',
          align: 'right',
          fontSize: 12,
          color: _taupe,
        ),
      ],
    ),
    _page(
      number: 14,
      layoutId: 'love_simply',
      role: 'inner',
      photos: 3,
      layers: [
        _box(id: 'bg', x: 0, y: 0, width: 1, height: 1, fill: _whiteBg, z: 1),
        _serif(
          id: 'title',
          x: 0.085,
          y: 0.08,
          width: 0.24,
          height: 0.022,
          text: 'Love, simply',
          fontSize: 28,
          fontWeight: 500,
          color: _brownBg,
        ),
        _text(
          id: 'body_top',
          x: 0.365,
          y: 0.082,
          width: 0.488,
          height: 0.026,
          text:
              'Through the warm walk together we kept every corner\nof this day quiet, simple, and full of the kind of love that stays.',
          fontSize: 11,
          color: _taupe,
          lineHeight: 1.4,
        ),
        _image(
          id: 'left_large',
          x: 0.085,
          y: 0.164,
          width: 0.505,
          height: 0.299,
          imageUrl: ceremony,
        ),
        _image(
          id: 'right_top',
          x: 0.625,
          y: 0.164,
          width: 0.163,
          height: 0.122,
          imageUrl: hands,
        ),
        _image(
          id: 'right_bottom',
          x: 0.625,
          y: 0.307,
          width: 0.163,
          height: 0.161,
          imageUrl: sunset,
        ),
        _text(
          id: 'bottom_l',
          x: 0.085,
          y: 0.503,
          width: 0.13,
          height: 0.014,
          text: 'just us, always.',
          fontSize: 12,
          color: _taupe,
        ),
        _text(
          id: 'bottom_r',
          x: 0.615,
          y: 0.503,
          width: 0.21,
          height: 0.014,
          text: 'Together in everything.',
          fontSize: 12,
          color: _taupe,
        ),
      ],
    ),
    _page(
      number: 15,
      layoutId: 'simple_corner_caption',
      role: 'inner',
      photos: 1,
      layers: [
        _box(id: 'bg', x: 0, y: 0, width: 1, height: 1, fill: _whiteBg, z: 1),
        _text(
          id: 'tl',
          x: 0.069,
          y: 0.078,
          width: 0.22,
          height: 0.014,
          text: 'FOREVER STARTS HERE',
          fontSize: 12,
          color: _taupe,
        ),
        _text(
          id: 'tr',
          x: 0.713,
          y: 0.078,
          width: 0.22,
          height: 0.014,
          text: 'THE BEGINNING OF US',
          align: 'right',
          fontSize: 12,
          color: _taupe,
        ),
        _image(
          id: 'center_photo',
          x: 0.387,
          y: 0.354,
          width: 0.226,
          height: 0.226,
          imageUrl: hands,
        ),
        _text(
          id: 'bl',
          x: 0.067,
          y: 0.86,
          width: 0.3,
          height: 0.014,
          text: 'IN THIS MOMENT, WE FOUND FOREVER',
          fontSize: 12,
          color: _taupe,
        ),
        _text(
          id: 'br',
          x: 0.654,
          y: 0.86,
          width: 0.27,
          height: 0.014,
          text: 'TWO HEARTS, ONE FOREVER.',
          align: 'right',
          fontSize: 12,
          color: _taupe,
        ),
      ],
    ),
    _page(
      number: 16,
      layoutId: 'brown_cake_full',
      role: 'inner',
      photos: 1,
      layers: [
        _box(id: 'bg', x: 0, y: 0, width: 1, height: 1, fill: _brownBg, z: 1),
        _text(
          id: 'tl',
          x: 0.085,
          y: 0.072,
          width: 0.18,
          height: 0.012,
          text: 'The beginning of us',
          fontSize: 11,
          color: _pale,
        ),
        _box(
          id: 'line',
          x: 0.229,
          y: 0.084,
          width: 0.542,
          height: 0.0015,
          fill: _pale,
          z: 3,
        ),
        _text(
          id: 'tr',
          x: 0.775,
          y: 0.072,
          width: 0.145,
          height: 0.012,
          text: 'forever starts here.',
          align: 'right',
          fontSize: 11,
          color: _pale,
        ),
        _image(
          id: 'hero',
          x: 0.17,
          y: 0.129,
          width: 0.659,
          height: 0.658,
          imageUrl: flower,
        ),
      ],
    ),
    _page(
      number: 17,
      layoutId: 'brown_cake_grid',
      role: 'inner',
      photos: 4,
      layers: [
        _box(id: 'bg', x: 0, y: 0, width: 1, height: 1, fill: _brownBg, z: 1),
        _image(
          id: 'g1',
          x: 0.231,
          y: 0.269,
          width: 0.23,
          height: 0.149,
          imageUrl: flower,
        ),
        _image(
          id: 'g2',
          x: 0.489,
          y: 0.269,
          width: 0.23,
          height: 0.149,
          imageUrl: flower,
        ),
        _image(
          id: 'g3',
          x: 0.231,
          y: 0.431,
          width: 0.23,
          height: 0.149,
          imageUrl: flower,
        ),
        _image(
          id: 'g4',
          x: 0.489,
          y: 0.431,
          width: 0.23,
          height: 0.149,
          imageUrl: flower,
        ),
        _text(
          id: 'caption',
          x: 0.187,
          y: 0.662,
          width: 0.626,
          height: 0.028,
          text:
              'As the candles glowed and we leaned closer, ordinary time\nfell away. Through laughter and sugar-soft light, nothing else felt as real as us.',
          align: 'center',
          fontSize: 11,
          color: _pale,
          lineHeight: 1.45,
        ),
      ],
    ),
    _page(
      number: 18,
      layoutId: 'double_vertical_night',
      role: 'inner',
      photos: 2,
      layers: [
        _box(id: 'bg', x: 0, y: 0, width: 1, height: 1, fill: _whiteBg, z: 1),
        _image(
          id: 'left',
          x: 0.093,
          y: 0.082,
          width: 0.378,
          height: 0.816,
          imageUrl: city,
        ),
        _image(
          id: 'right',
          x: 0.53,
          y: 0.082,
          width: 0.378,
          height: 0.816,
          imageUrl: city,
        ),
      ],
    ),
    _page(
      number: 19,
      layoutId: 'bw_proposal',
      role: 'inner',
      photos: 1,
      layers: [
        _box(id: 'bg', x: 0, y: 0, width: 1, height: 1, fill: _whiteBg, z: 1),
        _image(
          id: 'hero',
          x: 0.067,
          y: 0.072,
          width: 0.867,
          height: 0.858,
          imageUrl: hands,
        ),
      ],
    ),
    _page(
      number: 20,
      layoutId: 'soft_veil',
      role: 'inner',
      photos: 1,
      layers: [
        _image(
          id: 'hero',
          x: 0,
          y: 0,
          width: 1,
          height: 1,
          imageUrl: ceremony,
          z: 5,
        ),
        _box(
          id: 'wash',
          x: 0,
          y: 0,
          width: 1,
          height: 1,
          fill: '#22FAF4E8',
          z: 6,
        ),
        _text(
          id: 'body',
          x: 0.194,
          y: 0.824,
          width: 0.611,
          height: 0.024,
          text:
              'YOU WERE NEVER A MOMENT.\nYou became the memory I always return to.',
          align: 'center',
          fontSize: 11,
          color: _whiteBg,
          z: 20,
          lineHeight: 1.4,
        ),
        _serif(
          id: 'sign',
          x: 0.42,
          y: 0.895,
          width: 0.16,
          height: 0.022,
          text: 'Ark Kim',
          align: 'center',
          fontSize: 30,
          fontWeight: 600,
          color: _whiteBg,
          z: 20,
        ),
      ],
    ),
    _page(
      number: 21,
      layoutId: 'simple_back_view',
      role: 'inner',
      photos: 1,
      layers: [
        _box(id: 'bg', x: 0, y: 0, width: 1, height: 1, fill: _creamBg, z: 1),
        _text(
          id: 'top_names',
          x: 0.341,
          y: 0.082,
          width: 0.319,
          height: 0.014,
          text: 'PARK BIZ   10 / 26   KIM MIRI',
          align: 'center',
          fontSize: 12,
          color: _taupe,
          letterSpacing: 1.0,
        ),
        _image(
          id: 'center_photo',
          x: 0.357,
          y: 0.222,
          width: 0.286,
          height: 0.259,
          imageUrl: sunset,
        ),
        _text(
          id: 'body',
          x: 0.311,
          y: 0.594,
          width: 0.378,
          height: 0.03,
          text:
              'And so our story continues,\nhand in hand through every season,\nforever and always.',
          align: 'center',
          fontSize: 12,
          color: _taupe,
          lineHeight: 1.45,
        ),
      ],
    ),
    _page(
      number: 22,
      layoutId: 'classic_stairs',
      role: 'end',
      photos: 1,
      layers: [
        _box(id: 'bg', x: 0, y: 0, width: 1, height: 1, fill: _whiteBg, z: 1),
        _image(
          id: 'hero',
          x: 0.057,
          y: 0.051,
          width: 0.885,
          height: 0.847,
          imageUrl: ceremony,
        ),
        _text(
          id: 'meta_l',
          x: 0.067,
          y: 0.865,
          width: 0.21,
          height: 0.014,
          text: 'Sunday, October 26',
          fontSize: 12,
          color: _taupe,
        ),
        _text(
          id: 'meta_r',
          x: 0.708,
          y: 0.865,
          width: 0.225,
          height: 0.014,
          text: 'Maison de Blossom, Seoul',
          align: 'right',
          fontSize: 12,
          color: _taupe,
        ),
      ],
    ),
  ];
}

List<Map<String, dynamic>> _adaptPages(
  List<Map<String, dynamic>> pages,
  String ratioType,
) {
  final cloned = jsonDecode(jsonEncode(pages)) as List<dynamic>;
  final next = cloned.cast<Map<String, dynamic>>();
  for (final page in next) {
    final layers = (page['layers'] as List).cast<Map<String, dynamic>>();
    _adapt(layers, ratioType);
  }
  return next;
}

Map<String, dynamic> _templateJson() {
  final portrait = _portraitPages();
  final square = _adaptPages(portrait, 'square');
  final landscape = _adaptPages(portrait, 'landscape');
  return {
    'schemaVersion': 1,
    'strictLayout': true,
    'autoFit': false,
    'autoFitPadding': 0.0,
    'aspect': 'portrait',
    'designWidth': 1080,
    'designHeight': 1440,
    'templateId': 'wedding_editorial_v1',
    'version': 1,
    'lifecycleStatus': 'published',
    'ratio': '9:16',
    'cover': {'pageNumber': 1, 'layers': portrait.first['layers']},
    'metadata': {
      'style': 'wedding_editorial_clean',
      'designWidth': 1080,
      'designHeight': 1440,
      'difficulty': 2,
      'recommendedPhotoCount': 8,
      'mood': 'cream_brown_editorial',
      'tags': ['웨딩', '에디토리얼', '청첩장', '커플', '브라운'],
      'templateType': 'wedding',
      'theme': 'editorial',
      'title': 'Wedding Editorial',
      'category': '웨딩',
      'heroTextSafeArea': {'x': 0.30, 'y': 0.48, 'width': 0.40, 'height': 0.13},
      'sourceBottomSheetTemplateIds': ['wedding_editorial_v1'],
      'applyScope': 'cover_and_pages',
      'bottomSheetReferenceMode': 'style_and_tone_only',
    },
    'pages': portrait,
    'variants': {
      'square': {
        'variantId': 'wedding_editorial_square',
        'aspect': 'square',
        'ratio': '1:1',
        'designWidth': 1440,
        'designHeight': 1440,
        'metadata': {'templateType': 'wedding', 'theme': 'editorial'},
        'pages': square,
      },
      'landscape': {
        'variantId': 'wedding_editorial_landscape',
        'aspect': 'landscape',
        'ratio': '16:9',
        'designWidth': 1440,
        'designHeight': 1080,
        'metadata': {'templateType': 'wedding', 'theme': 'editorial'},
        'pages': landscape,
      },
    },
  };
}

Map<String, dynamic> _storeEntry() {
  final cover = _asset('ceremony_moment.png');
  final previewImages = <String>[
    _asset('ceremony_moment.png'),
    _asset('ceremony_moment.png'),
    _asset('ceremony_moment.png'),
    _asset('ceremony_moment.png'),
    _asset('sunset_pair.png'),
    _asset('flower_table.png'),
    _asset('flower_table.png'),
    _asset('sunset_pair.png'),
    _asset('city_weekend.png'),
    _asset('flower_table.png'),
    _asset('sunset_pair.png'),
    _asset('city_weekend.png'),
    _asset('hands_bw.png'),
    _asset('ceremony_moment.png'),
    _asset('hands_bw.png'),
    _asset('flower_table.png'),
    _asset('flower_table.png'),
    _asset('city_weekend.png'),
    _asset('hands_bw.png'),
    _asset('ceremony_moment.png'),
    _asset('sunset_pair.png'),
    _asset('ceremony_moment.png'),
  ];
  return {
    'id': 50,
    'title': 'Wedding Editorial',
    'subTitle': '웨딩 · clean editorial',
    'description': '크림과 브라운 톤의 정돈된 웨딩 에디토리얼 포토북 템플릿',
    'coverImageUrl': cover,
    'previewImages': previewImages,
    'pageCount': 22,
    'likeCount': 0,
    'userCount': 0,
    'category': '웨딩',
    'tags': ['웨딩', '에디토리얼', '브라운', '청첩장', '커플'],
    'weeklyScore': 0,
    'isNew': true,
    'isBest': false,
    'isPremium': false,
    'isLiked': false,
    'templateId': 'wedding_editorial_v1',
    'version': 'v1',
    'lifecycleStatus': 'published',
    'templateJson': jsonEncode(_templateJson()),
  };
}

void main() {
  final entry = _storeEntry();
  File(_handoffPath)
    ..createSync(recursive: true)
    ..writeAsStringSync(const JsonEncoder.withIndent('  ').convert([entry]));
  File(_storePath)
    ..createSync(recursive: true)
    ..writeAsStringSync(const JsonEncoder.withIndent('  ').convert([entry]));

  stdout.writeln('Generated wedding_editorial template');
  stdout.writeln('handoff=$_handoffPath');
  stdout.writeln('store=$_storePath');
  stdout.writeln(
    'next=./scripts/template_asset_pipeline.sh --template-slug=wedding_editorial '
    '--template-store-json=$_storePath',
  );
}
