import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;

const _assetDir = 'assets/templates/scrapbook/images/sources';
const _handoffPath = 'assets/templates/scrapbook_handoff.json';
const _storePath = 'assets/templates/generated/scrapbook_store.json';

const _paper = '#FFF8F2EA';
const _paperLight = '#FFFFFCF7';
const _oat = '#FFF2E8D8';
const _patch = '#FFD0CABD';
const _cocoa = '#FF6A5547';
const _sage = '#FFC0CCB9';
const _blush = '#FFEAD1CA';
const _rose = '#FFFFB8C8';
const _warmGray = '#FFCEC4B7';
const _charcoal = '#FF3E342F';
const _navy = '#FF263B57';
const _tapeColor = '#EAF4E7BC';
const _ink = '#FF4A413A';

String _asset(String fileName) => 'asset:$_assetDir/$fileName';

Map<String, dynamic> _image({
  required String id,
  required double x,
  required double y,
  required double width,
  required double height,
  required String imageUrl,
  String frame = '',
  int z = 10,
  double rotation = 0,
}) => {
  'id': id,
  'type': 'IMAGE',
  'zIndex': z,
  'x': x,
  'y': y,
  'width': width,
  'height': height,
  'scale': 1.0,
  'rotation': rotation,
  'opacity': 1.0,
  'payload': {
    'imageBackground': frame,
    'imageTemplate': 'free',
    'imageUrl': imageUrl,
    'previewUrl': imageUrl,
    'originalUrl': imageUrl,
  },
};

Map<String, dynamic> _text({
  required String id,
  required double x,
  required double y,
  required double width,
  required double height,
  required String text,
  String align = 'left',
  String fontFamily = 'Inter',
  int fontWeight = 500,
  double fontSize = 16,
  String color = _ink,
  double lineHeight = 1.3,
  double letterSpacing = 0,
  int z = 30,
  double rotation = 0,
}) => {
  'id': id,
  'type': 'TEXT',
  'zIndex': z,
  'x': x,
  'y': y,
  'width': width,
  'height': height,
  'scale': 1.0,
  'rotation': rotation,
  'opacity': 1.0,
  'payload': {
    'text': text,
    'textAlign': align,
    'textStyleType': 'none',
    'textBackground': null,
    'textStyle': {
      'fontSize': fontSize,
      'fontSizeRatio': fontSize / 1080,
      'fontFamily': fontFamily,
      'fontWeight': fontWeight,
      'color': color,
      'letterSpacing': letterSpacing,
      'height': lineHeight,
      'lineHeight': lineHeight,
    },
  },
};

Map<String, dynamic> _serif({
  required String id,
  required double x,
  required double y,
  required double width,
  required double height,
  required String text,
  String align = 'left',
  double fontSize = 32,
  int fontWeight = 700,
  String color = _cocoa,
  double lineHeight = 1.0,
  int z = 30,
}) => _text(
  id: id,
  x: x,
  y: y,
  width: width,
  height: height,
  text: text,
  align: align,
  fontFamily: 'Cormorant Garamond',
  fontWeight: fontWeight,
  fontSize: fontSize,
  color: color,
  lineHeight: lineHeight,
  z: z,
);

Map<String, dynamic> _hand({
  required String id,
  required double x,
  required double y,
  required double width,
  required double height,
  required String text,
  String color = _charcoal,
  double fontSize = 18,
  double rotation = 0,
  int z = 35,
}) => _text(
  id: id,
  x: x,
  y: y,
  width: width,
  height: height,
  text: text,
  fontFamily: 'Figma Hand',
  fontWeight: 400,
  fontSize: fontSize,
  color: color,
  lineHeight: 1.15,
  rotation: rotation,
  z: z,
);

Map<String, dynamic> _box({
  required String id,
  required double x,
  required double y,
  required double width,
  required double height,
  String fill = _paperLight,
  String? border,
  double? radius,
  double? borderWidth,
  int z = 2,
  double rotation = 0,
  double opacity = 1.0,
}) => {
  'id': id,
  'type': 'DECORATION',
  'zIndex': z,
  'x': x,
  'y': y,
  'width': width,
  'height': height,
  'scale': 1.0,
  'rotation': rotation,
  'opacity': opacity,
  'payload': {
    'imageBackground': '',
    'imageTemplate': 'free',
    'fillColor': fill,
    if (border != null) 'borderColor': border,
    if (radius != null) 'cornerRadius': radius,
    if (borderWidth != null) 'borderWidth': borderWidth,
  },
};

List<Map<String, dynamic>> _grid({
  required String id,
  required double x,
  required double y,
  required double width,
  required double height,
  int columns = 8,
  int rows = 7,
  String color = '#33C8C0B5',
  int z = 3,
}) {
  final out = <Map<String, dynamic>>[];
  for (var i = 0; i <= columns; i++) {
    out.add(
      _box(
        id: '${id}_v$i',
        x: x + (width / columns) * i,
        y: y,
        width: 0.0012,
        height: height,
        fill: color,
        z: z,
      ),
    );
  }
  for (var i = 0; i <= rows; i++) {
    out.add(
      _box(
        id: '${id}_h$i',
        x: x,
        y: y + (height / rows) * i,
        width: width,
        height: 0.001,
        fill: color,
        z: z,
      ),
    );
  }
  return out;
}

List<Map<String, dynamic>> _dotGrid({
  required String id,
  required double x,
  required double y,
  int columns = 6,
  int rows = 6,
  double gapX = 0.026,
  double gapY = 0.019,
  String color = '#8899A1AA',
  int z = 18,
}) {
  final out = <Map<String, dynamic>>[];
  for (var row = 0; row < rows; row++) {
    for (var col = 0; col < columns; col++) {
      out.add(
        _box(
          id: '${id}_${row}_$col',
          x: x + col * gapX,
          y: y + row * gapY,
          width: 0.006,
          height: 0.0045,
          fill: color,
          radius: 999,
          z: z,
        ),
      );
    }
  }
  return out;
}

List<Map<String, dynamic>> _stars(
  String id,
  List<(double, double, double)> specs, {
  String color = '#FFD3A447',
  int z = 22,
}) {
  return [
    for (var i = 0; i < specs.length; i++)
      _text(
        id: '${id}_$i',
        x: specs[i].$1,
        y: specs[i].$2,
        width: specs[i].$3,
        height: specs[i].$3,
        text: '★',
        align: 'center',
        fontFamily: 'Inter',
        fontSize: specs[i].$3 * 1080,
        fontWeight: 700,
        color: color,
        lineHeight: 1.0,
        z: z,
      ),
  ];
}

List<Map<String, dynamic>> _tape(
  String id,
  List<(double, double, double, double, double)> specs, {
  String fill = _tapeColor,
  int z = 24,
}) {
  return [
    for (var i = 0; i < specs.length; i++)
      _box(
        id: '${id}_$i',
        x: specs[i].$1,
        y: specs[i].$2,
        width: specs[i].$3,
        height: specs[i].$4,
        fill: fill,
        radius: 0.004,
        rotation: specs[i].$5,
        z: z,
        opacity: 0.92,
      ),
  ];
}

List<Map<String, dynamic>> _polaroid({
  required String id,
  required double x,
  required double y,
  required double width,
  required double height,
  required String imageUrl,
  double rotation = 0,
  int z = 8,
  bool label = false,
}) {
  final padX = math.min(0.026, width * 0.11);
  final padY = math.min(0.02, height * 0.09);
  final bottom = math.min(0.055, height * 0.20);
  return [
    _box(
      id: '${id}_card',
      x: x,
      y: y,
      width: width,
      height: height,
      fill: '#FFFFFFFF',
      radius: 0.004,
      rotation: rotation,
      z: z,
    ),
    _image(
      id: id,
      x: x + padX,
      y: y + padY,
      width: math.max(0.02, width - padX * 2),
      height: math.max(0.02, height - padY - bottom),
      imageUrl: imageUrl,
      rotation: rotation,
      z: z + 4,
    ),
    if (label)
      _hand(
        id: '${id}_label',
        x: x + padX,
        y: y + height - bottom + 0.012,
        width: width - padX * 2,
        height: 0.022,
        text: 'small memory',
        fontSize: 11,
        rotation: rotation,
        color: '#FF7B7168',
        z: z + 6,
      ),
  ];
}

Map<String, dynamic> _page({
  required int number,
  required String layoutId,
  required String role,
  required int photos,
  required List<Map<String, dynamic>> layers,
}) => {
  'pageNumber': number,
  'layoutId': layoutId,
  'role': role == 'cover'
      ? 'cover'
      : role == 'ending'
      ? 'end'
      : role == 'text'
      ? 'chapter'
      : 'inner',
  'recommendedPhotoCount': photos,
  'layers': _normalizeLayerOrder(layers),
};

List<Map<String, dynamic>> _normalizeLayerOrder(
  List<Map<String, dynamic>> layers,
) {
  for (var i = 0; i < layers.length; i++) {
    layers[i]['zIndex'] = i + 1;
  }
  return layers;
}

List<Map<String, dynamic>> _portraitPages() {
  final ceremony = _asset('ceremony_moment.png');
  final sunset = _asset('sunset_pair.png');
  final city = _asset('city_weekend.png');
  final flower = _asset('flower_table.png');
  final hands = _asset('hands_bw.png');

  return [
    _page(
      number: 1,
      layoutId: 'cover_memory_board',
      role: 'cover',
      photos: 5,
      layers: [
        _box(id: 'bg', x: 0, y: 0, width: 1, height: 1, fill: _paper, z: 1),
        _box(
          id: 'main_patch',
          x: 0.092,
          y: 0.083,
          width: 0.514,
          height: 0.693,
          fill: _patch,
          radius: 0.02,
          rotation: 1.6,
          z: 2,
        ),
        _box(
          id: 'right_patch',
          x: 0.60,
          y: 0.125,
          width: 0.32,
          height: 0.30,
          fill: '#F5FFFFFF',
          radius: 0.014,
          rotation: -3.0,
          z: 2,
        ),
        ..._grid(
          id: 'cover_grid',
          x: 0.61,
          y: 0.10,
          width: 0.26,
          height: 0.20,
          columns: 7,
          rows: 6,
          z: 3,
        ),
        ..._polaroid(
          id: 'photo_main',
          x: 0.117,
          y: 0.104,
          width: 0.381,
          height: 0.334,
          imageUrl: ceremony,
          rotation: 6,
          label: true,
        ),
        ..._polaroid(
          id: 'photo_top',
          x: 0.485,
          y: 0.128,
          width: 0.250,
          height: 0.225,
          imageUrl: sunset,
          rotation: -5,
        ),
        ..._polaroid(
          id: 'photo_right',
          x: 0.654,
          y: 0.176,
          width: 0.220,
          height: 0.191,
          imageUrl: flower,
          rotation: 4,
        ),
        ..._polaroid(
          id: 'photo_bottom',
          x: 0.157,
          y: 0.571,
          width: 0.235,
          height: 0.200,
          imageUrl: ceremony,
          rotation: -7,
        ),
        ..._polaroid(
          id: 'photo_mid',
          x: 0.481,
          y: 0.389,
          width: 0.289,
          height: 0.170,
          imageUrl: sunset,
          rotation: 2,
        ),
        _box(
          id: 'note_back',
          x: 0.64,
          y: 0.49,
          width: 0.25,
          height: 0.15,
          fill: _blush,
          radius: 0.02,
          rotation: 4,
          z: 12,
        ),
        _box(
          id: 'note_front',
          x: 0.69,
          y: 0.52,
          width: 0.24,
          height: 0.13,
          fill: _sage,
          radius: 0.02,
          rotation: -3,
          z: 13,
        ),
        _hand(
          id: 'favorite',
          x: 0.73,
          y: 0.525,
          width: 0.16,
          height: 0.05,
          text: 'favorite\nphotos',
          fontSize: 27,
          z: 35,
        ),
        ..._tape('cover_tape', [
          (0.228, 0.104, 0.106, 0.032, -8),
          (0.557, 0.108, 0.082, 0.026, 6),
          (0.72, 0.172, 0.072, 0.020, 4),
          (0.20, 0.548, 0.088, 0.027, 7),
          (0.577, 0.385, 0.086, 0.024, -5),
        ]),
        _serif(
          id: 'title',
          x: 0.115,
          y: 0.700,
          width: 0.52,
          height: 0.068,
          text: 'SCRAPBOOK',
          fontSize: 60,
          color: _charcoal,
        ),
        _hand(
          id: 'sub',
          x: 0.125,
          y: 0.776,
          width: 0.46,
          height: 0.032,
          text: 'Pinterest mood = 우리의 하루',
          fontSize: 20,
          color: '#FFFFFFFF',
        ),
        _box(
          id: 'memo_patch',
          x: 0.085,
          y: 0.815,
          width: 0.14,
          height: 0.066,
          fill: _blush,
          radius: 0.008,
          z: 18,
        ),
        _hand(
          id: 'memo_text',
          x: 0.11,
          y: 0.826,
          width: 0.09,
          height: 0.045,
          text: 'not\njust a\nphoto',
          fontSize: 18,
          z: 36,
        ),
        _box(
          id: 'badge',
          x: 0.65,
          y: 0.792,
          width: 0.198,
          height: 0.029,
          fill: _blush,
          radius: 999,
          z: 18,
        ),
        _text(
          id: 'badge_text',
          x: 0.667,
          y: 0.799,
          width: 0.16,
          height: 0.014,
          text: 'weekend archive',
          align: 'center',
          fontSize: 12,
          fontWeight: 700,
          color: _cocoa,
        ),
        ..._stars('cover_star', [(0.865, 0.655, 0.014)]),
      ],
    ),
    _page(
      number: 2,
      layoutId: 'polaroid_collage',
      role: 'inner',
      photos: 5,
      layers: [
        _box(id: 'bg', x: 0, y: 0, width: 1, height: 1, fill: _paper, z: 1),
        ..._grid(
          id: 'p1_grid',
          x: 0.09,
          y: 0.083,
          width: 0.28,
          height: 0.153,
          columns: 8,
          rows: 6,
          z: 2,
        ),
        ..._polaroid(
          id: 'p1_a',
          x: 0.102,
          y: 0.090,
          width: 0.288,
          height: 0.249,
          imageUrl: sunset,
          rotation: 7,
          label: true,
        ),
        ..._polaroid(
          id: 'p1_b',
          x: 0.383,
          y: 0.126,
          width: 0.253,
          height: 0.220,
          imageUrl: city,
          rotation: -4,
        ),
        ..._polaroid(
          id: 'p1_c',
          x: 0.628,
          y: 0.107,
          width: 0.223,
          height: 0.188,
          imageUrl: flower,
          rotation: 5,
        ),
        ..._polaroid(
          id: 'p1_d',
          x: 0.106,
          y: 0.344,
          width: 0.372,
          height: 0.309,
          imageUrl: sunset,
          rotation: -4,
        ),
        ..._polaroid(
          id: 'p1_e',
          x: 0.483,
          y: 0.421,
          width: 0.319,
          height: 0.266,
          imageUrl: city,
          rotation: 6,
        ),
        _box(
          id: 'note_large',
          x: 0.782,
          y: 0.312,
          width: 0.22,
          height: 0.117,
          fill: _blush,
          radius: 0.018,
          rotation: -3,
          z: 18,
        ),
        _hand(
          id: 'note_large_text',
          x: 0.812,
          y: 0.335,
          width: 0.16,
          height: 0.062,
          text: 'full\npage',
          fontSize: 21,
          z: 35,
        ),
        _box(
          id: 'note_small',
          x: 0.428,
          y: 0.686,
          width: 0.13,
          height: 0.092,
          fill: _blush,
          radius: 0.008,
          rotation: -4,
          z: 18,
        ),
        _hand(
          id: 'note_small_text',
          x: 0.462,
          y: 0.713,
          width: 0.07,
          height: 0.035,
          text: 'cut it\nout',
          fontSize: 15,
          z: 35,
        ),
        ..._tape('p1_tape', [
          (0.163, 0.068, 0.105, 0.031, 4),
          (0.463, 0.111, 0.084, 0.024, -7),
          (0.698, 0.088, 0.072, 0.019, 6),
          (0.215, 0.325, 0.083, 0.023, -4),
          (0.585, 0.408, 0.080, 0.024, 5),
          (0.614, 0.716, 0.088, 0.024, -3),
        ]),
        _serif(
          id: 'title',
          x: 0.092,
          y: 0.697,
          width: 0.30,
          height: 0.065,
          text: 'piled up\nmoments',
          fontSize: 38,
          color: _charcoal,
          lineHeight: 0.9,
        ),
        _box(
          id: 'chip_left',
          x: 0.068,
          y: 0.878,
          width: 0.14,
          height: 0.028,
          fill: _blush,
          radius: 999,
          z: 18,
        ),
        _text(
          id: 'chip_left_text',
          x: 0.083,
          y: 0.884,
          width: 0.11,
          height: 0.014,
          text: 'mood board',
          align: 'center',
          fontSize: 10,
          fontWeight: 700,
          color: _cocoa,
        ),
        _box(
          id: 'chip_mid',
          x: 0.508,
          y: 0.85,
          width: 0.18,
          height: 0.03,
          fill: _blush,
          radius: 999,
          z: 18,
        ),
        _text(
          id: 'chip_mid_text',
          x: 0.535,
          y: 0.857,
          width: 0.12,
          height: 0.014,
          text: 'polaroid set',
          align: 'center',
          fontSize: 11,
          fontWeight: 700,
          color: _cocoa,
        ),
        _box(
          id: 'chip_right',
          x: 0.742,
          y: 0.784,
          width: 0.14,
          height: 0.03,
          fill: _sage,
          radius: 999,
          z: 18,
        ),
        _text(
          id: 'chip_right_text',
          x: 0.765,
          y: 0.791,
          width: 0.09,
          height: 0.014,
          text: 'photo pile',
          align: 'center',
          fontSize: 11,
          fontWeight: 700,
          color: '#FFFFFFFF',
        ),
        ..._stars('p1_star', [
          (0.835, 0.179, 0.012),
          (0.79, 0.804, 0.009),
          (0.83, 0.97, 0.01),
        ], color: '#FF263B57'),
      ],
    ),
    _page(
      number: 3,
      layoutId: 'torn_note_page',
      role: 'inner',
      photos: 2,
      layers: [
        _box(id: 'bg', x: 0, y: 0, width: 1, height: 1, fill: _paper, z: 1),
        _box(
          id: 'top_band',
          x: 0.06,
          y: 0.06,
          width: 0.86,
          height: 0.065,
          fill: _blush,
          z: 2,
        ),
        _box(
          id: 'paper_card',
          x: 0.09,
          y: 0.12,
          width: 0.82,
          height: 0.43,
          fill: '#FFFFFFFF',
          z: 3,
          rotation: 1.2,
        ),
        _box(
          id: 'heart_board',
          x: 0.11,
          y: 0.155,
          width: 0.76,
          height: 0.33,
          fill: _rose,
          z: 4,
        ),
        _text(
          id: 'hearts',
          x: 0.18,
          y: 0.17,
          width: 0.62,
          height: 0.26,
          text: '♡ ♡ ♡ ♡ ♡\n♥ ♥ ♥ ♥ ♥\n♥ ♥ ♥ ♥ ♥\n♥ ♥ ♥ ♥ ♥\n♥ ♥ ♥ ♥ ♥',
          align: 'center',
          fontFamily: 'Cormorant Garamond',
          fontSize: 42,
          fontWeight: 700,
          color: '#FFD7185A',
          lineHeight: 1.1,
          z: 8,
        ),
        _hand(
          id: 'title',
          x: 0.27,
          y: 0.56,
          width: 0.36,
          height: 0.04,
          text: 'today was lovely',
          fontSize: 33,
          color: '#FFB27A62',
          z: 30,
        ),
        ..._polaroid(
          id: 'p2_left',
          x: 0.085,
          y: 0.64,
          width: 0.22,
          height: 0.18,
          imageUrl: sunset,
          rotation: 6,
        ),
        ..._polaroid(
          id: 'p2_right',
          x: 0.62,
          y: 0.64,
          width: 0.22,
          height: 0.18,
          imageUrl: hands,
          rotation: -5,
        ),
        ..._tape('p2_tape', [
          (0.165, 0.62, 0.08, 0.024, 4),
          (0.665, 0.62, 0.08, 0.024, -5),
        ]),
        _serif(
          id: 'caption',
          x: 0.31,
          y: 0.72,
          width: 0.32,
          height: 0.028,
          text: 'stuck between coffee stains and sunshine',
          align: 'center',
          fontSize: 16,
          fontWeight: 500,
          color: _charcoal,
        ),
        _box(
          id: 'rule',
          x: 0.30,
          y: 0.748,
          width: 0.36,
          height: 0.001,
          fill: _warmGray,
          z: 4,
        ),
        ..._dotGrid(id: 'p2_dots', x: 0.72, y: 0.78, rows: 7, columns: 6, z: 4),
        _box(
          id: 'chip',
          x: 0.71,
          y: 0.875,
          width: 0.16,
          height: 0.03,
          fill: _navy,
          radius: 999,
          z: 20,
        ),
        _text(
          id: 'chip_text',
          x: 0.734,
          y: 0.882,
          width: 0.11,
          height: 0.014,
          text: 'memo archive',
          align: 'center',
          fontSize: 11,
          fontWeight: 700,
          color: '#FFFFFFFF',
        ),
      ],
    ),
    _page(
      number: 4,
      layoutId: 'washi_grid',
      role: 'inner',
      photos: 4,
      layers: [
        _box(id: 'bg', x: 0, y: 0, width: 1, height: 1, fill: _paper, z: 1),
        _box(
          id: 'large_panel',
          x: 0.056,
          y: 0.054,
          width: 0.89,
          height: 0.84,
          fill: _paperLight,
          radius: 0.014,
          z: 2,
        ),
        _box(
          id: 'hanger',
          x: 0.135,
          y: 0.12,
          width: 0.68,
          height: 0.003,
          fill: _warmGray,
          z: 3,
        ),
        ..._polaroid(
          id: 'p3_a',
          x: 0.13,
          y: 0.145,
          width: 0.24,
          height: 0.22,
          imageUrl: city,
          rotation: 4,
        ),
        ..._polaroid(
          id: 'p3_b',
          x: 0.39,
          y: 0.155,
          width: 0.22,
          height: 0.205,
          imageUrl: flower,
          rotation: -3,
        ),
        ..._polaroid(
          id: 'p3_c',
          x: 0.65,
          y: 0.145,
          width: 0.22,
          height: 0.215,
          imageUrl: sunset,
          rotation: 5,
        ),
        _box(
          id: 'note_panel',
          x: 0.095,
          y: 0.455,
          width: 0.30,
          height: 0.285,
          fill: '#FFFFFFFF',
          radius: 0.01,
          z: 4,
        ),
        _serif(
          id: 'note_title',
          x: 0.125,
          y: 0.49,
          width: 0.22,
          height: 0.032,
          text: 'washi & notes',
          fontSize: 32,
          color: _charcoal,
        ),
        _text(
          id: 'dot',
          x: 0.23,
          y: 0.595,
          width: 0.02,
          height: 0.02,
          text: '·',
          align: 'center',
          fontSize: 22,
          fontWeight: 700,
          color: _charcoal,
        ),
        ..._polaroid(
          id: 'p3_big',
          x: 0.46,
          y: 0.48,
          width: 0.30,
          height: 0.30,
          imageUrl: city,
          rotation: -3,
        ),
        ..._polaroid(
          id: 'p3_small',
          x: 0.60,
          y: 0.65,
          width: 0.18,
          height: 0.15,
          imageUrl: flower,
          rotation: 5,
        ),
        _box(
          id: 'mini_note',
          x: 0.63,
          y: 0.78,
          width: 0.13,
          height: 0.07,
          fill: _blush,
          radius: 0.008,
          rotation: 4,
          z: 18,
        ),
        _hand(
          id: 'mini_text',
          x: 0.66,
          y: 0.797,
          width: 0.075,
          height: 0.034,
          text: 'love\nthis',
          fontSize: 18,
          z: 35,
        ),
        ..._tape('p3_tape', [
          (0.18, 0.12, 0.07, 0.020, 3),
          (0.43, 0.125, 0.07, 0.020, 3),
          (0.66, 0.12, 0.07, 0.020, 3),
          (0.655, 0.637, 0.07, 0.020, 5),
        ]),
        _box(
          id: 'scrap_chip',
          x: 0.105,
          y: 0.79,
          width: 0.14,
          height: 0.032,
          fill: _sage,
          radius: 999,
          z: 18,
        ),
        _text(
          id: 'scrap_chip_text',
          x: 0.125,
          y: 0.798,
          width: 0.10,
          height: 0.014,
          text: 'scrap note',
          align: 'center',
          fontSize: 11,
          fontWeight: 700,
          color: '#FFFFFFFF',
        ),
        ..._stars('p3_star', [
          (0.785, 0.155, 0.011),
          (0.105, 0.844, 0.010),
          (0.795, 0.765, 0.008),
        ], color: '#FFC45C4E'),
      ],
    ),
    _page(
      number: 5,
      layoutId: 'stamp_note',
      role: 'inner',
      photos: 1,
      layers: [
        _box(
          id: 'bg',
          x: 0,
          y: 0,
          width: 1,
          height: 1,
          fill: _paperLight,
          z: 1,
        ),
        _image(
          id: 'hero',
          x: 0.10,
          y: 0.155,
          width: 0.44,
          height: 0.47,
          imageUrl: city,
          z: 10,
        ),
        _box(
          id: 'stamp_block',
          x: 0.64,
          y: 0.16,
          width: 0.22,
          height: 0.18,
          fill: _blush,
          radius: 0.018,
          z: 4,
        ),
        _text(
          id: 'date',
          x: 0.685,
          y: 0.19,
          width: 0.13,
          height: 0.08,
          text: '04\nJUN',
          align: 'center',
          fontFamily: 'Inter',
          fontSize: 42,
          fontWeight: 800,
          color: _cocoa,
          lineHeight: 1.12,
          z: 30,
        ),
        _box(
          id: 'note_card',
          x: 0.60,
          y: 0.39,
          width: 0.28,
          height: 0.24,
          fill: _paper,
          radius: 0.018,
          z: 4,
        ),
        _serif(
          id: 'note_title',
          x: 0.63,
          y: 0.43,
          width: 0.19,
          height: 0.028,
          text: 'a stamped note',
          fontSize: 21,
          color: _charcoal,
          fontWeight: 500,
        ),
        _text(
          id: 'body',
          x: 0.63,
          y: 0.49,
          width: 0.20,
          height: 0.12,
          text: '날짜를 크게 남기고\n짧은 문장을 붙여\n두는 페이지.',
          fontFamily: 'NotoSans',
          fontSize: 19,
          fontWeight: 500,
          color: _ink,
          lineHeight: 1.42,
        ),
        _box(
          id: 'tiny_note',
          x: 0.61,
          y: 0.70,
          width: 0.18,
          height: 0.10,
          fill: '#FFFFFFFF',
          radius: 0.006,
          rotation: -5,
          z: 10,
        ),
        _hand(
          id: 'tiny_note_text',
          x: 0.642,
          y: 0.72,
          width: 0.13,
          height: 0.054,
          text: 'sticker\nset',
          fontSize: 18,
          z: 35,
        ),
        _box(
          id: 'jun_chip',
          x: 0.67,
          y: 0.785,
          width: 0.10,
          height: 0.03,
          fill: '#FFE8DCA5',
          radius: 999,
          z: 20,
        ),
        _text(
          id: 'jun_text',
          x: 0.69,
          y: 0.792,
          width: 0.06,
          height: 0.014,
          text: '04 jun',
          align: 'center',
          fontSize: 11,
          fontWeight: 700,
          color: _cocoa,
        ),
        _box(
          id: 'small_tag',
          x: 0.085,
          y: 0.765,
          width: 0.13,
          height: 0.06,
          fill: _blush,
          radius: 0.006,
          rotation: 7,
          z: 10,
        ),
        _text(
          id: 'small_tag_text',
          x: 0.13,
          y: 0.785,
          width: 0.045,
          height: 0.018,
          text: 'JUN',
          align: 'center',
          fontSize: 12,
          fontWeight: 700,
          color: '#FFFFFFFF',
        ),
        ..._stars('p4_star', [
          (0.88, 0.175, 0.012),
          (0.865, 0.447, 0.008),
        ], color: '#FFB44A43'),
      ],
    ),
    _page(
      number: 6,
      layoutId: 'tape_wall',
      role: 'inner',
      photos: 3,
      layers: [
        _box(
          id: 'bg',
          x: 0,
          y: 0,
          width: 1,
          height: 1,
          fill: _paperLight,
          z: 1,
        ),
        ..._polaroid(
          id: 'wall_hero',
          x: 0.10,
          y: 0.10,
          width: 0.52,
          height: 0.56,
          imageUrl: sunset,
          rotation: -2,
        ),
        ..._polaroid(
          id: 'wall_side_a',
          x: 0.70,
          y: 0.12,
          width: 0.22,
          height: 0.21,
          imageUrl: flower,
          rotation: 4,
        ),
        ..._polaroid(
          id: 'wall_side_b',
          x: 0.70,
          y: 0.37,
          width: 0.22,
          height: 0.21,
          imageUrl: city,
          rotation: -3,
        ),
        ..._polaroid(
          id: 'wall_side_c',
          x: 0.73,
          y: 0.62,
          width: 0.16,
          height: 0.14,
          imageUrl: ceremony,
          rotation: 5,
        ),
        ..._tape('wall_tape', [
          (0.74, 0.095, 0.08, 0.023, -4),
          (0.735, 0.345, 0.08, 0.023, 5),
          (0.755, 0.595, 0.07, 0.020, -5),
        ]),
        _serif(
          id: 'wall_title',
          x: 0.10,
          y: 0.70,
          width: 0.34,
          height: 0.04,
          text: 'captured\non the wall',
          fontSize: 35,
          color: _charcoal,
          lineHeight: 0.95,
        ),
        _text(
          id: 'wall_body',
          x: 0.10,
          y: 0.772,
          width: 0.42,
          height: 0.045,
          text: '겹쳐 붙인 사진과 작은 메모가\n한 장의 보드처럼 보이도록.',
          fontFamily: 'NotoSans',
          fontSize: 14,
          fontWeight: 500,
          color: _ink,
          lineHeight: 1.35,
        ),
        _box(
          id: 'wall_note',
          x: 0.68,
          y: 0.76,
          width: 0.18,
          height: 0.10,
          fill: _paper,
          radius: 0.008,
          rotation: -5,
          z: 18,
        ),
        _hand(
          id: 'wall_note_text',
          x: 0.72,
          y: 0.785,
          width: 0.09,
          height: 0.04,
          text: 'one more\nclip',
          fontSize: 18,
          z: 35,
        ),
        _box(
          id: 'wall_badge',
          x: 0.70,
          y: 0.88,
          width: 0.16,
          height: 0.032,
          fill: _sage,
          radius: 999,
          z: 18,
        ),
        _text(
          id: 'wall_badge_text',
          x: 0.725,
          y: 0.887,
          width: 0.11,
          height: 0.014,
          text: 'archived',
          align: 'center',
          fontSize: 11,
          fontWeight: 700,
          color: '#FFFFFFFF',
        ),
        ..._stars('wall_star', [
          (0.66, 0.765, 0.010),
          (0.88, 0.90, 0.012),
        ], color: '#FFC45C4E'),
      ],
    ),
    _page(
      number: 7,
      layoutId: 'weekend_note',
      role: 'inner',
      photos: 3,
      layers: [
        _box(id: 'bg', x: 0, y: 0, width: 1, height: 1, fill: _paper, z: 1),
        _box(
          id: 'journal',
          x: 0.09,
          y: 0.09,
          width: 0.82,
          height: 0.84,
          fill: _paperLight,
          radius: 0.012,
          z: 2,
        ),
        ..._grid(
          id: 'journal_grid',
          x: 0.115,
          y: 0.112,
          width: 0.28,
          height: 0.153,
          columns: 7,
          rows: 6,
          z: 3,
        ),
        _serif(
          id: 'headline',
          x: 0.12,
          y: 0.13,
          width: 0.25,
          height: 0.04,
          text: 'weekend note',
          fontSize: 28,
          color: _charcoal,
        ),
        _text(
          id: 'body',
          x: 0.12,
          y: 0.19,
          width: 0.28,
          height: 0.09,
          text: 'small paper,\nphoto card,\nand tiny notes.',
          fontFamily: 'NotoSans',
          fontSize: 13,
          color: _ink,
          lineHeight: 1.35,
        ),
        ..._polaroid(
          id: 'note_top',
          x: 0.52,
          y: 0.13,
          width: 0.33,
          height: 0.25,
          imageUrl: city,
          rotation: 3,
        ),
        ..._polaroid(
          id: 'note_mid',
          x: 0.14,
          y: 0.46,
          width: 0.44,
          height: 0.31,
          imageUrl: flower,
          rotation: -1,
        ),
        ..._polaroid(
          id: 'note_tiny',
          x: 0.70,
          y: 0.72,
          width: 0.16,
          height: 0.14,
          imageUrl: sunset,
          rotation: 5,
        ),
        _box(
          id: 'postit',
          x: 0.60,
          y: 0.39,
          width: 0.16,
          height: 0.15,
          fill: '#FFF4DCCC',
          radius: 0.008,
          rotation: -3,
          z: 18,
        ),
        _text(
          id: 'postit_text',
          x: 0.63,
          y: 0.415,
          width: 0.10,
          height: 0.10,
          text: 'covered\nwith\nsmall paper',
          fontSize: 13,
          fontFamily: 'Figma Hand',
          color: _ink,
          lineHeight: 1.15,
          z: 35,
        ),
        ..._tape('note_tape', [
          (0.55, 0.105, 0.08, 0.022, -4),
          (0.74, 0.695, 0.07, 0.020, 5),
        ]),
        _box(
          id: 'saved_chip',
          x: 0.12,
          y: 0.86,
          width: 0.14,
          height: 0.03,
          fill: _sage,
          radius: 999,
          z: 18,
        ),
        _text(
          id: 'saved_chip_text',
          x: 0.14,
          y: 0.867,
          width: 0.10,
          height: 0.014,
          text: 'keep safe',
          align: 'center',
          fontSize: 10,
          fontWeight: 700,
          color: '#FFFFFFFF',
        ),
      ],
    ),
    _page(
      number: 8,
      layoutId: 'stacked_postcards',
      role: 'inner',
      photos: 4,
      layers: [
        _box(
          id: 'bg',
          x: 0,
          y: 0,
          width: 1,
          height: 1,
          fill: _paperLight,
          z: 1,
        ),
        _box(
          id: 'outer_patch',
          x: 0.08,
          y: 0.08,
          width: 0.84,
          height: 0.84,
          fill: _paper,
          radius: 0.012,
          z: 2,
        ),
        ..._polaroid(
          id: 'post_a',
          x: 0.145,
          y: 0.12,
          width: 0.56,
          height: 0.53,
          imageUrl: city,
          rotation: -4,
        ),
        ..._polaroid(
          id: 'post_b',
          x: 0.25,
          y: 0.16,
          width: 0.52,
          height: 0.50,
          imageUrl: sunset,
          rotation: 2,
        ),
        ..._polaroid(
          id: 'post_c',
          x: 0.335,
          y: 0.21,
          width: 0.48,
          height: 0.47,
          imageUrl: ceremony,
          rotation: 5,
        ),
        ..._polaroid(
          id: 'post_d',
          x: 0.70,
          y: 0.72,
          width: 0.16,
          height: 0.13,
          imageUrl: flower,
          rotation: -5,
        ),
        ..._tape('post_tape', [
          (0.25, 0.13, 0.09, 0.024, -6),
          (0.36, 0.19, 0.08, 0.022, 4),
          (0.45, 0.235, 0.075, 0.020, -5),
          (0.72, 0.69, 0.07, 0.020, 4),
        ]),
        _serif(
          id: 'post_title',
          x: 0.10,
          y: 0.77,
          width: 0.26,
          height: 0.06,
          text: 'layered\npostcard',
          fontSize: 34,
          color: _charcoal,
          lineHeight: 0.92,
        ),
        _text(
          id: 'post_body',
          x: 0.40,
          y: 0.795,
          width: 0.34,
          height: 0.035,
          text: 'stacked paper and one tiny memory',
          fontSize: 13,
          color: _ink,
        ),
        _box(
          id: 'note',
          x: 0.12,
          y: 0.70,
          width: 0.18,
          height: 0.10,
          fill: _blush,
          radius: 0.006,
          rotation: -4,
          z: 18,
        ),
        _hand(
          id: 'note_text',
          x: 0.15,
          y: 0.723,
          width: 0.10,
          height: 0.05,
          text: 'one\nmore',
          fontSize: 18,
          z: 35,
        ),
        ..._stars('post_star', [(0.30, 0.71, 0.01), (0.33, 0.80, 0.008)]),
      ],
    ),
    _page(
      number: 9,
      layoutId: 'stamp_note_alt',
      role: 'inner',
      photos: 3,
      layers: [
        _box(
          id: 'bg',
          x: 0,
          y: 0,
          width: 1,
          height: 1,
          fill: '#FFD8D1C8',
          z: 1,
        ),
        _box(
          id: 'heart_panel',
          x: 0.31,
          y: 0.16,
          width: 0.28,
          height: 0.24,
          fill: '#FFF5D1DA',
          z: 2,
        ),
        _text(
          id: 'heart_grid',
          x: 0.35,
          y: 0.20,
          width: 0.20,
          height: 0.13,
          text: '♡ ♡ ♡\n♥ ♥ ♥\n♥ ♥ ♥\n♥ ♥ ♥',
          fontSize: 26,
          fontFamily: 'Cormorant Garamond',
          fontWeight: 700,
          color: '#FFC84E76',
          lineHeight: 1.08,
          align: 'center',
        ),
        _image(
          id: 'left',
          x: 0.16,
          y: 0.46,
          width: 0.18,
          height: 0.16,
          imageUrl: hands,
          z: 10,
        ),
        _image(
          id: 'top_right',
          x: 0.58,
          y: 0.18,
          width: 0.18,
          height: 0.14,
          imageUrl: sunset,
          z: 10,
        ),
        _image(
          id: 'bottom_right',
          x: 0.58,
          y: 0.48,
          width: 0.16,
          height: 0.14,
          imageUrl: city,
          z: 10,
        ),
        _box(
          id: 'tiny_note',
          x: 0.75,
          y: 0.70,
          width: 0.10,
          height: 0.05,
          fill: _paperLight,
          z: 4,
        ),
        _hand(
          id: 'tiny_note_text',
          x: 0.766,
          y: 0.717,
          width: 0.08,
          height: 0.024,
          text: 'saved',
          fontSize: 10,
        ),
      ],
    ),
    _page(
      number: 10,
      layoutId: 'four_cut',
      role: 'inner',
      photos: 4,
      layers: [
        _box(
          id: 'bg',
          x: 0,
          y: 0,
          width: 1,
          height: 1,
          fill: _paperLight,
          z: 1,
        ),
        ..._polaroid(
          id: 'cut_a',
          x: 0.107,
          y: 0.132,
          width: 0.352,
          height: 0.292,
          imageUrl: hands,
        ),
        ..._polaroid(
          id: 'cut_b',
          x: 0.541,
          y: 0.132,
          width: 0.352,
          height: 0.292,
          imageUrl: sunset,
        ),
        ..._polaroid(
          id: 'cut_c',
          x: 0.107,
          y: 0.464,
          width: 0.352,
          height: 0.292,
          imageUrl: city,
        ),
        ..._polaroid(
          id: 'cut_d',
          x: 0.541,
          y: 0.464,
          width: 0.352,
          height: 0.292,
          imageUrl: ceremony,
        ),
        _hand(
          id: 'cut_title',
          x: 0.22,
          y: 0.775,
          width: 0.26,
          height: 0.03,
          text: 'four tiny keepsakes',
          fontSize: 18,
        ),
        _box(
          id: 'note',
          x: 0.75,
          y: 0.72,
          width: 0.14,
          height: 0.09,
          fill: _paper,
          rotation: -4,
          z: 18,
        ),
        _hand(
          id: 'note_text',
          x: 0.78,
          y: 0.745,
          width: 0.07,
          height: 0.035,
          text: 'tiny\nnote',
          fontSize: 14,
          z: 35,
        ),
        _box(
          id: 'badge',
          x: 0.72,
          y: 0.82,
          width: 0.10,
          height: 0.028,
          fill: _blush,
          radius: 999,
          z: 18,
        ),
        _text(
          id: 'badge_text',
          x: 0.735,
          y: 0.827,
          width: 0.07,
          height: 0.012,
          text: 'kept',
          align: 'center',
          fontSize: 10,
          fontWeight: 700,
          color: _cocoa,
        ),
        ..._stars('cut_star', [(0.69, 0.73, 0.010), (0.86, 0.81, 0.012)]),
      ],
    ),
    _page(
      number: 11,
      layoutId: 'souvenir_page',
      role: 'inner',
      photos: 4,
      layers: [
        _box(id: 'bg', x: 0, y: 0, width: 1, height: 1, fill: _paper, z: 1),
        _box(
          id: 'souvenir_bg',
          x: 0.08,
          y: 0.083,
          width: 0.84,
          height: 0.82,
          fill: _paperLight,
          radius: 0.012,
          z: 2,
        ),
        ..._polaroid(
          id: 'souvenir_main',
          x: 0.12,
          y: 0.122,
          width: 0.46,
          height: 0.42,
          imageUrl: city,
        ),
        _box(
          id: 'receipt',
          x: 0.625,
          y: 0.148,
          width: 0.25,
          height: 0.30,
          fill: '#FFFFFFFF',
          radius: 0.005,
          z: 5,
        ),
        _text(
          id: 'receipt_text',
          x: 0.662,
          y: 0.182,
          width: 0.16,
          height: 0.17,
          text:
              'RECEIPT\ncoffee  4.0\nphoto   1.0\nmemory  ∞\n\npaid with\nsmall joy',
          fontSize: 13,
          fontFamily: 'NotoSans',
          fontWeight: 600,
          color: _ink,
          lineHeight: 1.35,
          z: 30,
        ),
        ..._polaroid(
          id: 'souvenir_small',
          x: 0.61,
          y: 0.53,
          width: 0.29,
          height: 0.20,
          imageUrl: flower,
          rotation: 3,
        ),
        ..._polaroid(
          id: 'souvenir_hang',
          x: 0.65,
          y: 0.67,
          width: 0.17,
          height: 0.14,
          imageUrl: sunset,
          rotation: -4,
        ),
        ..._tape('souvenir_tape', [(0.70, 0.645, 0.07, 0.018, 4)]),
        _serif(
          id: 'title',
          x: 0.12,
          y: 0.78,
          width: 0.30,
          height: 0.04,
          text: 'souvenir page',
          fontSize: 30,
          color: _charcoal,
        ),
        _box(
          id: 'badge',
          x: 0.12,
          y: 0.82,
          width: 0.14,
          height: 0.03,
          fill: _blush,
          radius: 999,
          z: 18,
        ),
        _text(
          id: 'badge_text',
          x: 0.14,
          y: 0.827,
          width: 0.10,
          height: 0.014,
          text: 'saved',
          align: 'center',
          fontSize: 10,
          fontWeight: 700,
          color: _cocoa,
        ),
      ],
    ),
    _page(
      number: 12,
      layoutId: 'ending_memory',
      role: 'inner',
      photos: 4,
      layers: [
        _box(
          id: 'bg',
          x: 0,
          y: 0,
          width: 1,
          height: 1,
          fill: _paperLight,
          z: 1,
        ),
        ..._polaroid(
          id: 'end_top',
          x: 0.10,
          y: 0.08,
          width: 0.80,
          height: 0.36,
          imageUrl: city,
        ),
        _serif(
          id: 'title',
          x: 0.11,
          y: 0.51,
          width: 0.38,
          height: 0.065,
          text: 'keep this\npage',
          fontSize: 42,
          color: _charcoal,
          lineHeight: 0.9,
        ),
        _text(
          id: 'body',
          x: 0.11,
          y: 0.61,
          width: 0.46,
          height: 0.035,
          text: 'as one small scrap to open again',
          fontSize: 13,
          color: _ink,
        ),
        _box(
          id: 'bottom_patch',
          x: 0.09,
          y: 0.675,
          width: 0.80,
          height: 0.19,
          fill: _oat,
          radius: 0.012,
          z: 2,
        ),
        ..._polaroid(
          id: 'bottom_a',
          x: 0.12,
          y: 0.695,
          width: 0.25,
          height: 0.16,
          imageUrl: sunset,
        ),
        ..._polaroid(
          id: 'bottom_b',
          x: 0.41,
          y: 0.72,
          width: 0.25,
          height: 0.15,
          imageUrl: flower,
        ),
        ..._polaroid(
          id: 'bottom_c',
          x: 0.70,
          y: 0.70,
          width: 0.16,
          height: 0.14,
          imageUrl: hands,
        ),
        _box(
          id: 'note',
          x: 0.67,
          y: 0.58,
          width: 0.17,
          height: 0.10,
          fill: _paper,
          radius: 0.008,
          rotation: -4,
          z: 18,
        ),
        _hand(
          id: 'note_text',
          x: 0.71,
          y: 0.607,
          width: 0.08,
          height: 0.035,
          text: 'last\nclip',
          fontSize: 16,
          z: 35,
        ),
        ..._stars('end_star', [(0.64, 0.58, 0.010), (0.84, 0.67, 0.012)]),
      ],
    ),
    _page(
      number: 13,
      layoutId: 'dark_archive',
      role: 'inner',
      photos: 1,
      layers: [
        _box(id: 'bg', x: 0, y: 0, width: 1, height: 1, fill: _charcoal, z: 1),
        _box(
          id: 'heart_panel',
          x: 0.20,
          y: 0.12,
          width: 0.46,
          height: 0.22,
          fill: '#FFF5D1DA',
          z: 2,
        ),
        _text(
          id: 'heart_grid',
          x: 0.24,
          y: 0.18,
          width: 0.38,
          height: 0.08,
          text: '♡ ♡ ♡ ♡\n♥ ♥ ♥ ♥\n♥ ♥ ♥ ♥',
          fontSize: 24,
          fontFamily: 'Cormorant Garamond',
          fontWeight: 700,
          color: '#FFC84E76',
          lineHeight: 1.08,
          align: 'center',
        ),
        _hand(
          id: 'ending',
          x: 0.18,
          y: 0.43,
          width: 0.32,
          height: 0.04,
          text: 'keep this page',
          color: _paper,
          fontSize: 22,
        ),
        _text(
          id: 'meta',
          x: 0.18,
          y: 0.49,
          width: 0.26,
          height: 0.03,
          text: 'for later',
          fontSize: 11,
          fontWeight: 700,
          color: _paper,
          letterSpacing: 1.8,
        ),
        _box(
          id: 'card',
          x: 0.18,
          y: 0.60,
          width: 0.45,
          height: 0.13,
          fill: _paper,
          z: 3,
        ),
        ..._polaroid(
          id: 'tiny_polaroid',
          x: 0.72,
          y: 0.66,
          width: 0.11,
          height: 0.09,
          imageUrl: city,
          rotation: -4,
        ),
        _box(
          id: 'tiny_note',
          x: 0.68,
          y: 0.59,
          width: 0.10,
          height: 0.05,
          fill: _blush,
          z: 4,
        ),
        _hand(
          id: 'tiny_note_text',
          x: 0.697,
          y: 0.607,
          width: 0.08,
          height: 0.024,
          text: 'mini',
          fontSize: 10,
        ),
      ],
    ),
    _page(
      number: 14,
      layoutId: 'quiet_note',
      role: 'inner',
      photos: 1,
      layers: [
        _box(
          id: 'bg',
          x: 0,
          y: 0,
          width: 1,
          height: 1,
          fill: _paperLight,
          z: 1,
        ),
        _box(
          id: 'panel',
          x: 0.14,
          y: 0.15,
          width: 0.72,
          height: 0.66,
          fill: _paper,
          radius: 0.012,
          z: 2,
        ),
        _box(
          id: 'tape',
          x: 0.44,
          y: 0.135,
          width: 0.12,
          height: 0.024,
          fill: _tapeColor,
          radius: 0.004,
          rotation: -2,
          z: 20,
        ),
        _serif(
          id: 'title',
          x: 0.26,
          y: 0.29,
          width: 0.36,
          height: 0.08,
          text: 'a quiet\nscrapbook',
          align: 'center',
          fontSize: 44,
          color: _charcoal,
          lineHeight: 0.95,
        ),
        _text(
          id: 'body',
          x: 0.27,
          y: 0.43,
          width: 0.46,
          height: 0.06,
          text: 'blank space is kept intentionally\nfor one short memory note.',
          align: 'center',
          fontSize: 14,
          color: _ink,
          lineHeight: 1.35,
        ),
        _image(
          id: 'quiet_memory',
          x: 0.40,
          y: 0.505,
          width: 0.20,
          height: 0.12,
          imageUrl: flower,
          z: 12,
        ),
        _box(
          id: 'sticker',
          x: 0.38,
          y: 0.58,
          width: 0.22,
          height: 0.034,
          fill: _blush,
          radius: 999,
          z: 18,
        ),
        _text(
          id: 'sticker_text',
          x: 0.405,
          y: 0.588,
          width: 0.17,
          height: 0.014,
          text: 'memory board',
          align: 'center',
          fontSize: 11,
          fontWeight: 700,
          color: _cocoa,
        ),
        ..._stars('quiet_star', [(0.77, 0.64, 0.013)]),
      ],
    ),
    _page(
      number: 15,
      layoutId: 'ending_memory_card',
      role: 'inner',
      photos: 4,
      layers: [
        _box(
          id: 'bg',
          x: 0,
          y: 0,
          width: 1,
          height: 1,
          fill: _paperLight,
          z: 1,
        ),
        ..._polaroid(
          id: 'ending_hero',
          x: 0.10,
          y: 0.08,
          width: 0.80,
          height: 0.36,
          imageUrl: flower,
        ),
        _serif(
          id: 'title',
          x: 0.11,
          y: 0.51,
          width: 0.38,
          height: 0.065,
          text: 'keep this\npage',
          fontSize: 42,
          color: _charcoal,
          lineHeight: 0.9,
        ),
        _text(
          id: 'body',
          x: 0.11,
          y: 0.61,
          width: 0.46,
          height: 0.035,
          text: 'as one small scrap to open again',
          fontSize: 13,
          color: _ink,
        ),
        _box(
          id: 'bottom_patch',
          x: 0.09,
          y: 0.675,
          width: 0.80,
          height: 0.19,
          fill: _oat,
          radius: 0.012,
          z: 2,
        ),
        ..._polaroid(
          id: 'ending_bottom_a',
          x: 0.12,
          y: 0.695,
          width: 0.25,
          height: 0.16,
          imageUrl: sunset,
        ),
        ..._polaroid(
          id: 'ending_bottom_b',
          x: 0.41,
          y: 0.72,
          width: 0.25,
          height: 0.15,
          imageUrl: flower,
        ),
        ..._polaroid(
          id: 'ending_bottom_c',
          x: 0.70,
          y: 0.70,
          width: 0.16,
          height: 0.14,
          imageUrl: hands,
        ),
        _box(
          id: 'note',
          x: 0.67,
          y: 0.58,
          width: 0.17,
          height: 0.10,
          fill: _paper,
          radius: 0.008,
          rotation: -4,
          z: 18,
        ),
        _hand(
          id: 'note_text',
          x: 0.71,
          y: 0.607,
          width: 0.08,
          height: 0.035,
          text: 'last\nclip',
          fontSize: 16,
          z: 35,
        ),
        ..._stars('ending_star', [(0.64, 0.58, 0.010), (0.84, 0.67, 0.012)]),
      ],
    ),
    _page(
      number: 16,
      layoutId: 'back_cover',
      role: 'ending',
      photos: 1,
      layers: [
        _box(
          id: 'bg',
          x: 0,
          y: 0,
          width: 1,
          height: 1,
          fill: _paperLight,
          z: 1,
        ),
        _box(
          id: 'back_card',
          x: 0.13,
          y: 0.16,
          width: 0.74,
          height: 0.67,
          fill: _paper,
          radius: 0.012,
          z: 2,
        ),
        _box(
          id: 'tape',
          x: 0.44,
          y: 0.139,
          width: 0.12,
          height: 0.026,
          fill: _tapeColor,
          radius: 0.004,
          rotation: -2,
          z: 20,
        ),
        _serif(
          id: 'title',
          x: 0.24,
          y: 0.27,
          width: 0.34,
          height: 0.08,
          text: 'the end\nof scraps',
          fontSize: 44,
          color: _charcoal,
          lineHeight: 0.94,
        ),
        _text(
          id: 'body',
          x: 0.24,
          y: 0.40,
          width: 0.50,
          height: 0.06,
          text:
              'A small archive of pieces, colors, paper,\nand photos that made the day feel real.',
          fontSize: 14,
          color: _ink,
          lineHeight: 1.35,
        ),
        _box(
          id: 'note_left',
          x: 0.24,
          y: 0.60,
          width: 0.17,
          height: 0.10,
          fill: _blush,
          radius: 0.008,
          rotation: -4,
          z: 18,
        ),
        _hand(
          id: 'note_left_text',
          x: 0.27,
          y: 0.626,
          width: 0.10,
          height: 0.04,
          text: 'final\nnote',
          fontSize: 16,
          z: 35,
        ),
        ..._polaroid(
          id: 'back_extra',
          x: 0.62,
          y: 0.61,
          width: 0.18,
          height: 0.15,
          imageUrl: city,
          rotation: 5,
        ),
        ..._tape('back_tape', [(0.657, 0.585, 0.075, 0.021, 5)]),
        _box(
          id: 'badge',
          x: 0.565,
          y: 0.78,
          width: 0.13,
          height: 0.03,
          fill: _sage,
          radius: 999,
          z: 18,
        ),
        _text(
          id: 'badge_text',
          x: 0.59,
          y: 0.787,
          width: 0.08,
          height: 0.014,
          text: 'xoxo',
          align: 'center',
          fontSize: 11,
          fontWeight: 700,
          color: '#FFFFFFFF',
        ),
        ..._stars('back_star', [(0.84, 0.68, 0.014), (0.40, 0.605, 0.010)]),
      ],
    ),
  ];
}

bool _isFullBleed(Map<String, dynamic> layer) {
  if (layer['type'] != 'IMAGE') return false;
  final x = (layer['x'] as num?)?.toDouble() ?? 0;
  final y = (layer['y'] as num?)?.toDouble() ?? 0;
  final w = (layer['width'] as num?)?.toDouble() ?? 0;
  final h = (layer['height'] as num?)?.toDouble() ?? 0;
  return x <= 0.02 && y <= 0.02 && w >= 0.98 && h >= 0.98;
}

void _adapt(List<Map<String, dynamic>> layers, String ratioType) {
  final verticalScale = ratioType == 'landscape' ? 0.72 : 0.88;
  final topInset = ratioType == 'landscape' ? 0.06 : 0.035;
  for (final layer in layers) {
    if (_isFullBleed(layer)) {
      layer['x'] = 0.0;
      layer['y'] = 0.0;
      layer['width'] = 1.0;
      layer['height'] = 1.0;
      continue;
    }
    final y = (layer['y'] as num).toDouble();
    final h = (layer['height'] as num).toDouble();
    layer['y'] = topInset + (y * verticalScale);
    layer['height'] = (h * verticalScale).clamp(0.02, 1.0);
    if (layer['type'] == 'TEXT' && ratioType == 'landscape') {
      final style =
          (layer['payload'] as Map<String, dynamic>)['textStyle']
              as Map<String, dynamic>;
      final fontSize = (style['fontSize'] as num).toDouble();
      style['fontSize'] = (fontSize * 0.9).clamp(9.0, 72.0);
    }
  }
}

List<Map<String, dynamic>> _adaptPages(
  List<Map<String, dynamic>> pages,
  String ratioType,
) {
  final cloned = jsonDecode(jsonEncode(pages)) as List<dynamic>;
  final next = cloned.cast<Map<String, dynamic>>();
  for (final page in next) {
    final layers = (page['layers'] as List).cast<Map<String, dynamic>>();
    _adapt(layers, ratioType);
  }
  return next;
}

Map<String, dynamic> _templateJson() {
  final portrait = _portraitPages();
  final square = _adaptPages(portrait, 'square');
  final landscape = _adaptPages(portrait, 'landscape');
  return {
    'schemaVersion': 1,
    'strictLayout': true,
    'autoFit': false,
    'autoFitPadding': 0.0,
    'aspect': 'portrait',
    'designWidth': 1080,
    'designHeight': 1440,
    'templateId': 'scrapbook_v1',
    'version': 2,
    'lifecycleStatus': 'published',
    'ratio': '9:16',
    'cover': {'pageNumber': 1, 'layers': portrait.first['layers']},
    'metadata': {
      'style': 'scrapbook_pinterest_layered',
      'designWidth': 1080,
      'designHeight': 1440,
      'difficulty': 3,
      'recommendedPhotoCount': 10,
      'mood': 'layered_paper_collage',
      'tags': ['스크랩북', '콜라주', '메모', '테이프', '다이어리'],
      'templateType': 'scrapbook',
      'theme': 'memory_board',
      'title': 'Scrapbook',
      'category': '스크랩북',
      'heroTextSafeArea': {'x': 0.1, 'y': 0.68, 'width': 0.55, 'height': 0.14},
      'sourceBottomSheetTemplateIds': ['scrapbook_v1'],
      'applyScope': 'cover_and_pages',
      'bottomSheetReferenceMode': 'style_and_tone_only',
    },
    'pages': portrait,
    'variants': {
      'square': {
        'variantId': 'scrapbook_square',
        'aspect': 'square',
        'ratio': '1:1',
        'designWidth': 1440,
        'designHeight': 1440,
        'metadata': {'templateType': 'scrapbook', 'theme': 'memory_board'},
        'pages': square,
      },
      'landscape': {
        'variantId': 'scrapbook_landscape',
        'aspect': 'landscape',
        'ratio': '16:9',
        'designWidth': 1440,
        'designHeight': 1080,
        'metadata': {'templateType': 'scrapbook', 'theme': 'memory_board'},
        'pages': landscape,
      },
    },
  };
}

Map<String, dynamic> _storeEntry() {
  final previews = <String>[
    _asset('ceremony_moment.png'),
    _asset('sunset_pair.png'),
    _asset('hands_bw.png'),
    _asset('flower_table.png'),
    _asset('city_weekend.png'),
    _asset('sunset_pair.png'),
    _asset('city_weekend.png'),
    _asset('ceremony_moment.png'),
    _asset('hands_bw.png'),
    _asset('sunset_pair.png'),
    _asset('flower_table.png'),
    _asset('city_weekend.png'),
    _asset('hands_bw.png'),
    _asset('flower_table.png'),
    _asset('city_weekend.png'),
    _asset('flower_table.png'),
  ];
  return {
    'id': 51,
    'title': 'Scrapbook',
    'subTitle': '스크랩북 · layered collage',
    'description': '겹쳐 붙인 종이와 메모, 테이프, 폴라로이드 무드로 채운 Pinterest 감성 스크랩북 템플릿',
    'coverImageUrl': previews.first,
    'previewImages': previews,
    'pageCount': 16,
    'likeCount': 0,
    'userCount': 0,
    'category': '스크랩북',
    'tags': ['스크랩북', '콜라주', '다이어리', '메모', '감성'],
    'weeklyScore': 0,
    'isNew': true,
    'isBest': false,
    'isPremium': false,
    'isLiked': false,
    'templateId': 'scrapbook_v1',
    'version': 'v2',
    'lifecycleStatus': 'published',
    'templateJson': jsonEncode(_templateJson()),
  };
}

void main() {
  final entry = _storeEntry();
  File(_handoffPath)
    ..createSync(recursive: true)
    ..writeAsStringSync(const JsonEncoder.withIndent('  ').convert([entry]));
  File(_storePath)
    ..createSync(recursive: true)
    ..writeAsStringSync(const JsonEncoder.withIndent('  ').convert([entry]));

  stdout.writeln('Generated scrapbook template');
  stdout.writeln('handoff=$_handoffPath');
  stdout.writeln('store=$_storePath');
  stdout.writeln(
    'next=./scripts/template_asset_pipeline.sh --template-slug=scrapbook '
    '--template-store-json=$_storePath',
  );
}
