import 'dart:convert';
import 'dart:io';

// One contract drives server validation and the synchronous Flutter parser.
void main(List<String> args) {
  final data =
      jsonDecode(
            File(
              'supabase/functions/ai-album-draft/typography-contract.json',
            ).readAsStringSync(),
          )
          as Map<String, dynamic>;
  final body =
      '''// Generated by tool/generate_ai_typography.dart. Do not edit.
const aiTemplateTypographyContract = ${const JsonEncoder.withIndent('  ').convert(data)};
''';
  final file = File(
    'lib/features/album/ai_album/domain/ai_template_typography.g.dart',
  );
  if (args.contains('--check')) {
    if (!file.existsSync() || file.readAsStringSync() != body) {
      stderr.writeln(
        'AI typography contract is stale. Run dart tool/generate_ai_typography.dart',
      );
      exitCode = 1;
    }
  } else {
    file.writeAsStringSync(body);
  }
}
