part of 'authored_collections.dart';

enum FreeCollectionVolume {
  vows('our-vows', '우리의 서약', '두 사람의 말로 채우는 결혼 기록', '웨딩', -9401),
  garden('garden-promise', '정원에서의 약속', '꽃과 초록 사이에 간직한 하루', '웨딩', -9402),
  cinema('one-fine-film', '영화 같던 하루', '한 편의 영화처럼 남기는 웨딩 필름', '웨딩', -9403),
  letters('love-letters', '사랑의 편지', '사진 사이에 접어 둔 다정한 문장', '웨딩', -9404),
  seaside('across-the-sea', '바다를 건너', '물빛과 햇살을 모은 바다 여행', '여행', -9411),
  city('city-collector', '도시의 수집가', '거리와 취향을 분류하는 도시 기록', '여행', -9412),
  walking('slow-paths', '느리게 걷는 길', '걷고 쉬고 바라보며 남긴 장면', '여행', -9413),
  postcards('travel-postbox', '여행의 우편함', '엽서와 짧은 안부로 엮는 여행', '여행', -9414),
  table('seasonal-table', '계절의 식탁', '맛있는 순간으로 기억하는 계절', '일상', -9421),
  objects('taste-archive', '취향 보관함', '좋아하는 물건과 시간을 모은 책', '일상', -9422),
  together('better-together', '함께라서 좋은 날', '함께 웃던 얼굴과 오래 남을 이야기', '일상', -9423),
  weekend('weekend-temperature', '주말의 온도', '느슨한 오후를 위한 작은 사진 일기', '일상', -9424),
  firstYear('your-first-year', '너의 첫해', '열두 번의 처음을 담은 성장 연감', '성장·육아', -9431),
  littleSteps(
    'little-footsteps',
    '작은 걸음의 기록',
    '처음 앉고 걷고 웃던 순간의 관찰 노트',
    '성장·육아',
    -9432,
  ),
  babyBloom('you-are-spring', '너라는 봄', '부드러운 꽃빛으로 남기는 아기의 계절', '성장·육아', -9433),
  playroom(
    'growing-in-color',
    '알록달록 자라는 날',
    '호기심과 놀이로 채운 컬러 성장 일기',
    '성장·육아',
    -9434,
  ),
  birthday('first-birthday', '처음 맞는 생일', '첫 생일을 축하하는 작은 기념 앨범', '성장·육아', -9435),
  homeYear(
    'our-family-year',
    '우리 집의 사계절',
    '평범한 가족의 열두 장면을 모은 연감',
    '가족·친구',
    -9441,
  ),
  familyTable(
    'around-our-table',
    '한 식탁의 이야기',
    '함께 만들고 나누어 먹던 가족의 시간',
    '가족·친구',
    -9442,
  ),
  friendsUs(
    'our-good-company',
    '우리의 좋은 사이',
    '친구와의 웃음과 대화를 붙여 둔 우정 노트',
    '가족·친구',
    -9443,
  ),
  generations(
    'across-generations',
    '세대를 잇는 사진',
    '닮은 얼굴과 마음을 잇는 가족 사진집',
    '가족·친구',
    -9444,
  ),
  familyOuting(
    'a-picnic-together',
    '함께 떠난 소풍',
    '다 같이 보낸 바깥의 하루를 엮은 소풍책',
    '가족·친구',
    -9445,
  ),
  usDays(
    'dates-of-us',
    '너와 나의 날짜들',
    '처음 만난 날부터 이어 쓰는 두 사람의 연대기',
    '커플·기념일',
    -9451,
  ),
  dateFilm(
    'scenes-for-two',
    '둘만의 장면',
    '일상의 데이트를 담은 작은 필름 사진집',
    '커플·기념일',
    -9452,
  ),
  loveSeason(
    'seasons-of-love',
    '사랑이 머문 계절',
    '계절마다 달라지는 빛과 두 사람의 표정',
    '커플·기념일',
    -9453,
  ),
  anniversary('still-us', '오래도록 우리', '함께한 시간을 기념하는 다정한 선물', '커플·기념일', -9454),
  twoTickets(
    'collected-by-two',
    '둘이 모은 조각',
    '표와 엽서와 데이트 사진의 작은 스크랩북',
    '커플·기념일',
    -9455,
  ),
  pawDiary(
    'a-day-with-you',
    '너의 하루를 따라',
    '반려견의 표정과 생활을 기록하는 관찰 일기',
    '반려동물',
    -9461,
  ),
  catNap('shapes-of-naps', '낮잠의 모양', '고양이의 조용한 세계를 담은 사진 에세이', '반려동물', -9462),
  walkClub(
    'our-walking-promise',
    '산책이라는 약속',
    '반려견과 함께 걷는 길의 작은 지도책',
    '반려동물',
    -9463,
  ),
  petHome(
    'our-little-companion',
    '우리 집 작은 가족',
    '함께 살며 발견한 귀여운 습관의 기록',
    '반려동물',
    -9464,
  ),
  petPortrait(
    'the-kindest-face',
    '가장 다정한 얼굴',
    '소중한 반려동물을 위한 여백 있는 초상집',
    '반려동물',
    -9465,
  );

  const FreeCollectionVolume(
    this.id,
    this.title,
    this.subtitle,
    this.category,
    this.bundledId,
  );
  final String id, title, subtitle, category;
  final int bundledId;
  static FreeCollectionVolume? byId(String id) =>
      values.where((v) => v.id == id).firstOrNull;
  List<_FreeSpread> get _spreads =>
      _freeSpreadStories[this] ?? _lifeSpreadStories[this]!;
  List<String> get chapters =>
      _spreads.map((s) => s.title).toList(growable: false);
  EditorialCopy get defaultCopy =>
      _lifeDefaultCopy(category) ??
      EditorialCopy(
        place: category == '웨딩'
            ? '초여름의 작은 정원'
            : category == '여행'
            ? '바다 곁의 작은 마을'
            : '봄에서 여름으로',
        period: category == '웨딩'
            ? '2026. 05. 24'
            : category == '여행'
            ? '2026. 06. 12 ~ 18'
            : '2026. 04 ~ 06',
        byline: category == '일상' ? '수연의 기록' : '수연과 지후',
        note: switch (category) {
          '웨딩' =>
            '좋은 날에도 평범한 날에도 서로의 편이 되기로 했다.\n\n오늘의 마음을 잊지 않고, 작은 이야기에 귀 기울이며 살고 싶다. 함께해 준 모든 사람에게 이 마음을 전한다.',
          '여행' =>
            '낯선 길에서 뜻밖의 좋은 장면을 만났다.\n\n오래 앉아 있던 자리와 이름 모를 골목, 함께 웃었던 순간을 한 권에 담는다. 다음에도 우리만의 속도로 걸어 보기로.',
          _ =>
            '별일 없던 하루에도 좋은 순간은 있었다.\n\n마음에 든 접시와 읽던 책, 친구와 나누던 이야기를 조금씩 모았다. 다음 계절에도 이만큼의 다정함을 기억하고 싶다.',
        },
      );
  Map<String, dynamic> document(
    CollectionAspect aspect, {
    EditorialCopy? copy,
  }) => _buildFreeCollection(this, aspect, copy ?? defaultCopy);
}

enum _FreeLayout {
  opening,
  gallery,
  paired,
  window,
  contact,
  ledger,
  letter,
  postcard,
  mosaic,
  stillLife,
  panorama,
  timeline,
  keepsake,
  closing,
  milestone,
  ribbonPair,
  pinboard,
  fieldNotes,
  portraitEssay,
}

class _FreeSpread {
  const _FreeSpread(
    this.title,
    this.line,
    this.caption,
    this.layout,
    this.photo,
    this.detail,
  );
  final String title, line, caption;
  final _FreeLayout layout;
  final int photo, detail;
}

// Every spread has an authored story, photo pairing and composition. These are
// not generated from a repeating page-count loop or copied from retired books.
const _freeSpreadStories = <FreeCollectionVolume, List<_FreeSpread>>{
  FreeCollectionVolume.vows: [
    _FreeSpread(
      '우리의 첫 문장',
      '오늘부터\n같은 방향으로.',
      '서로를 바라보던 첫 장면.',
      _FreeLayout.opening,
      0,
      1,
    ),
    _FreeSpread(
      '서로를 고른 이유',
      '너와 함께라면\n평범한 날도 좋아.',
      '서로에게 들려주고 싶은 말.',
      _FreeLayout.letter,
      1,
      4,
    ),
    _FreeSpread(
      '준비하는 마음',
      '기다림에도\n빛이 들었다.',
      '마지막 단추와 조용한 숨.',
      _FreeLayout.paired,
      2,
      3,
    ),
    _FreeSpread(
      '작은 약속들',
      '잊지 않을\n세 가지 마음.',
      '자주 웃고, 잘 듣고, 함께 걷기.',
      _FreeLayout.ledger,
      4,
      0,
    ),
    _FreeSpread(
      '같은 걸음',
      '한 걸음씩\n우리의 속도로.',
      '손을 놓지 않고 걷던 길.',
      _FreeLayout.panorama,
      5,
      0,
    ),
    _FreeSpread(
      '서약의 순간',
      '많은 말보다\n진심으로.',
      '서로에게 건넨 짧은 약속.',
      _FreeLayout.window,
      3,
      4,
    ),
    _FreeSpread(
      '반지에 담은 뜻',
      '작은 원에\n담긴 긴 시간.',
      '매일의 선택을 기억하며.',
      _FreeLayout.stillLife,
      4,
      2,
    ),
    _FreeSpread(
      '함께한 사람들',
      '우리를 둘러싼\n다정한 얼굴.',
      '마음을 모아 준 사람들.',
      _FreeLayout.gallery,
      6,
      1,
    ),
    _FreeSpread(
      '웃음이 번지던 날',
      '사진 밖에서도\n웃고 있었다.',
      '작은 표정까지 오래 기억하기.',
      _FreeLayout.mosaic,
      0,
      6,
    ),
    _FreeSpread(
      '축하의 식탁',
      '한자리에\n모인 마음들.',
      '함께 나눈 음식과 이야기.',
      _FreeLayout.keepsake,
      1,
      7,
    ),
    _FreeSpread(
      '저녁의 대화',
      '하루가 끝나도\n이야기는 계속.',
      '조용히 되짚어 본 오늘.',
      _FreeLayout.postcard,
      7,
      2,
    ),
    _FreeSpread(
      '계속 쓰는 약속',
      '내일도\n서로의 편으로.',
      '우리의 다음 페이지에.',
      _FreeLayout.closing,
      0,
      3,
    ),
  ],
  FreeCollectionVolume.garden: [
    _FreeSpread(
      '정원의 초대',
      '초록 사이로\n너를 만나러.',
      '꽃이 피어 있던 길목.',
      _FreeLayout.window,
      0,
      4,
    ),
    _FreeSpread(
      '꽃을 고르는 시간',
      '너를 닮은\n색을 골랐다.',
      '그날의 꽃과 잎을 기억한다.',
      _FreeLayout.stillLife,
      4,
      2,
    ),
    _FreeSpread(
      '바람이 머문 자리',
      '잠시 멈춰\n바람을 듣다.',
      '베일 끝에 닿던 오후.',
      _FreeLayout.gallery,
      2,
      3,
    ),
    _FreeSpread(
      '만개한 마음',
      '천천히\n마음이 피었다.',
      '말보다 먼저 전해진 표정.',
      _FreeLayout.opening,
      0,
      1,
    ),
    _FreeSpread(
      '정원에서의 약속',
      '계절이 바뀌어도\n같은 마음으로.',
      '햇살 아래에서 나눈 서약.',
      _FreeLayout.panorama,
      5,
      0,
    ),
    _FreeSpread(
      '우리의 꽃다발',
      '오늘의 향기를\n책 사이에.',
      '리본과 꽃잎의 작은 기록.',
      _FreeLayout.keepsake,
      4,
      3,
    ),
    _FreeSpread(
      '다정한 손님',
      '좋은 사람들로\n채워진 정원.',
      '멀리서도 와 준 마음.',
      _FreeLayout.paired,
      6,
      1,
    ),
    _FreeSpread(
      '햇살 아래 웃음',
      '눈을 마주치면\n웃음이 났다.',
      '눈부셔서 더 좋았던 순간.',
      _FreeLayout.mosaic,
      0,
      6,
    ),
    _FreeSpread(
      '꽃이 놓인 식탁',
      '작은 꽃 한 송이\n이야기 한 조각.',
      '식탁 위에도 마음을 담았다.',
      _FreeLayout.contact,
      1,
      4,
    ),
    _FreeSpread(
      '정원의 기록',
      '꽃 이름보다\n마음을 기억해.',
      '그날 눈에 담은 색들.',
      _FreeLayout.ledger,
      4,
      2,
    ),
    _FreeSpread(
      '고마운 당신에게',
      '우리 곁에\n있어 주어서.',
      '꼭 전하고 싶은 감사.',
      _FreeLayout.letter,
      7,
      6,
    ),
    _FreeSpread(
      '다음 계절에도',
      '또 한 번\n함께 피어나자.',
      '다시 돌아오고 싶은 정원.',
      _FreeLayout.closing,
      0,
      5,
    ),
  ],
  FreeCollectionVolume.cinema: [
    _FreeSpread(
      '첫 장면',
      '오늘의 주인공은\n우리 두 사람.',
      '카메라가 켜지기 전부터.',
      _FreeLayout.opening,
      0,
      3,
    ),
    _FreeSpread(
      '준비의 장면들',
      '분주한 손끝\n고요한 마음.',
      '작은 움직임을 이어 붙이면.',
      _FreeLayout.contact,
      2,
      4,
    ),
    _FreeSpread(
      '마주 보는 순간',
      '대사 없이도\n알 수 있었지.',
      '처음 마주한 표정.',
      _FreeLayout.paired,
      0,
      2,
    ),
    _FreeSpread(
      '빛이 들어오다',
      '빛이 바뀌면\n장면도 달라져.',
      '창가에서 멈춘 시간.',
      _FreeLayout.window,
      2,
      3,
    ),
    _FreeSpread(
      '오래 남길 시퀀스',
      '천천히\n걸어 들어왔다.',
      '우리에게는 가장 긴 순간.',
      _FreeLayout.panorama,
      5,
      0,
    ),
    _FreeSpread(
      '오늘의 대사',
      '좋아하는 말을\n다시 들려줘.',
      '짧지만 선명했던 약속.',
      _FreeLayout.letter,
      3,
      4,
    ),
    _FreeSpread(
      '가까이 본 마음',
      '크게 웃던 얼굴\n떨리던 손.',
      '화면 가득 담아 두고 싶다.',
      _FreeLayout.mosaic,
      0,
      6,
    ),
    _FreeSpread(
      '장면의 조각',
      '꽃과 반지\n그리고 우리.',
      '이야기를 완성하는 작은 것.',
      _FreeLayout.stillLife,
      4,
      7,
    ),
    _FreeSpread(
      '함께 출연한 사람',
      '우리 이야기의\n소중한 얼굴들.',
      '고마운 이름을 한 명씩.',
      _FreeLayout.gallery,
      6,
      1,
    ),
    _FreeSpread(
      '저녁의 속도',
      '어둠이 내려도\n빛나던 순간.',
      '하루의 마지막 촬영.',
      _FreeLayout.timeline,
      7,
      0,
    ),
    _FreeSpread(
      '지우지 않을 컷',
      '완벽하지 않아도\n가장 우리답게.',
      '흔들려서 더 좋은 장면.',
      _FreeLayout.keepsake,
      0,
      2,
    ),
    _FreeSpread(
      '끝나지 않은 영화',
      '다음 장면은\n함께 만들기로.',
      '우리 영화의 첫 번째 권.',
      _FreeLayout.closing,
      7,
      5,
    ),
  ],
  FreeCollectionVolume.letters: [
    _FreeSpread(
      '사랑하는 너에게',
      '이 마음을\n한 권에 접어.',
      '처음 쓰는 우리의 편지.',
      _FreeLayout.letter,
      0,
      2,
    ),
    _FreeSpread(
      '편지의 첫 줄',
      '너를 생각하면\n좋은 말이 떠올라.',
      '짧게 적어 본 오늘의 마음.',
      _FreeLayout.opening,
      2,
      4,
    ),
    _FreeSpread(
      '기다리던 답장',
      '눈을 마주치면\n답을 알 수 있어.',
      '말없이 전해진 마음.',
      _FreeLayout.paired,
      0,
      3,
    ),
    _FreeSpread(
      '봉투 속의 꽃',
      '그날의 꽃을\n같이 보내요.',
      '사진으로 남긴 작은 꽃다발.',
      _FreeLayout.keepsake,
      4,
      2,
    ),
    _FreeSpread(
      '우리의 날짜',
      '수많은 날 중\n이날을 기억해.',
      '달력에 오래 남겨 둘 표시.',
      _FreeLayout.ledger,
      3,
      7,
    ),
    _FreeSpread(
      '함께 걷던 문장',
      '앞으로도\n이렇게 나란히.',
      '우리의 문장이 길어지도록.',
      _FreeLayout.panorama,
      5,
      0,
    ),
    _FreeSpread(
      '너의 작은 표정',
      '가장 좋아하는\n너의 얼굴.',
      '사진 옆에 적어 둔 이유.',
      _FreeLayout.window,
      0,
      2,
    ),
    _FreeSpread(
      '우리에게 온 편지',
      '고마운 마음이\n차곡차곡.',
      '축하의 말들을 모아서.',
      _FreeLayout.postcard,
      6,
      1,
    ),
    _FreeSpread(
      '마음의 조각들',
      '사소한 순간도\n소중히 간직해.',
      '다시 꺼내 보고 싶은 것들.',
      _FreeLayout.mosaic,
      4,
      0,
    ),
    _FreeSpread(
      '오늘을 기억하는 법',
      '사진 한 장\n문장 한 줄.',
      '책을 펴면 다시 만날 하루.',
      _FreeLayout.gallery,
      1,
      7,
    ),
    _FreeSpread(
      '밤에 쓰는 편지',
      '하루의 끝에서\n다시 고마워.',
      '불을 끄기 전에 남긴 말.',
      _FreeLayout.timeline,
      7,
      3,
    ),
    _FreeSpread(
      '추신',
      '내일도\n많이 사랑할게.',
      '마지막 줄에 적어 둔 약속.',
      _FreeLayout.closing,
      0,
      4,
    ),
  ],
  FreeCollectionVolume.seaside: [
    _FreeSpread(
      '물빛의 시작',
      '이번 여행은\n바다 쪽으로.',
      '창밖에 물빛이 보이던 순간.',
      _FreeLayout.panorama,
      0,
      4,
    ),
    _FreeSpread(
      '도착한 항구',
      '낯선 바람과\n첫 인사를.',
      '짐을 내려놓고 바로 걸었다.',
      _FreeLayout.opening,
      0,
      1,
    ),
    _FreeSpread(
      '파도를 세는 오후',
      '아무것도\n서두르지 말자.',
      '같은 자리에서 오래 바라보기.',
      _FreeLayout.window,
      2,
      0,
    ),
    _FreeSpread(
      '해안의 작은 색',
      '파랑 옆에는\n또 다른 파랑.',
      '바다 곁에서 주운 색.',
      _FreeLayout.mosaic,
      0,
      2,
    ),
    _FreeSpread(
      '소금기 머금은 골목',
      '길 끝마다\n바다가 있었다.',
      '모퉁이를 돌며 만난 풍경.',
      _FreeLayout.paired,
      1,
      0,
    ),
    _FreeSpread(
      '느린 점심',
      '배가 고프면\n잠깐 쉬어 가기.',
      '그 동네의 맛을 골랐다.',
      _FreeLayout.stillLife,
      5,
      3,
    ),
    _FreeSpread(
      '햇살의 기록',
      '반짝이는 것은\n오래 보고 싶어.',
      '한낮부터 저녁까지.',
      _FreeLayout.timeline,
      2,
      4,
    ),
    _FreeSpread(
      '바닷가의 엽서',
      '여기 바다가\n참 좋다고.',
      '보고 싶은 사람에게 보낸 안부.',
      _FreeLayout.postcard,
      0,
      3,
    ),
    _FreeSpread(
      '남겨 둔 자리',
      '다시 올 이유를\n하나 남겨 둬.',
      '마음에 들었던 작은 카페.',
      _FreeLayout.gallery,
      3,
      1,
    ),
    _FreeSpread(
      '주머니 속 바다',
      '사진 몇 장에\n담긴 물소리.',
      '가지고 돌아온 작은 기념.',
      _FreeLayout.keepsake,
      5,
      2,
    ),
    _FreeSpread(
      '돌아오는 길',
      '멀어질수록\n더 선명해졌다.',
      '차창에서 마지막으로 본 빛.',
      _FreeLayout.contact,
      4,
      0,
    ),
    _FreeSpread(
      '다시 만날 물빛',
      '언젠가 또\n바다를 건너.',
      '돌아온 뒤에도 남아 있는 여행.',
      _FreeLayout.closing,
      2,
      0,
    ),
  ],
  FreeCollectionVolume.city: [
    _FreeSpread(
      '도시 수집 시작',
      '좋아하는 장면을\n분류해 봅니다.',
      '이번 도시에서 발견한 것.',
      _FreeLayout.ledger,
      1,
      0,
    ),
    _FreeSpread(
      '거리의 첫인상',
      '처음 걷는 길은\n조금 더 천천히.',
      '발걸음이 멈춘 첫 번째 장소.',
      _FreeLayout.opening,
      1,
      4,
    ),
    _FreeSpread(
      '창문과 벽',
      '도시의 표정을\n가까이서.',
      '이름보다 먼저 기억한 모양.',
      _FreeLayout.contact,
      1,
      0,
    ),
    _FreeSpread(
      '도시의 시간표',
      '걷고 먹고\n다시 걷는다.',
      '계획과 우연 사이의 하루.',
      _FreeLayout.timeline,
      4,
      5,
    ),
    _FreeSpread(
      '오래 앉은 카페',
      '마음에 든 자리\n따뜻한 한 잔.',
      '의자 하나까지 기억하고 싶다.',
      _FreeLayout.stillLife,
      3,
      5,
    ),
    _FreeSpread(
      '눈길의 방향',
      '멀리 한 번\n가까이 한 번.',
      '거리에서 고른 두 장면.',
      _FreeLayout.paired,
      0,
      1,
    ),
    _FreeSpread(
      '시장의 진열장',
      '가장 생생한\n동네의 색.',
      '계절을 파는 사람들.',
      _FreeLayout.mosaic,
      5,
      3,
    ),
    _FreeSpread(
      '뜻밖의 여백',
      '분주한 도시에도\n조용한 틈이.',
      '잠깐 숨을 고른 곳.',
      _FreeLayout.window,
      2,
      1,
    ),
    _FreeSpread(
      '수집한 이름들',
      '기억하고 싶은\n장소의 목록.',
      '다음 방문을 위한 메모.',
      _FreeLayout.keepsake,
      3,
      4,
    ),
    _FreeSpread(
      '도시를 펼치면',
      '길과 사람과\n빛이 이어진다.',
      '조금 떨어져서 바라본 풍경.',
      _FreeLayout.panorama,
      0,
      2,
    ),
    _FreeSpread(
      '한 도시의 인상',
      '사진에 없는\n이야기도 남겨.',
      '걸으면서 생각했던 문장.',
      _FreeLayout.letter,
      1,
      5,
    ),
    _FreeSpread(
      '수집의 다음 장',
      '다음 도시에서도\n우리의 취향으로.',
      '한 권의 기록을 마치며.',
      _FreeLayout.closing,
      4,
      0,
    ),
  ],
  FreeCollectionVolume.walking: [
    _FreeSpread(
      '가벼운 출발',
      '오늘은\n조금 느리게.',
      '시간보다 방향을 고른 날.',
      _FreeLayout.opening,
      4,
      2,
    ),
    _FreeSpread(
      '걷는 마음',
      '목적지보다\n가는 길이 좋아.',
      '발걸음에 맞춰 숨을 고르기.',
      _FreeLayout.letter,
      2,
      1,
    ),
    _FreeSpread(
      '첫 번째 쉼',
      '좋은 풍경 앞에\n잠깐 앉았다.',
      '쉬어 갈 이유는 충분했다.',
      _FreeLayout.window,
      2,
      0,
    ),
    _FreeSpread(
      '길 위의 초록',
      '눈에 담아 온\n작은 계절.',
      '모퉁이에서 만난 빛과 잎.',
      _FreeLayout.stillLife,
      5,
      1,
    ),
    _FreeSpread(
      '나란한 풍경',
      '멀리도 보고\n곁도 보고.',
      '다른 거리에서 바라본 같은 날.',
      _FreeLayout.paired,
      0,
      2,
    ),
    _FreeSpread(
      '바람의 길',
      '사진 밖으로\n이어지는 풍경.',
      '한참을 걷고서 만난 바다.',
      _FreeLayout.panorama,
      2,
      0,
    ),
    _FreeSpread(
      '느린 하루의 순서',
      '늦어도 괜찮은\n우리의 일정.',
      '천천히 보낸 시간의 목록.',
      _FreeLayout.timeline,
      4,
      3,
    ),
    _FreeSpread(
      '길에서 만난 식탁',
      '따뜻한 한 끼가\n여행을 채운다.',
      '걷다가 들어간 작은 가게.',
      _FreeLayout.gallery,
      3,
      5,
    ),
    _FreeSpread(
      '챙겨 온 조각',
      '손에는 가볍게\n마음에는 오래.',
      '잊기 전에 모아 둔 기록.',
      _FreeLayout.keepsake,
      5,
      1,
    ),
    _FreeSpread(
      '다시 걷고 싶은 길',
      '다음에도\n이 길로 가자.',
      '돌아보며 고른 장면들.',
      _FreeLayout.mosaic,
      1,
      4,
    ),
    _FreeSpread(
      '집으로 보내는 안부',
      '잘 걷고\n잘 쉬고 있어.',
      '낯선 자리에서 쓴 짧은 편지.',
      _FreeLayout.postcard,
      0,
      3,
    ),
    _FreeSpread(
      '느리게 오래',
      '여행이 끝나도\n이 속도를 기억해.',
      '내일도 조금 천천히.',
      _FreeLayout.closing,
      2,
      4,
    ),
  ],
  FreeCollectionVolume.postcards: [
    _FreeSpread(
      '첫 번째 안부',
      '잘 도착했어요.\n여기는 참 좋아요.',
      '첫 풍경을 엽서로 보냅니다.',
      _FreeLayout.postcard,
      0,
      1,
    ),
    _FreeSpread(
      '여행의 주소',
      '낯선 곳에도\n우리의 자리가.',
      '며칠 동안 머물렀던 동네.',
      _FreeLayout.ledger,
      1,
      3,
    ),
    _FreeSpread(
      '창가에서 쓴 문장',
      '가는 길에\n너를 생각했어.',
      '차창에서 만난 물빛.',
      _FreeLayout.opening,
      4,
      2,
    ),
    _FreeSpread(
      '오늘의 소식',
      '아침부터 저녁까지\n좋은 일이 있었어.',
      '하루를 짧게 접어 보내기.',
      _FreeLayout.timeline,
      5,
      3,
    ),
    _FreeSpread(
      '우표 대신 풍경',
      '이 장면을\n보여 주고 싶어.',
      '사진 네 장으로 전하는 안부.',
      _FreeLayout.contact,
      1,
      0,
    ),
    _FreeSpread(
      '동네의 맛',
      '다음에는\n같이 먹으러 오자.',
      '그 사람을 떠올리며 고른 메뉴.',
      _FreeLayout.stillLife,
      3,
      5,
    ),
    _FreeSpread(
      '나란히 놓은 엽서',
      '낮의 풍경과\n저녁의 마음.',
      '서로 다른 두 장면의 편지.',
      _FreeLayout.paired,
      0,
      2,
    ),
    _FreeSpread(
      '바람을 담아',
      '사진에서\n바람이 났으면.',
      '한 장으로는 모자란 풍경.',
      _FreeLayout.panorama,
      2,
      0,
    ),
    _FreeSpread(
      '봉투에 넣은 기억',
      '작은 것들도\n같이 보낼게.',
      '티켓과 메모를 모아 두기.',
      _FreeLayout.keepsake,
      4,
      5,
    ),
    _FreeSpread(
      '보내지 않은 편지',
      '돌아가서\n천천히 들려줄게.',
      '길게 적고 싶었던 이야기.',
      _FreeLayout.letter,
      1,
      3,
    ),
    _FreeSpread(
      '모아 놓은 안부',
      '여행의 문장을\n다시 펼쳐 보니.',
      '장면마다 떠오르는 목소리.',
      _FreeLayout.mosaic,
      0,
      5,
    ),
    _FreeSpread(
      '마지막 인사',
      '곧 만나요.\n이야기가 많아요.',
      '다음 편지는 어디에서 쓸까.',
      _FreeLayout.closing,
      4,
      2,
    ),
  ],
  FreeCollectionVolume.table: [
    _FreeSpread(
      '계절을 차리다',
      '오늘의 기분을\n한 접시에.',
      '식탁에서 시작하는 작은 기록.',
      _FreeLayout.stillLife,
      0,
      4,
    ),
    _FreeSpread(
      '아침의 그릇',
      '천천히 차린\n하루의 첫 끼.',
      '익숙한 그릇에 담긴 새 아침.',
      _FreeLayout.opening,
      0,
      2,
    ),
    _FreeSpread(
      '장보기 메모',
      '눈에 들어온\n계절의 색.',
      '맛있어 보여서 골랐던 것.',
      _FreeLayout.ledger,
      4,
      0,
    ),
    _FreeSpread(
      '두 사람의 식탁',
      '혼자보다\n함께 먹는 맛.',
      '좋아하는 사람과 나눈 점심.',
      _FreeLayout.paired,
      1,
      5,
    ),
    _FreeSpread(
      '과일이 익는 시간',
      '향기까지\n남겨 두고 싶어.',
      '색이 고와서 한 번 더 바라보기.',
      _FreeLayout.window,
      4,
      0,
    ),
    _FreeSpread(
      '우리의 소풍',
      '식탁을\n밖으로 옮긴 날.',
      '돗자리 위에 모인 마음.',
      _FreeLayout.panorama,
      1,
      5,
    ),
    _FreeSpread(
      '한 주의 맛',
      '잘 먹고\n잘 지냈습니다.',
      '좋았던 한 끼를 고르는 일.',
      _FreeLayout.contact,
      0,
      4,
    ),
    _FreeSpread(
      '오후의 한 조각',
      '달콤한 것과\n짧은 이야기.',
      '바쁜 날의 작은 쉼표.',
      _FreeLayout.keepsake,
      4,
      2,
    ),
    _FreeSpread(
      '다시 만들고 싶은 맛',
      '정확한 양보다\n기억하는 마음.',
      '다음 식탁을 위한 짧은 메모.',
      _FreeLayout.letter,
      0,
      1,
    ),
    _FreeSpread(
      '식탁의 얼굴들',
      '좋은 음식 곁에\n좋은 사람들.',
      '한참 웃다가 식어 버린 차.',
      _FreeLayout.gallery,
      5,
      1,
    ),
    _FreeSpread(
      '하루의 마지막 접시',
      '함께 치우며\n오늘을 마무리.',
      '식탁이 비워진 뒤에도.',
      _FreeLayout.timeline,
      0,
      3,
    ),
    _FreeSpread(
      '다음 계절의 메뉴',
      '다음에도\n같이 먹어요.',
      '계절이 바뀌면 또 차릴 식탁.',
      _FreeLayout.closing,
      4,
      0,
    ),
  ],
  FreeCollectionVolume.objects: [
    _FreeSpread(
      '취향의 첫 칸',
      '좋아하는 것을\n모아 봅니다.',
      '이유가 있어서 곁에 둔 것.',
      _FreeLayout.ledger,
      3,
      2,
    ),
    _FreeSpread(
      '책상 위의 하루',
      '손이 닿는 곳에\n내가 좋아하는 것.',
      '매일 쓰는 작은 도구들.',
      _FreeLayout.stillLife,
      3,
      2,
    ),
    _FreeSpread(
      '읽다 멈춘 페이지',
      '밑줄 하나에\n머문 마음.',
      '다시 읽고 싶었던 문장.',
      _FreeLayout.letter,
      2,
      3,
    ),
    _FreeSpread(
      '자주 고르는 색',
      '취향에는\n작은 공통점이.',
      '나란히 두고 보니 알게 된 것.',
      _FreeLayout.contact,
      4,
      0,
    ),
    _FreeSpread(
      '좋아하는 자리',
      '앉아 있으면\n편안해지는 곳.',
      '내가 돌아오는 작은 풍경.',
      _FreeLayout.window,
      3,
      2,
    ),
    _FreeSpread(
      '한 쌍의 물건',
      '함께 놓으면\n더 좋은 조합.',
      '서로 다른 모양의 좋은 균형.',
      _FreeLayout.paired,
      2,
      3,
    ),
    _FreeSpread(
      '취향을 만나는 길',
      '밖에서도\n눈길이 머문다.',
      '산책하며 발견한 장면.',
      _FreeLayout.panorama,
      6,
      1,
    ),
    _FreeSpread(
      '오래 쓰는 이유',
      '새것보다\n익숙한 것이 좋아.',
      '시간이 남긴 작은 흔적.',
      _FreeLayout.opening,
      3,
      2,
    ),
    _FreeSpread(
      '모아 놓은 조각',
      '종이 한 장에도\n이야기가 있으니.',
      '버리지 못한 작은 기록.',
      _FreeLayout.keepsake,
      2,
      4,
    ),
    _FreeSpread(
      '취향의 변화',
      '조금씩 달라져도\n여전히 나답게.',
      '계절마다 달라지는 선택.',
      _FreeLayout.timeline,
      0,
      6,
    ),
    _FreeSpread(
      '누군가에게 추천',
      '네가 좋아할 것\n같아서 남겨 둬.',
      '함께 나누고 싶은 취향.',
      _FreeLayout.postcard,
      2,
      3,
    ),
    _FreeSpread(
      '아직 비어 있는 칸',
      '새로운 좋아함을\n위한 자리.',
      '다음 수집을 기다리며.',
      _FreeLayout.closing,
      3,
      2,
    ),
  ],
  FreeCollectionVolume.together: [
    _FreeSpread(
      '우리의 모임',
      '같이 있으면\n좋은 날이 된다.',
      '한자리에 모인 반가운 얼굴.',
      _FreeLayout.panorama,
      5,
      1,
    ),
    _FreeSpread(
      '약속 잡던 날',
      '달력 한 칸에\n설렘을 적었다.',
      '만나기 전부터 시작된 이야기.',
      _FreeLayout.opening,
      1,
      0,
    ),
    _FreeSpread(
      '오랜만의 인사',
      '어제 만난 듯\n바로 웃었다.',
      '달라진 것과 여전한 것.',
      _FreeLayout.paired,
      5,
      1,
    ),
    _FreeSpread(
      '같이 차린 식탁',
      '하나씩 가져와\n모두의 식탁으로.',
      '좋아하는 음식을 나누는 일.',
      _FreeLayout.stillLife,
      0,
      4,
    ),
    _FreeSpread(
      '웃음의 순간들',
      '같은 말에도\n함께 웃는 사이.',
      '사진마다 들리는 웃음소리.',
      _FreeLayout.mosaic,
      5,
      1,
    ),
    _FreeSpread(
      '걷고 이야기하고',
      '길은 짧았고\n이야기는 길었다.',
      '나란히 걷던 익숙한 속도.',
      _FreeLayout.gallery,
      6,
      5,
    ),
    _FreeSpread(
      '우리의 하루',
      '특별한 계획 없이\n충분히 좋은 날.',
      '그날의 순서를 적어 보기.',
      _FreeLayout.timeline,
      1,
      0,
    ),
    _FreeSpread(
      '작은 선물',
      '너를 생각하며\n고른 작은 것.',
      '주는 마음과 받는 표정.',
      _FreeLayout.keepsake,
      4,
      2,
    ),
    _FreeSpread(
      '고마운 이름들',
      '있어 주어서\n참 고마워.',
      '함께한 사람에게 남기는 말.',
      _FreeLayout.letter,
      5,
      6,
    ),
    _FreeSpread(
      '각자의 좋은 순간',
      '같은 하루에도\n다른 기억이.',
      '한 사람씩 골라 본 장면.',
      _FreeLayout.contact,
      0,
      1,
    ),
    _FreeSpread(
      '집에 가는 길',
      '헤어진 뒤에도\n웃음이 남았다.',
      '돌아가며 보낸 짧은 안부.',
      _FreeLayout.postcard,
      6,
      3,
    ),
    _FreeSpread(
      '다음에도 우리',
      '곧 또 만나.\n같이 좋은 날을.',
      '다음 약속을 남겨 둡니다.',
      _FreeLayout.closing,
      5,
      1,
    ),
  ],
  FreeCollectionVolume.weekend: [
    _FreeSpread(
      '조금 늦은 시작',
      '알람 없이\n눈을 뜬 아침.',
      '아무것도 서두르지 않는 날.',
      _FreeLayout.window,
      0,
      2,
    ),
    _FreeSpread(
      '오늘의 계획',
      '하고 싶은 일\n한두 가지쯤.',
      '빈칸이 있어도 괜찮은 목록.',
      _FreeLayout.ledger,
      3,
      0,
    ),
    _FreeSpread(
      '마음에 드는 아침',
      '천천히 차리고\n오래 앉았다.',
      '하루의 속도를 정하는 한 끼.',
      _FreeLayout.stillLife,
      0,
      4,
    ),
    _FreeSpread(
      '가벼운 산책',
      '가까운 길에서\n새로운 장면을.',
      '익숙한 동네를 다르게 걷기.',
      _FreeLayout.panorama,
      6,
      1,
    ),
    _FreeSpread(
      '햇살 드는 자리',
      '잠깐 앉아서\n책 몇 페이지.',
      '그늘과 햇살 사이의 온도.',
      _FreeLayout.opening,
      2,
      3,
    ),
    _FreeSpread(
      '작은 기분 전환',
      '꽃 한 송이로\n달라진 하루.',
      '나를 위해 골랐던 색.',
      _FreeLayout.keepsake,
      4,
      6,
    ),
    _FreeSpread(
      '오후의 두 장면',
      '나가도 좋고\n집에 있어도 좋아.',
      '우리에게 맞는 주말의 모양.',
      _FreeLayout.paired,
      1,
      3,
    ),
    _FreeSpread(
      '함께 보낸 시간',
      '별말 없이도\n편안한 사이.',
      '같은 공간에서 보낸 오후.',
      _FreeLayout.gallery,
      5,
      1,
    ),
    _FreeSpread(
      '한 주를 접으며',
      '수고했다고\n나에게 말해 줘.',
      '천천히 되짚어 본 이번 주.',
      _FreeLayout.letter,
      3,
      2,
    ),
    _FreeSpread(
      '좋았던 조각들',
      '일부러 남겨 둔\n작은 기억.',
      '다음 주에 꺼내 볼 장면들.',
      _FreeLayout.mosaic,
      0,
      6,
    ),
    _FreeSpread(
      '일요일의 안부',
      '이번 주말은\n이렇게 보냈어.',
      '친구에게 전하는 짧은 이야기.',
      _FreeLayout.postcard,
      1,
      4,
    ),
    _FreeSpread(
      '월요일 앞에서',
      '이만큼 쉬었으니\n다시 가볍게.',
      '다음 주말에 이어 쓸 이야기.',
      _FreeLayout.closing,
      6,
      0,
    ),
  ],
};
