part of 'authored_collections.dart';

// Each volume has twelve authored spreads, not a count-based repeated filler.
const _lifeSpreadStories = <FreeCollectionVolume, List<_FreeSpread>>{
  FreeCollectionVolume.firstYear: [
    _FreeSpread(
      "너를 만난 날",
      "작고 소중한\n우리의 시작.",
      "처음 손을 잡던 온도를 기억한다.",
      _FreeLayout.opening,
      2,
      5,
    ),
    _FreeSpread(
      "작은 손의 약속",
      "한 손 가득\n전해진 마음.",
      "손가락 하나를 꼭 쥐던 힘.",
      _FreeLayout.portraitEssay,
      5,
      2,
    ),
    _FreeSpread(
      "집으로 온 봄",
      "너의 자리가\n우리 집에 생겼다.",
      "매일의 풍경이 조금 달라졌다.",
      _FreeLayout.window,
      2,
      3,
    ),
    _FreeSpread(
      "웃음이 자란다",
      "마주 보면\n함께 웃게 돼.",
      "처음 눈을 맞추던 오후.",
      _FreeLayout.gallery,
      0,
      5,
    ),
    _FreeSpread(
      "뒤집고 앉고",
      "어제와 다른\n오늘의 너.",
      "작은 변화도 크게 반가웠다.",
      _FreeLayout.milestone,
      0,
      3,
    ),
    _FreeSpread(
      "좋아하는 놀이",
      "작은 손으로\n세상을 만져.",
      "매일 달라지는 관심사.",
      _FreeLayout.contact,
      0,
      3,
    ),
    _FreeSpread(
      "바깥의 첫 계절",
      "햇살도 바람도\n처음이니까.",
      "모든 것이 신기한 산책.",
      _FreeLayout.fieldNotes,
      1,
      0,
    ),
    _FreeSpread(
      "한 걸음의 용기",
      "넘어져도\n다시 일어서.",
      "곁에서 천천히 기다려 주기.",
      _FreeLayout.paired,
      1,
      5,
    ),
    _FreeSpread(
      "너만의 표정들",
      "사진마다\n다른 이야기.",
      "우리가 좋아하는 얼굴들.",
      _FreeLayout.mosaic,
      0,
      4,
    ),
    _FreeSpread(
      "첫 생일의 빛",
      "함께 자란\n우리의 첫해.",
      "작은 생일을 크게 축하하며.",
      _FreeLayout.ribbonPair,
      4,
      3,
    ),
    _FreeSpread(
      "남겨 둔 보물",
      "작아진 물건에\n커진 기억.",
      "처음 신던 양말을 접어 둔다.",
      _FreeLayout.keepsake,
      3,
      5,
    ),
    _FreeSpread(
      "내년의 너에게",
      "서두르지 말고\n너의 속도로.",
      "다음의 처음도 함께할게.",
      _FreeLayout.closing,
      0,
      1,
    ),
  ],
  FreeCollectionVolume.littleSteps: [
    _FreeSpread(
      "발견 노트",
      "오늘은 무엇을\n배웠을까.",
      "눈을 맞추며 하루를 시작한다.",
      _FreeLayout.fieldNotes,
      0,
      3,
    ),
    _FreeSpread(
      "손을 펴다",
      "잡고 놓으며\n알아가는 세상.",
      "작은 손이 기억하는 감촉.",
      _FreeLayout.portraitEssay,
      5,
      3,
    ),
    _FreeSpread(
      "고개를 들다",
      "궁금한 것이\n하나씩 늘어나.",
      "눈높이에 맞춰 바라보기.",
      _FreeLayout.window,
      2,
      0,
    ),
    _FreeSpread(
      "첫 웃음",
      "함께 웃으면\n더 크게 웃어.",
      "소리가 된 즐거움을 적어 둔다.",
      _FreeLayout.gallery,
      0,
      5,
    ),
    _FreeSpread(
      "혼자 앉는 오후",
      "조금 더 넓어진\n너의 세상.",
      "익숙한 장난감도 새롭게 보인다.",
      _FreeLayout.milestone,
      0,
      3,
    ),
    _FreeSpread(
      "놀이의 순서",
      "쥐었다 놓았다\n다시 해 보고.",
      "반복할수록 즐거운 발견.",
      _FreeLayout.contact,
      3,
      0,
    ),
    _FreeSpread(
      "밖으로 한 걸음",
      "새로운 길에도\n우리 함께.",
      "바깥 공기를 처음 만난 날.",
      _FreeLayout.panorama,
      1,
      0,
    ),
    _FreeSpread(
      "잡아 주는 손",
      "혼자가 아닌\n작은 도전.",
      "놓지 않아도 괜찮아.",
      _FreeLayout.ribbonPair,
      1,
      5,
    ),
    _FreeSpread(
      "넘어져도 괜찮아",
      "서툴러도\n충분히 멋져.",
      "다시 시도한 순간에 박수를.",
      _FreeLayout.ledger,
      1,
      0,
    ),
    _FreeSpread(
      "조금 더 멀리",
      "어제보다\n한 걸음 더.",
      "네가 정한 속도를 응원한다.",
      _FreeLayout.paired,
      1,
      4,
    ),
    _FreeSpread(
      "자라난 흔적",
      "나란히 놓으면\n보이는 변화.",
      "오늘의 키와 마음을 기록한다.",
      _FreeLayout.pinboard,
      3,
      4,
    ),
    _FreeSpread(
      "계속되는 발견",
      "다음에는\n어디로 갈까.",
      "성장의 다음 줄은 비워 둘게.",
      _FreeLayout.closing,
      0,
      5,
    ),
  ],
  FreeCollectionVolume.babyBloom: [
    _FreeSpread(
      "봄의 이름",
      "너를 부르면\n봄이 온다.",
      "우리에게 찾아온 작은 계절.",
      _FreeLayout.window,
      2,
      5,
    ),
    _FreeSpread(
      "포근한 첫날",
      "햇빛보다\n부드러운 숨.",
      "조용히 바라보던 얼굴.",
      _FreeLayout.portraitEssay,
      2,
      5,
    ),
    _FreeSpread(
      "손끝에 핀 마음",
      "손끝에서\n시작된 사랑.",
      "작은 손 안에 담긴 큰 마음.",
      _FreeLayout.ribbonPair,
      5,
      3,
    ),
    _FreeSpread(
      "꿈꾸는 오후",
      "잠든 시간도\n기억이 된다.",
      "깨우지 않고 간직한 한 장.",
      _FreeLayout.gallery,
      2,
      0,
    ),
    _FreeSpread(
      "웃음이 피는 곳",
      "너의 웃음이\n집을 채운다.",
      "눈을 마주칠 때마다 찾아오는 봄.",
      _FreeLayout.opening,
      0,
      3,
    ),
    _FreeSpread(
      "빛을 따라",
      "햇살 닿는 곳에\n우리도 잠시.",
      "산책에서 발견한 초록.",
      _FreeLayout.panorama,
      1,
      0,
    ),
    _FreeSpread(
      "처음 입은 계절",
      "작은 옷에도\n날들이 쌓여.",
      "차곡차곡 접어 둔 기억.",
      _FreeLayout.stillLife,
      3,
      5,
    ),
    _FreeSpread(
      "자라는 꽃잎",
      "하루하루\n다르게 피어나.",
      "작은 변화들을 모은 기록.",
      _FreeLayout.milestone,
      0,
      1,
    ),
    _FreeSpread(
      "곁에 있는 손",
      "너를 지키며\n우리도 자라.",
      "손을 잡고 배우는 하루.",
      _FreeLayout.paired,
      1,
      5,
    ),
    _FreeSpread(
      "첫 번째 축하",
      "네가 온 날을\n함께 기억해.",
      "일 년의 고마움을 담아.",
      _FreeLayout.keepsake,
      4,
      3,
    ),
    _FreeSpread(
      "너에게 쓴 봄",
      "언젠가 읽어 줄\n다정한 말.",
      "너의 처음을 함께해서 기뻐.",
      _FreeLayout.letter,
      0,
      5,
    ),
    _FreeSpread(
      "다음 계절에도",
      "어떤 계절에도\n너의 곁에서.",
      "계속 피어날 날들을 기다린다.",
      _FreeLayout.closing,
      2,
      0,
    ),
  ],
  FreeCollectionVolume.playroom: [
    _FreeSpread(
      "오늘의 놀이방",
      "작은 손의\n커다란 하루.",
      "좋아하는 것부터 꺼내 볼까.",
      _FreeLayout.pinboard,
      0,
      3,
    ),
    _FreeSpread(
      "첫 번째 발견",
      "이건 어떤\n소리가 날까.",
      "만지고 들어 보던 아침.",
      _FreeLayout.milestone,
      3,
      0,
    ),
    _FreeSpread(
      "웃음 수집",
      "하나 둘 셋\n웃음이 가득.",
      "가장 신났던 표정들을 모은다.",
      _FreeLayout.contact,
      0,
      4,
    ),
    _FreeSpread(
      "색을 만나는 날",
      "새로운 색에\n눈이 반짝.",
      "오늘 눈길이 머문 물건들.",
      _FreeLayout.stillLife,
      3,
      0,
    ),
    _FreeSpread(
      "꼬물꼬물 손",
      "잡아 보고\n다시 놓아 보고.",
      "생각보다 바쁜 작은 손.",
      _FreeLayout.ribbonPair,
      5,
      3,
    ),
    _FreeSpread(
      "쉬는 시간",
      "신나게 놀고\n잠깐 충전.",
      "낮잠도 하루의 중요한 장면.",
      _FreeLayout.window,
      2,
      0,
    ),
    _FreeSpread(
      "바깥 놀이터",
      "문밖에도\n놀이가 가득.",
      "바람이 들려준 새로운 소리.",
      _FreeLayout.fieldNotes,
      1,
      0,
    ),
    _FreeSpread(
      "도전하는 발",
      "한 걸음씩\n새로운 곳으로.",
      "용기 낸 발끝을 응원해.",
      _FreeLayout.paired,
      1,
      3,
    ),
    _FreeSpread(
      "오늘의 하이라이트",
      "마음에 드는\n순간을 골라.",
      "여러 장 중에 고르기 어려운 하루.",
      _FreeLayout.mosaic,
      0,
      4,
    ),
    _FreeSpread(
      "우리의 놀이 목록",
      "내일은 무얼\n해 보면 좋을까.",
      "좋아하는 놀이를 적어 둔다.",
      _FreeLayout.ledger,
      3,
      1,
    ),
    _FreeSpread(
      "축하하는 놀이",
      "한 해가 모여\n즐거운 파티.",
      "손뼉 치며 맞이한 첫 생일.",
      _FreeLayout.gallery,
      4,
      0,
    ),
    _FreeSpread(
      "내일 또 놀자",
      "오늘보다\n궁금한 내일.",
      "다음 놀이도 함께하자.",
      _FreeLayout.closing,
      0,
      3,
    ),
  ],
  FreeCollectionVolume.birthday: [
    _FreeSpread(
      "처음의 축하",
      "너의 첫 생일을\n축하해.",
      "우리가 함께 자란 일 년.",
      _FreeLayout.ribbonPair,
      4,
      0,
    ),
    _FreeSpread(
      "초대하는 마음",
      "소중한 사람을\n한자리에.",
      "오늘을 기다리던 마음.",
      _FreeLayout.postcard,
      3,
      4,
    ),
    _FreeSpread(
      "일 년 전 오늘",
      "처음 만났던\n너의 작은 얼굴.",
      "지금도 선명한 첫 순간.",
      _FreeLayout.portraitEssay,
      2,
      5,
    ),
    _FreeSpread(
      "작은 변화들",
      "얼마나 많이\n자랐는지.",
      "한 장씩 모아 보는 일 년.",
      _FreeLayout.milestone,
      0,
      1,
    ),
    _FreeSpread(
      "파티를 준비해",
      "네가 좋아할\n색을 골라.",
      "작은 장식에도 마음을 담았다.",
      _FreeLayout.stillLife,
      3,
      4,
    ),
    _FreeSpread(
      "주인공의 표정",
      "오늘은 네가\n가장 빛나.",
      "카메라보다 너를 바라보던 날.",
      _FreeLayout.gallery,
      4,
      0,
    ),
    _FreeSpread(
      "함께 웃는 시간",
      "한 사람씩\n마음을 모아.",
      "축하를 전해 준 다정한 얼굴.",
      _FreeLayout.mosaic,
      4,
      1,
    ),
    _FreeSpread(
      "손뼉 치는 마음",
      "이렇게 자라서\n참 고마워.",
      "서로에게 건넨 작은 박수.",
      _FreeLayout.opening,
      0,
      5,
    ),
    _FreeSpread(
      "첫해의 선물",
      "물건보다\n오래 남을 마음.",
      "선물과 이야기를 함께 남긴다.",
      _FreeLayout.keepsake,
      3,
      5,
    ),
    _FreeSpread(
      "기억하고 싶은 말",
      "앞으로도\n너의 편이야.",
      "너에게 보내는 생일 편지.",
      _FreeLayout.letter,
      4,
      0,
    ),
    _FreeSpread(
      "파티가 끝나고",
      "조용해진 집에\n남은 온기.",
      "하루를 천천히 되짚어 본다.",
      _FreeLayout.paired,
      2,
      3,
    ),
    _FreeSpread(
      "다음 생일까지",
      "다음의 일 년도\n함께 웃자.",
      "너의 다음 처음을 기다리며.",
      _FreeLayout.closing,
      0,
      4,
    ),
  ],
  FreeCollectionVolume.homeYear: [
    _FreeSpread(
      "올해의 우리",
      "같은 집에서\n다른 하루를.",
      "한 해의 가족 사진을 펼친다.",
      _FreeLayout.opening,
      0,
      1,
    ),
    _FreeSpread(
      "봄의 식탁",
      "함께 앉으면\n이야기가 시작돼.",
      "계절이 바뀌는 식탁의 풍경.",
      _FreeLayout.gallery,
      3,
      1,
    ),
    _FreeSpread(
      "주말의 부엌",
      "손을 보태고\n웃음을 나누고.",
      "서로의 취향을 배우는 시간.",
      _FreeLayout.paired,
      1,
      3,
    ),
    _FreeSpread(
      "우리 집의 말",
      "자주 하는 말에\n마음이 담겨.",
      "가족만 아는 말을 적는다.",
      _FreeLayout.fieldNotes,
      0,
      1,
    ),
    _FreeSpread(
      "초록의 소풍",
      "같이 나가면\n더 좋은 날.",
      "가까운 공원도 충분한 여행.",
      _FreeLayout.panorama,
      0,
      4,
    ),
    _FreeSpread(
      "닮은 표정",
      "다른 듯 닮은\n우리의 얼굴.",
      "세대를 건너 전해지는 미소.",
      _FreeLayout.portraitEssay,
      0,
      1,
    ),
    _FreeSpread(
      "평범한 기념일",
      "작은 날도\n기억하기로.",
      "축하할 일을 놓치지 않는 마음.",
      _FreeLayout.milestone,
      1,
      3,
    ),
    _FreeSpread(
      "함께한 사람들",
      "문을 열고\n반가운 얼굴을.",
      "가족 곁의 소중한 사람들.",
      _FreeLayout.contact,
      2,
      0,
    ),
    _FreeSpread(
      "가을의 기록",
      "쌓인 사진만큼\n깊어진 계절.",
      "오래 기억할 한 장을 고른다.",
      _FreeLayout.pinboard,
      0,
      3,
    ),
    _FreeSpread(
      "집에 머무는 날",
      "밖보다 좋은\n우리의 자리.",
      "같이 있는 조용한 오후.",
      _FreeLayout.window,
      1,
      3,
    ),
    _FreeSpread(
      "한 해의 고마움",
      "당연하지 않은\n매일의 다정함.",
      "올해 서로에게 고마웠던 일.",
      _FreeLayout.letter,
      0,
      1,
    ),
    _FreeSpread(
      "다음 해의 사진",
      "내년에도\n이 자리에서.",
      "우리의 연감은 계속된다.",
      _FreeLayout.closing,
      0,
      3,
    ),
  ],
  FreeCollectionVolume.familyTable: [
    _FreeSpread(
      "한 식탁에 모여",
      "오늘도\n같이 먹자.",
      "식탁으로 모여드는 발걸음.",
      _FreeLayout.gallery,
      3,
      1,
    ),
    _FreeSpread(
      "장을 보던 날",
      "너를 생각하며\n골라 온 것들.",
      "좋아하는 맛을 기억한다.",
      _FreeLayout.stillLife,
      3,
      4,
    ),
    _FreeSpread(
      "손을 보태다",
      "조금 서툴러도\n함께 만들면 돼.",
      "작은 손도 반가운 부엌.",
      _FreeLayout.paired,
      1,
      3,
    ),
    _FreeSpread(
      "우리 집의 맛",
      "말하지 않아도\n아는 그 맛.",
      "가족의 단골 메뉴를 적어 둔다.",
      _FreeLayout.fieldNotes,
      3,
      1,
    ),
    _FreeSpread(
      "기다리는 시간",
      "끓는 소리와\n함께 나누는 말.",
      "식사 전에도 이야기는 이어진다.",
      _FreeLayout.window,
      1,
      3,
    ),
    _FreeSpread(
      "첫 숟가락",
      "마주 보고\n맛있게 한 입.",
      "표정으로 전해지는 대답.",
      _FreeLayout.ribbonPair,
      1,
      3,
    ),
    _FreeSpread(
      "세대의 레시피",
      "손끝에서\n전해지는 기억.",
      "함께 배우고 남기는 맛.",
      _FreeLayout.portraitEssay,
      0,
      3,
    ),
    _FreeSpread(
      "바깥의 식탁",
      "도시락을 열면\n소풍이 시작돼.",
      "초록 아래서 나눈 한 끼.",
      _FreeLayout.panorama,
      0,
      4,
    ),
    _FreeSpread(
      "손님이 온 저녁",
      "자리 하나 더\n마음도 조금 더.",
      "친구도 가족이 되는 식탁.",
      _FreeLayout.mosaic,
      2,
      3,
    ),
    _FreeSpread(
      "오늘의 대화",
      "밥을 먹으며\n나눈 이야기.",
      "잊기 아까운 말들을 적는다.",
      _FreeLayout.ledger,
      1,
      0,
    ),
    _FreeSpread(
      "다 먹고 난 뒤",
      "빈 접시에도\n온기는 남아.",
      "다음에 또 먹자는 약속.",
      _FreeLayout.keepsake,
      3,
      1,
    ),
    _FreeSpread(
      "다음 식탁에서",
      "새로운 계절도\n함께 맛보자.",
      "우리 집의 다음 메뉴를 기다리며.",
      _FreeLayout.closing,
      0,
      3,
    ),
  ],
  FreeCollectionVolume.friendsUs: [
    _FreeSpread(
      "우리라는 이름",
      "만나면 금방\n예전의 우리.",
      "오랜 사이에도 새로운 장면.",
      _FreeLayout.pinboard,
      2,
      5,
    ),
    _FreeSpread(
      "약속 잡던 날",
      "시간을 맞춰\n마음을 모아.",
      "바쁜 날들 사이에 만든 자리.",
      _FreeLayout.postcard,
      4,
      2,
    ),
    _FreeSpread(
      "오랜만의 얼굴",
      "보자마자\n웃음이 났다.",
      "서로의 안부를 묻던 첫 장면.",
      _FreeLayout.gallery,
      2,
      5,
    ),
    _FreeSpread(
      "우리의 단골",
      "같은 자리에\n쌓인 이야기.",
      "다시 찾아가고 싶은 곳.",
      _FreeLayout.fieldNotes,
      4,
      2,
    ),
    _FreeSpread(
      "서로 다른 취향",
      "달라도 좋아\n그래서 더 좋아.",
      "각자의 좋아하는 것들을 모은다.",
      _FreeLayout.contact,
      2,
      3,
    ),
    _FreeSpread(
      "별것 아닌 농담",
      "사진 밖에서\n더 크게 웃었다.",
      "설명하지 않아도 통하는 마음.",
      _FreeLayout.mosaic,
      5,
      2,
    ),
    _FreeSpread(
      "같이 걷는 오후",
      "목적지보다\n같이 걷는 길.",
      "이야기가 길어지던 산책.",
      _FreeLayout.panorama,
      2,
      4,
    ),
    _FreeSpread(
      "마음을 듣는 시간",
      "잘 듣고\n오래 기억할게.",
      "서로에게 힘이 된 한마디.",
      _FreeLayout.ribbonPair,
      2,
      5,
    ),
    _FreeSpread(
      "함께한 날짜",
      "달력에 남은\n우리의 약속.",
      "사진으로 돌아보는 모임들.",
      _FreeLayout.milestone,
      2,
      4,
    ),
    _FreeSpread(
      "작은 기념품",
      "같이 골라서\n더 소중한 것.",
      "하루의 조각을 책 사이에.",
      _FreeLayout.keepsake,
      4,
      3,
    ),
    _FreeSpread(
      "너에게 보낼 말",
      "다음에도\n네 편이 될게.",
      "사진 옆에 남기는 짧은 편지.",
      _FreeLayout.letter,
      5,
      2,
    ),
    _FreeSpread(
      "다음에 또 만나",
      "멀리 있어도\n가까운 마음.",
      "다음 약속을 남겨 둔다.",
      _FreeLayout.closing,
      2,
      5,
    ),
  ],
  FreeCollectionVolume.generations: [
    _FreeSpread(
      "닮은 마음들",
      "사진 속에서\n우리가 이어져.",
      "서로 닮은 얼굴을 찾아본다.",
      _FreeLayout.portraitEssay,
      0,
      1,
    ),
    _FreeSpread(
      "가장 오래된 이야기",
      "처음 듣는 말도\n우리의 역사.",
      "어른들에게 묻고 싶은 안부.",
      _FreeLayout.fieldNotes,
      0,
      3,
    ),
    _FreeSpread(
      "손에서 손으로",
      "살뜰한 마음을\n배우는 시간.",
      "함께 만들며 전해지는 온기.",
      _FreeLayout.paired,
      1,
      3,
    ),
    _FreeSpread(
      "한자리에 모이면",
      "여러 세대가\n하나의 사진에.",
      "오늘의 가족을 기록한다.",
      _FreeLayout.gallery,
      0,
      1,
    ),
    _FreeSpread(
      "작은 일상의 유산",
      "큰 선물보다\n작은 습관으로.",
      "우리 집에 오래 남은 것들.",
      _FreeLayout.stillLife,
      3,
      4,
    ),
    _FreeSpread(
      "같이 웃는 이유",
      "나이는 달라도\n웃음은 같아.",
      "세대를 넘는 즐거운 순간.",
      _FreeLayout.mosaic,
      0,
      1,
    ),
    _FreeSpread(
      "가족의 시간표",
      "지나온 날과\n다가올 날 사이.",
      "기억하고 싶은 날짜들을 적는다.",
      _FreeLayout.milestone,
      0,
      3,
    ),
    _FreeSpread(
      "함께 걷던 길",
      "속도를 맞추면\n모두의 산책.",
      "옆에서 나란히 걸어 보기.",
      _FreeLayout.panorama,
      0,
      4,
    ),
    _FreeSpread(
      "식탁의 기억",
      "익숙한 맛에서\n다시 만나는 마음.",
      "한 끼에 담긴 긴 이야기.",
      _FreeLayout.window,
      3,
      1,
    ),
    _FreeSpread(
      "다정한 호칭",
      "부르는 이름마다\n담겨 있는 사랑.",
      "가족만의 이름을 남겨 둔다.",
      _FreeLayout.ledger,
      0,
      1,
    ),
    _FreeSpread(
      "오래 전하고 싶은 말",
      "지금의 마음을\n다음 세대에게.",
      "사진 뒤에 적어 둔 이야기.",
      _FreeLayout.letter,
      0,
      3,
    ),
    _FreeSpread(
      "이어지는 사진",
      "다음 장에도\n우리는 함께.",
      "시간이 지나도 남아 있을 마음.",
      _FreeLayout.closing,
      0,
      1,
    ),
  ],
  FreeCollectionVolume.familyOuting: [
    _FreeSpread(
      "소풍 가는 날",
      "문밖으로\n같이 나가자.",
      "오늘은 조금 다른 풍경으로.",
      _FreeLayout.opening,
      0,
      4,
    ),
    _FreeSpread(
      "가방을 챙기며",
      "작은 가방에\n기대도 함께.",
      "빠뜨리지 않고 챙긴 것들.",
      _FreeLayout.pinboard,
      4,
      3,
    ),
    _FreeSpread(
      "우리의 목적지",
      "멀지 않아도\n충분히 좋아.",
      "길 위에서 시작된 이야기.",
      _FreeLayout.fieldNotes,
      0,
      4,
    ),
    _FreeSpread(
      "돗자리를 펴다",
      "초록 위에\n우리의 자리.",
      "앉을 자리를 고르던 마음.",
      _FreeLayout.panorama,
      0,
      4,
    ),
    _FreeSpread(
      "도시락의 시간",
      "밖에서 먹으면\n조금 더 맛있어.",
      "나눠 먹어 더 좋은 한 끼.",
      _FreeLayout.stillLife,
      3,
      4,
    ),
    _FreeSpread(
      "햇살 속 얼굴",
      "햇살만큼\n환하게 웃어.",
      "오늘 가장 밝았던 표정.",
      _FreeLayout.gallery,
      0,
      1,
    ),
    _FreeSpread(
      "마음대로 놀기",
      "계획에 없던\n시간이 좋아.",
      "자유롭게 채운 오후.",
      _FreeLayout.contact,
      0,
      2,
    ),
    _FreeSpread(
      "같이 걷는 길",
      "뒤처지면\n잠깐 기다리기.",
      "같은 속도로 만든 산책.",
      _FreeLayout.paired,
      0,
      4,
    ),
    _FreeSpread(
      "잠깐의 쉼",
      "그늘 아래\n이야기가 쌓여.",
      "아무것도 하지 않아 좋았던 순간.",
      _FreeLayout.window,
      2,
      4,
    ),
    _FreeSpread(
      "오늘 주운 기억",
      "사진 몇 장과\n다정한 한마디.",
      "소풍에서 가져온 조각들.",
      _FreeLayout.keepsake,
      4,
      0,
    ),
    _FreeSpread(
      "돌아오는 길",
      "조금 피곤해도\n마음은 가득.",
      "집으로 가져온 하루의 온기.",
      _FreeLayout.ribbonPair,
      0,
      1,
    ),
    _FreeSpread(
      "또 함께 떠나자",
      "다음 소풍에도\n같은 사람들과.",
      "우리의 다음 바깥 하루를 위해.",
      _FreeLayout.closing,
      0,
      4,
    ),
  ],
  FreeCollectionVolume.usDays: [
    _FreeSpread(
      "우리의 첫 날짜",
      "그날부터\n우리가 시작돼.",
      "함께 쓰는 시간의 첫 장.",
      _FreeLayout.milestone,
      0,
      3,
    ),
    _FreeSpread(
      "처음 나눈 대화",
      "짧은 인사가\n긴 이야기가 돼.",
      "서로가 궁금해지던 날.",
      _FreeLayout.ribbonPair,
      1,
      0,
    ),
    _FreeSpread(
      "두 번째 약속",
      "다시 만날 날을\n기다리는 마음.",
      "달력에 동그라미를 그리던 순간.",
      _FreeLayout.postcard,
      3,
      1,
    ),
    _FreeSpread(
      "취향을 알아가며",
      "너의 좋아함이\n나에게도 스며.",
      "함께 고른 작은 것들.",
      _FreeLayout.stillLife,
      3,
      1,
    ),
    _FreeSpread(
      "같이 걷는 길",
      "손을 잡으면\n길이 달라져.",
      "같은 풍경을 나누는 산책.",
      _FreeLayout.panorama,
      0,
      4,
    ),
    _FreeSpread(
      "우리의 단골",
      "자주 가는 곳에\n쌓이는 시간.",
      "함께 앉던 자리를 기억한다.",
      _FreeLayout.gallery,
      1,
      3,
    ),
    _FreeSpread(
      "평범한 주말",
      "별일 없어도\n너와 있으면.",
      "일상이 된 다정한 장면.",
      _FreeLayout.contact,
      0,
      1,
    ),
    _FreeSpread(
      "작은 축하",
      "잊지 않고\n기억하는 마음.",
      "서로의 하루를 축하해 준 날.",
      _FreeLayout.window,
      2,
      3,
    ),
    _FreeSpread(
      "서로의 편",
      "다른 날에도\n같은 편으로.",
      "힘이 되어 준 말을 적어 둔다.",
      _FreeLayout.letter,
      1,
      3,
    ),
    _FreeSpread(
      "날짜가 쌓이다",
      "기념일 사이에\n더 많은 사랑.",
      "지나온 날들을 한눈에.",
      _FreeLayout.pinboard,
      2,
      0,
    ),
    _FreeSpread(
      "오늘의 우리",
      "처음보다\n조금 더 가까이.",
      "지금의 두 사람을 남긴다.",
      _FreeLayout.portraitEssay,
      0,
      2,
    ),
    _FreeSpread(
      "내일의 약속",
      "다음 날짜에도\n너와 나란히.",
      "아직 쓰지 않은 이야기를 위해.",
      _FreeLayout.closing,
      0,
      1,
    ),
  ],
  FreeCollectionVolume.dateFilm: [
    _FreeSpread(
      "첫 장면",
      "우리의 일상이\n영화가 된다.",
      "두 사람만 아는 시작 장면.",
      _FreeLayout.gallery,
      0,
      1,
    ),
    _FreeSpread(
      "오프닝의 대화",
      "별것 아닌 말로\n하루를 열어.",
      "서로에게 건넨 첫 인사.",
      _FreeLayout.opening,
      1,
      3,
    ),
    _FreeSpread(
      "빛이 좋은 자리",
      "창가에 앉아\n너를 바라봐.",
      "오후의 빛으로 남긴 얼굴.",
      _FreeLayout.portraitEssay,
      1,
      0,
    ),
    _FreeSpread(
      "산책의 시퀀스",
      "나란히 걸으며\n쌓이는 장면.",
      "한 걸음마다 달라지는 풍경.",
      _FreeLayout.panorama,
      0,
      4,
    ),
    _FreeSpread(
      "우리의 소품",
      "작은 물건도\n이야기가 된다.",
      "함께 고른 것들의 출연 목록.",
      _FreeLayout.stillLife,
      3,
      1,
    ),
    _FreeSpread(
      "웃음의 연속",
      "멈추기 아까운\n웃음의 순간.",
      "비슷하지만 모두 다른 표정.",
      _FreeLayout.contact,
      1,
      2,
    ),
    _FreeSpread(
      "장면과 장면 사이",
      "잠깐 쉬어도\n이야기는 계속.",
      "사진 사이의 조용한 여백.",
      _FreeLayout.window,
      0,
      3,
    ),
    _FreeSpread(
      "축하의 클로즈업",
      "오늘의 주인공은\n너와 나.",
      "서로를 위해 준비한 작은 선물.",
      _FreeLayout.ribbonPair,
      2,
      3,
    ),
    _FreeSpread(
      "기억의 편집",
      "마음에 남은\n장면부터.",
      "하루를 다시 골라 보는 시간.",
      _FreeLayout.mosaic,
      0,
      2,
    ),
    _FreeSpread(
      "내레이션",
      "말하지 못한\n마음도 담아.",
      "사진 밖의 이야기를 남긴다.",
      _FreeLayout.letter,
      1,
      3,
    ),
    _FreeSpread(
      "엔딩의 빛",
      "하루의 끝에도\n네가 있어.",
      "끝나서 더 소중해진 장면.",
      _FreeLayout.paired,
      0,
      2,
    ),
    _FreeSpread(
      "다음 편의 우리",
      "계속 보고 싶은\n두 사람의 영화.",
      "함께할 다음 장면을 기다린다.",
      _FreeLayout.closing,
      0,
      1,
    ),
  ],
  FreeCollectionVolume.loveSeason: [
    _FreeSpread(
      "사랑의 계절",
      "너와 함께\n빛이 달라져.",
      "같은 계절을 나누는 두 사람.",
      _FreeLayout.window,
      0,
      3,
    ),
    _FreeSpread(
      "봄날의 약속",
      "조금 가벼운\n마음으로 만나.",
      "새로운 시작을 함께한 날.",
      _FreeLayout.ribbonPair,
      1,
      3,
    ),
    _FreeSpread(
      "꽃을 고르다",
      "네가 좋아할\n색을 생각해.",
      "작은 꽃에 담은 마음.",
      _FreeLayout.stillLife,
      3,
      2,
    ),
    _FreeSpread(
      "햇살 따라 걷기",
      "봄의 길 위에\n우리의 발걸음.",
      "서두르지 않고 바라본 풍경.",
      _FreeLayout.panorama,
      0,
      4,
    ),
    _FreeSpread(
      "여름의 대화",
      "시원한 한 잔과\n길어진 이야기.",
      "시간 가는 줄 몰랐던 자리.",
      _FreeLayout.gallery,
      1,
      0,
    ),
    _FreeSpread(
      "물빛의 얼굴",
      "같은 바다를\n같은 마음으로.",
      "여름의 가장 선명한 사진.",
      _FreeLayout.portraitEssay,
      0,
      4,
    ),
    _FreeSpread(
      "우리의 작은 축제",
      "특별한 날을\n서로에게 선물해.",
      "기억하고 축하하는 마음.",
      _FreeLayout.pinboard,
      2,
      3,
    ),
    _FreeSpread(
      "가을의 취향",
      "함께 좋아하는\n것들이 늘어.",
      "서로 닮아 가는 목록.",
      _FreeLayout.fieldNotes,
      3,
      1,
    ),
    _FreeSpread(
      "한 장의 편지",
      "차분한 계절에\n꺼내 보는 말.",
      "다정함을 글로 남기는 시간.",
      _FreeLayout.letter,
      2,
      3,
    ),
    _FreeSpread(
      "곁에 머무는 겨울",
      "밖이 추워도\n함께라 따뜻해.",
      "집에서 나눈 평범한 행복.",
      _FreeLayout.paired,
      2,
      1,
    ),
    _FreeSpread(
      "계절을 모아서",
      "네 번의 빛과\n수많은 표정.",
      "한 해를 천천히 돌아본다.",
      _FreeLayout.contact,
      0,
      2,
    ),
    _FreeSpread(
      "또 돌아오는 봄",
      "계절이 바뀌어도\n우리는 계속.",
      "다음 봄에도 같은 마음으로.",
      _FreeLayout.closing,
      0,
      3,
    ),
  ],
  FreeCollectionVolume.anniversary: [
    _FreeSpread(
      "오늘의 기념일",
      "함께한 시간을\n축하합니다.",
      "두 사람을 위한 작은 책.",
      _FreeLayout.ribbonPair,
      2,
      0,
    ),
    _FreeSpread(
      "처음의 마음",
      "그때의 우리를\n다시 만나.",
      "서로를 고르던 첫 장면.",
      _FreeLayout.portraitEssay,
      0,
      1,
    ),
    _FreeSpread(
      "우리가 쌓은 날",
      "특별한 하루와\n평범한 매일.",
      "사이사이 더 많았던 다정함.",
      _FreeLayout.milestone,
      2,
      0,
    ),
    _FreeSpread(
      "서로의 취향",
      "이젠 제법\n잘 아는 것들.",
      "말하지 않아도 떠오르는 선택.",
      _FreeLayout.stillLife,
      3,
      1,
    ),
    _FreeSpread(
      "자주 가던 곳",
      "같은 자리에\n달라진 우리.",
      "추억이 된 단골의 풍경.",
      _FreeLayout.gallery,
      1,
      0,
    ),
    _FreeSpread(
      "함께 떠난 날",
      "길을 나서면\n더 가까워져.",
      "낯선 곳에서 배운 서로.",
      _FreeLayout.panorama,
      0,
      4,
    ),
    _FreeSpread(
      "곁을 지키는 일",
      "큰말보다\n매일의 마음.",
      "작은 배려들을 기록한다.",
      _FreeLayout.fieldNotes,
      1,
      2,
    ),
    _FreeSpread(
      "웃음의 기록",
      "함께 웃어서\n더 좋은 얼굴.",
      "우리가 고른 행복한 장면들.",
      _FreeLayout.mosaic,
      2,
      0,
    ),
    _FreeSpread(
      "오늘의 선물",
      "마음을 담아\n너에게 건네.",
      "포장을 열기 전의 설렘.",
      _FreeLayout.keepsake,
      3,
      2,
    ),
    _FreeSpread(
      "고마웠던 순간",
      "너에게 꼭\n전하고 싶은 말.",
      "기념일에 쓰는 감사의 편지.",
      _FreeLayout.letter,
      2,
      1,
    ),
    _FreeSpread(
      "지금의 초상",
      "오늘의 우리를\n오래 기억해.",
      "한 장에 담은 현재의 두 사람.",
      _FreeLayout.paired,
      0,
      2,
    ),
    _FreeSpread(
      "오래도록 우리",
      "다음 기념일도\n네 옆에서.",
      "함께 쓰는 다음 해를 위해.",
      _FreeLayout.closing,
      2,
      0,
    ),
  ],
  FreeCollectionVolume.twoTickets: [
    _FreeSpread(
      "둘의 수집함",
      "작은 조각에\n하루를 붙여.",
      "함께 모은 기억을 펼친다.",
      _FreeLayout.pinboard,
      3,
      0,
    ),
    _FreeSpread(
      "첫 번째 표",
      "같이 들어간\n그날의 문.",
      "입장권 한 장의 작은 이야기.",
      _FreeLayout.postcard,
      3,
      1,
    ),
    _FreeSpread(
      "카페의 오후",
      "한 잔을 사이에\n오가는 마음.",
      "메뉴보다 오래 기억할 대화.",
      _FreeLayout.gallery,
      1,
      3,
    ),
    _FreeSpread(
      "길 위의 엽서",
      "같은 풍경을\n다르게 기억해.",
      "서로 고른 장면을 나란히.",
      _FreeLayout.ribbonPair,
      0,
      4,
    ),
    _FreeSpread(
      "너의 작은 선물",
      "별것 아닌 듯\n소중한 것.",
      "받던 날의 마음까지 남긴다.",
      _FreeLayout.keepsake,
      3,
      2,
    ),
    _FreeSpread(
      "사진을 고르는 밤",
      "이 장면이\n나는 참 좋아.",
      "각자가 고른 오늘의 한 장.",
      _FreeLayout.contact,
      0,
      1,
    ),
    _FreeSpread(
      "날짜를 붙여서",
      "잊지 않도록\n짧게 적어 둬.",
      "누구와 어디에서 웃었는지.",
      _FreeLayout.milestone,
      2,
      3,
    ),
    _FreeSpread(
      "우리만의 지도",
      "점과 점 사이\n우리의 길.",
      "다시 가고 싶은 곳의 목록.",
      _FreeLayout.fieldNotes,
      0,
      1,
    ),
    _FreeSpread(
      "소중한 구석",
      "작은 모서리에도\n기억이 남아.",
      "편지와 리본을 함께 모은다.",
      _FreeLayout.stillLife,
      3,
      2,
    ),
    _FreeSpread(
      "책 사이의 마음",
      "꺼내 읽으면\n다시 그날로.",
      "접어 둔 마음을 펼쳐 본다.",
      _FreeLayout.letter,
      1,
      3,
    ),
    _FreeSpread(
      "한 권이 된 조각",
      "따로였던 날이\n하나의 이야기로.",
      "흩어진 사진을 모으는 즐거움.",
      _FreeLayout.mosaic,
      0,
      2,
    ),
    _FreeSpread(
      "빈칸을 남겨",
      "다음 조각도\n함께 모으자.",
      "새로운 표를 넣을 자리를 비워 둔다.",
      _FreeLayout.closing,
      0,
      3,
    ),
  ],
  FreeCollectionVolume.pawDiary: [
    _FreeSpread(
      "네가 여는 아침",
      "눈을 뜨면\n가장 먼저 너.",
      "하루의 시작에 있는 얼굴.",
      _FreeLayout.portraitEssay,
      0,
      2,
    ),
    _FreeSpread(
      "아침의 인사",
      "말은 달라도\n마음은 같아.",
      "다가오는 발소리를 기억한다.",
      _FreeLayout.gallery,
      0,
      1,
    ),
    _FreeSpread(
      "너의 준비물",
      "익숙한 물건에\n안심하는 마음.",
      "매일 함께 쓰는 작은 것들.",
      _FreeLayout.stillLife,
      2,
      3,
    ),
    _FreeSpread(
      "산책 가는 길",
      "문이 열리면\n세상이 반가워.",
      "오늘도 함께 나선 길.",
      _FreeLayout.panorama,
      1,
      0,
    ),
    _FreeSpread(
      "궁금한 냄새",
      "잠깐 멈춰서\n자세히 알아봐.",
      "너의 속도로 걸어 보는 산책.",
      _FreeLayout.fieldNotes,
      1,
      0,
    ),
    _FreeSpread(
      "초록의 놀이터",
      "맘껏 바라보고\n천천히 즐겨.",
      "잔디 위의 기분 좋은 표정.",
      _FreeLayout.paired,
      0,
      1,
    ),
    _FreeSpread(
      "돌아온 자리",
      "밖도 좋지만\n집도 참 좋아.",
      "익숙한 공간으로 돌아온 안도.",
      _FreeLayout.window,
      3,
      2,
    ),
    _FreeSpread(
      "낮잠의 시간",
      "잘 쉬는 것도\n중요한 하루.",
      "조용히 지켜본 잠든 얼굴.",
      _FreeLayout.ribbonPair,
      3,
      0,
    ),
    _FreeSpread(
      "표정 사전",
      "사진마다 다른\n너의 이야기.",
      "우리만 아는 표정을 모은다.",
      _FreeLayout.contact,
      0,
      1,
    ),
    _FreeSpread(
      "좋아하는 목록",
      "작은 취향을\n기억해 둘게.",
      "네가 고르는 것들을 적는다.",
      _FreeLayout.ledger,
      2,
      0,
    ),
    _FreeSpread(
      "오늘의 한 장",
      "평범해서\n더 소중한 날.",
      "오래 보고 싶은 장면을 고른다.",
      _FreeLayout.pinboard,
      0,
      3,
    ),
    _FreeSpread(
      "내일도 네 곁에",
      "같이 걷고\n같이 쉬자.",
      "평범한 내일을 함께 기다린다.",
      _FreeLayout.closing,
      3,
      0,
    ),
  ],
  FreeCollectionVolume.catNap: [
    _FreeSpread(
      "너의 작은 세계",
      "조용히 보면\n많은 이야기.",
      "고양이의 하루를 천천히 연다.",
      _FreeLayout.portraitEssay,
      0,
      1,
    ),
    _FreeSpread(
      "창가의 시간",
      "햇빛을 따라\n자리를 옮겨.",
      "오늘 가장 좋아한 자리.",
      _FreeLayout.window,
      0,
      1,
    ),
    _FreeSpread(
      "바깥 구경",
      "눈동자에 담긴\n작은 바깥 세상.",
      "창 너머를 오래 바라보던 아침.",
      _FreeLayout.gallery,
      0,
      1,
    ),
    _FreeSpread(
      "편안한 물건",
      "익숙한 감촉에\n몸을 기대.",
      "네가 머무는 곳을 기억한다.",
      _FreeLayout.stillLife,
      2,
      1,
    ),
    _FreeSpread(
      "동그랗게 쉬기",
      "접힌 몸에도\n편안한 리듬.",
      "각자 다른 낮잠의 모양.",
      _FreeLayout.ribbonPair,
      1,
      0,
    ),
    _FreeSpread(
      "느린 오후",
      "서두를 일 없는\n너의 시간.",
      "고요한 방에 햇빛이 머문다.",
      _FreeLayout.panorama,
      0,
      1,
    ),
    _FreeSpread(
      "아주 작은 움직임",
      "귀 하나에도\n마음이 보여.",
      "조용히 관찰한 표정의 차이.",
      _FreeLayout.fieldNotes,
      0,
      1,
    ),
    _FreeSpread(
      "자리의 취향",
      "오늘은 여기가\n좋은가 봐.",
      "좋아하는 자리를 표시해 둔다.",
      _FreeLayout.ledger,
      1,
      2,
    ),
    _FreeSpread(
      "낮잠 수집",
      "비슷한 듯\n다른 잠든 얼굴.",
      "깨우지 않고 모아 둔 사진.",
      _FreeLayout.paired,
      1,
      0,
    ),
    _FreeSpread(
      "함께 사는 감각",
      "말없이 곁에\n머무는 다정함.",
      "같은 방에서 각자의 시간을.",
      _FreeLayout.keepsake,
      2,
      1,
    ),
    _FreeSpread(
      "너에게 쓰는 말",
      "그저 곁에 있어\n참 고마워.",
      "매일의 동행에게 남기는 편지.",
      _FreeLayout.letter,
      0,
      1,
    ),
    _FreeSpread(
      "다음 햇살에도",
      "내일도 이곳에\n편히 머물러.",
      "함께할 조용한 날들을 위해.",
      _FreeLayout.closing,
      1,
      0,
    ),
  ],
  FreeCollectionVolume.walkClub: [
    _FreeSpread(
      "오늘도 산책",
      "서두르지 말고\n같이 걸어.",
      "너와 나의 매일의 약속.",
      _FreeLayout.fieldNotes,
      1,
      0,
    ),
    _FreeSpread(
      "출발 전 점검",
      "편안한 준비로\n기분 좋은 시작.",
      "목줄과 물을 챙기는 시간.",
      _FreeLayout.stillLife,
      2,
      1,
    ),
    _FreeSpread(
      "문밖의 첫 걸음",
      "늘 같은 길도\n새롭게 보여.",
      "너를 따라 발견하는 동네.",
      _FreeLayout.opening,
      1,
      0,
    ),
    _FreeSpread(
      "우리의 단골 길",
      "좋아하는 길을\n기억해 두자.",
      "쉬어 가기 좋은 곳을 기록한다.",
      _FreeLayout.milestone,
      1,
      2,
    ),
    _FreeSpread(
      "잠깐 멈추는 곳",
      "기다려 주면\n더 즐거워져.",
      "충분히 맡고 바라보는 시간.",
      _FreeLayout.window,
      0,
      1,
    ),
    _FreeSpread(
      "초록 아래서",
      "햇살과 그늘을\n함께 지나.",
      "계절이 담긴 오늘의 산책.",
      _FreeLayout.panorama,
      0,
      1,
    ),
    _FreeSpread(
      "같은 방향",
      "나란히 걸으며\n맞추는 속도.",
      "너와 내가 편한 걸음을 찾는다.",
      _FreeLayout.paired,
      1,
      0,
    ),
    _FreeSpread(
      "쉬어 가는 약속",
      "잘 걷기 위해\n잠깐 쉬어.",
      "물 한 모금과 짧은 휴식.",
      _FreeLayout.ribbonPair,
      0,
      2,
    ),
    _FreeSpread(
      "오늘 만난 풍경",
      "익숙한 동네에\n새로운 장면.",
      "길에서 발견한 작은 변화.",
      _FreeLayout.pinboard,
      1,
      0,
    ),
    _FreeSpread(
      "집으로 돌아와",
      "다녀왔다는\n편안한 인사.",
      "기분 좋게 쉬는 산책의 끝.",
      _FreeLayout.gallery,
      3,
      2,
    ),
    _FreeSpread(
      "걸음을 남기다",
      "길이 쌓이고\n마음도 쌓여.",
      "좋았던 길과 시간을 적는다.",
      _FreeLayout.ledger,
      1,
      0,
    ),
    _FreeSpread(
      "내일의 같은 시간",
      "또 같이\n문밖으로 나가자.",
      "평범한 약속을 오래 지키기.",
      _FreeLayout.closing,
      0,
      3,
    ),
  ],
  FreeCollectionVolume.petHome: [
    _FreeSpread(
      "작은 가족 소개",
      "우리 집에는\n네 자리가 있어.",
      "함께 사는 하루의 첫 장.",
      _FreeLayout.pinboard,
      0,
      1,
    ),
    _FreeSpread(
      "처음 익힌 공간",
      "조금씩 천천히\n집이 되어 가.",
      "편안해진 순간들을 모은다.",
      _FreeLayout.window,
      0,
      2,
    ),
    _FreeSpread(
      "좋아하는 자리",
      "네가 고르면\n그곳이 좋은 곳.",
      "한동안 머문 자리를 기록한다.",
      _FreeLayout.gallery,
      1,
      0,
    ),
    _FreeSpread(
      "함께 쓰는 물건",
      "작은 물건에도\n생활이 담겨.",
      "익숙해진 감촉과 냄새.",
      _FreeLayout.stillLife,
      2,
      1,
    ),
    _FreeSpread(
      "눈을 마주치면",
      "말없이 나누는\n우리의 인사.",
      "서로를 알아보는 눈빛.",
      _FreeLayout.portraitEssay,
      0,
      1,
    ),
    _FreeSpread(
      "하루의 습관",
      "반복되는 일에\n마음이 놓여.",
      "함께 맞춰 온 생활의 리듬.",
      _FreeLayout.milestone,
      1,
      2,
    ),
    _FreeSpread(
      "귀여운 순간들",
      "그냥 지나치기엔\n너무 소중해.",
      "별일 아닌 표정도 모아 둔다.",
      _FreeLayout.ribbonPair,
      0,
      1,
    ),
    _FreeSpread(
      "조용한 동행",
      "각자의 자리에서\n같은 시간을.",
      "옆에 있어 든든한 오후.",
      _FreeLayout.paired,
      1,
      0,
    ),
    _FreeSpread(
      "햇빛이 드는 방",
      "가장 편한 곳에\n너를 위해.",
      "오늘도 안심하고 쉴 수 있도록.",
      _FreeLayout.panorama,
      0,
      2,
    ),
    _FreeSpread(
      "우리의 기록함",
      "사진 몇 장과\n생활의 조각.",
      "쌓여 가는 작은 가족의 역사.",
      _FreeLayout.keepsake,
      2,
      1,
    ),
    _FreeSpread(
      "고마운 마음",
      "함께 살아 줘서\n참 고마워.",
      "서로의 집이 된 마음을 적는다.",
      _FreeLayout.letter,
      0,
      1,
    ),
    _FreeSpread(
      "계속되는 집",
      "내일도 편안히\n우리 곁에서.",
      "이 집의 다음 장면을 기다린다.",
      _FreeLayout.closing,
      1,
      0,
    ),
  ],
  FreeCollectionVolume.petPortrait: [
    _FreeSpread(
      "너라는 얼굴",
      "오래 바라봐도\n새로운 표정.",
      "소중한 동행의 작은 초상집.",
      _FreeLayout.portraitEssay,
      0,
      3,
    ),
    _FreeSpread(
      "눈빛의 이야기",
      "눈을 마주치면\n전해지는 마음.",
      "말보다 먼저 오는 대답.",
      _FreeLayout.gallery,
      0,
      1,
    ),
    _FreeSpread(
      "햇빛의 윤곽",
      "빛이 닿은 털과\n다정한 눈.",
      "평범한 오후에 남긴 초상.",
      _FreeLayout.window,
      0,
      3,
    ),
    _FreeSpread(
      "움직이는 순간",
      "멈춘 사진에\n담긴 생기.",
      "산책에서 만난 활기찬 모습.",
      _FreeLayout.panorama,
      1,
      0,
    ),
    _FreeSpread(
      "가까운 기록",
      "작은 부분에도\n너다운 모습.",
      "소중해서 자세히 보게 되는 것.",
      _FreeLayout.paired,
      0,
      2,
    ),
    _FreeSpread(
      "편안한 얼굴",
      "긴장이 풀린\n가장 자연스러운 너.",
      "집에서 발견하는 조용한 표정.",
      _FreeLayout.ribbonPair,
      3,
      0,
    ),
    _FreeSpread(
      "머무는 자리",
      "네가 있으면\n장소가 달라져.",
      "함께 살아가는 공간의 초상.",
      _FreeLayout.fieldNotes,
      3,
      2,
    ),
    _FreeSpread(
      "너의 소지품",
      "오래 함께한\n작은 물건들.",
      "일상의 감촉도 사진에 담는다.",
      _FreeLayout.stillLife,
      2,
      0,
    ),
    _FreeSpread(
      "하루의 표정집",
      "한 장으로는\n다 담을 수 없어.",
      "달라지는 눈빛과 자세를 모은다.",
      _FreeLayout.contact,
      0,
      1,
    ),
    _FreeSpread(
      "고른 한 장",
      "여러 장 중에\n자꾸 보게 되는 사진.",
      "지금의 너를 오래 기억한다.",
      _FreeLayout.pinboard,
      0,
      3,
    ),
    _FreeSpread(
      "사진 밖의 마음",
      "보이지 않아도\n분명한 다정함.",
      "너에게 보내는 짧은 말.",
      _FreeLayout.letter,
      3,
      0,
    ),
    _FreeSpread(
      "오래도록 간직해",
      "시간이 흘러도\n선명한 얼굴.",
      "같이 보낸 날들을 소중히 담는다.",
      _FreeLayout.closing,
      0,
      3,
    ),
  ],
};
