part of 'studio_decoration_catalog.dart';

const conceptWaveDecorations = [
  ...lifeConceptDecorations,
  StudioDecorationSpec(
    'waveSilkKnot',
    '실크 매듭과 은빛 링',
    StudioDecorationCategory.sticker,
    1,
    .32,
    assetPath: 'assets/sticker/studio/wave_silk_knot.png',
    collection: '서약의 아틀리에',
  ),
  StudioDecorationSpec(
    'waveSeaGlass',
    '파도가 다듬은 유리',
    StudioDecorationCategory.sticker,
    1,
    .26,
    assetPath: 'assets/sticker/studio/wave_sea_glass.png',
    collection: '해변의 기록',
  ),
  StudioDecorationSpec(
    'wavePencil',
    '짧아진 코발트 연필',
    StudioDecorationCategory.sticker,
    1,
    .32,
    assetPath: 'assets/sticker/studio/wave_pencil.png',
    collection: '책상 위 수집',
  ),
];

const lifeConceptDecorations = [
  ...lifeVarietyCutouts,
  ...lifeVarietyPapers,
  StudioDecorationSpec(
    'lifeBonnet',
    '처음 쓴 코튼 보닛',
    StudioDecorationCategory.sticker,
    1,
    .34,
    assetPath: 'assets/sticker/studio/life_bonnet.png',
    collection: '작은 첫 계절',
  ),
  StudioDecorationSpec(
    'lifeGingham',
    '접어 둔 체크 피크닉 천',
    StudioDecorationCategory.paper,
    1,
    .62,
    assetPath: 'assets/sticker/studio/life_gingham.png',
    collection: '함께 차린 식탁',
  ),
  StudioDecorationSpec(
    'lifeHouseKey',
    '우리 집 열쇠와 코튼 고리',
    StudioDecorationCategory.sticker,
    1,
    .28,
    assetPath: 'assets/sticker/studio/life_house_key.png',
    collection: '둘의 보관함',
  ),
  StudioDecorationSpec(
    'lifeRopeBall',
    '손때 묻은 직조 공',
    StudioDecorationCategory.sticker,
    1,
    .32,
    assetPath: 'assets/sticker/studio/life_rope_ball.png',
    collection: '산책의 흔적',
  ),
];

const lifeVarietyCutouts = [
  StudioDecorationSpec(
    'lifeRattle',
    '첫 놀이 나무 딸랑이',
    StudioDecorationCategory.sticker,
    1,
    .30,
    assetPath: 'assets/sticker/studio/life_rattle.png',
    collection: '작은 첫 계절',
  ),
  StudioDecorationSpec(
    'lifeBib',
    '민트 거즈 턱받이',
    StudioDecorationCategory.sticker,
    1,
    .34,
    assetPath: 'assets/sticker/studio/life_bib.png',
    collection: '작은 첫 계절',
  ),
  StudioDecorationSpec(
    'lifeBasket',
    '일요일 버드나무 바구니',
    StudioDecorationCategory.sticker,
    1,
    .36,
    assetPath: 'assets/sticker/studio/life_basket.png',
    collection: '함께 차린 식탁',
  ),
  StudioDecorationSpec(
    'lifeMug',
    '숲색 법랑 컵',
    StudioDecorationCategory.sticker,
    1,
    .28,
    assetPath: 'assets/sticker/studio/life_mug.png',
    collection: '함께 차린 식탁',
  ),
  StudioDecorationSpec(
    'lifeSlippers',
    '나란한 코튼 실내화',
    StudioDecorationCategory.sticker,
    1,
    .32,
    assetPath: 'assets/sticker/studio/life_slippers.png',
    collection: '둘의 보관함',
  ),
  StudioDecorationSpec(
    'lifeVase',
    '창가의 올리브 화병',
    StudioDecorationCategory.sticker,
    1,
    .30,
    assetPath: 'assets/sticker/studio/life_vase.png',
    collection: '둘의 보관함',
  ),
  StudioDecorationSpec(
    'lifeFeltMouse',
    '작은 양모 장난감',
    StudioDecorationCategory.sticker,
    1,
    .28,
    assetPath: 'assets/sticker/studio/life_mouse.png',
    collection: '산책의 흔적',
  ),
  StudioDecorationSpec(
    'lifeBowl',
    '청록 테두리 세라믹 식기',
    StudioDecorationCategory.sticker,
    1,
    .30,
    assetPath: 'assets/sticker/studio/life_bowl.png',
    collection: '산책의 흔적',
  ),
];

const lifeVarietyPapers = [
  StudioDecorationSpec(
    'lifeWardrobeLabel',
    '봉제선 성장 라벨',
    StudioDecorationCategory.paper,
    1.5,
    .58,
    collection: '작은 첫 계절',
  ),
  StudioDecorationSpec(
    'lifePicnicSlip',
    '절취선 피크닉 카드',
    StudioDecorationCategory.paper,
    1.5,
    .58,
    collection: '함께 차린 식탁',
  ),
  StudioDecorationSpec(
    'lifeHomeNote',
    '접어 둔 생활 메모',
    StudioDecorationCategory.paper,
    1.5,
    .58,
    collection: '둘의 보관함',
  ),
  StudioDecorationSpec(
    'lifeCompanionTab',
    '색인형 관찰 카드',
    StudioDecorationCategory.paper,
    1.5,
    .58,
    collection: '산책의 흔적',
  ),
];
