part of 'studio_decoration_catalog.dart';

const keepsakeMaterialCollections = [
  '서약의 아틀리에',
  '해변의 기록',
  '책상 위 수집',
  '작은 첫 계절',
  '함께 차린 식탁',
  '둘의 보관함',
  '산책의 흔적',
];

/// Original cutouts and independently drawn stationery. IDs are document and
/// point-shop identities; collections group discovery, not purchase ownership.
const keepsakeDecorations = [
  StudioDecorationSpec(
    'materialLace',
    '자수 레이스 코너',
    StudioDecorationCategory.sticker,
    1,
    .42,
    assetPath: 'assets/sticker/studio/material_lace.png',
    collection: '서약의 아틀리에',
  ),
  StudioDecorationSpec(
    'materialShell',
    '해변에서 주운 조개',
    StudioDecorationCategory.sticker,
    1,
    .28,
    assetPath: 'assets/sticker/studio/material_shell.png',
    collection: '해변의 기록',
  ),
  StudioDecorationSpec(
    'materialBookmark',
    '마블링 책갈피',
    StudioDecorationCategory.paper,
    2 / 3,
    .28,
    assetPath: 'assets/sticker/studio/material_bookmark.png',
    collection: '책상 위 수집',
  ),
  StudioDecorationSpec(
    'materialBooties',
    '첫 니트 신발',
    StudioDecorationCategory.sticker,
    1,
    .32,
    assetPath: 'assets/sticker/studio/material_booties.png',
    collection: '작은 첫 계절',
  ),
  StudioDecorationSpec(
    'materialLinen',
    '숲색 리넨 조각',
    StudioDecorationCategory.paper,
    1,
    .60,
    assetPath: 'assets/sticker/studio/material_linen.png',
    collection: '함께 차린 식탁',
  ),
  StudioDecorationSpec(
    'materialRose',
    '간직한 장미',
    StudioDecorationCategory.sticker,
    2 / 3,
    .25,
    assetPath: 'assets/sticker/studio/material_rose.png',
    collection: '둘의 보관함',
  ),
  StudioDecorationSpec(
    'materialLeash',
    '세이지 산책 끈',
    StudioDecorationCategory.sticker,
    1,
    .36,
    assetPath: 'assets/sticker/studio/material_leash.png',
    collection: '산책의 흔적',
  ),
  StudioDecorationSpec(
    'materialClip',
    '은빛 아카이브 집게',
    StudioDecorationCategory.sticker,
    1,
    .20,
    assetPath: 'assets/sticker/studio/material_clip.png',
    collection: '책상 위 수집',
  ),
  StudioDecorationSpec(
    'materialBlindEmboss',
    '압인 문장 카드',
    StudioDecorationCategory.paper,
    .78,
    .57,
    collection: '서약의 아틀리에',
  ),
  StudioDecorationSpec(
    'materialVellumBand',
    '반투명 봉합 띠',
    StudioDecorationCategory.tape,
    4.2,
    .58,
    collection: '서약의 아틀리에',
  ),
  StudioDecorationSpec(
    'materialContourMap',
    '등고선 여행지',
    StudioDecorationCategory.paper,
    1.35,
    .70,
    collection: '해변의 기록',
  ),
  StudioDecorationSpec(
    'materialTransitPunch',
    '펀칭 여행 태그',
    StudioDecorationCategory.paper,
    .55,
    .33,
    collection: '해변의 기록',
  ),
  StudioDecorationSpec(
    'materialSpecimenPocket',
    '표본 보관 포켓',
    StudioDecorationCategory.paper,
    .84,
    .60,
    collection: '책상 위 수집',
  ),
  StudioDecorationSpec(
    'materialIndexTabs',
    '컬러 인덱스 탭',
    StudioDecorationCategory.tape,
    2.4,
    .43,
    collection: '책상 위 수집',
  ),
  StudioDecorationSpec(
    'materialScallopNote',
    '꽃잎 가장자리 노트',
    StudioDecorationCategory.paper,
    .90,
    .59,
    collection: '작은 첫 계절',
  ),
  StudioDecorationSpec(
    'materialMonthDial',
    '열두 달 기록 원판',
    StudioDecorationCategory.paper,
    1,
    .46,
    collection: '작은 첫 계절',
  ),
  StudioDecorationSpec(
    'materialRecipeFoldout',
    '접어 둔 레시피',
    StudioDecorationCategory.paper,
    1.55,
    .76,
    collection: '함께 차린 식탁',
  ),
  StudioDecorationSpec(
    'materialCrossStitchBand',
    '크로스 스티치 띠',
    StudioDecorationCategory.tape,
    4.4,
    .50,
    collection: '함께 차린 식탁',
  ),
  StudioDecorationSpec(
    'materialTicketDuo',
    '나란한 두 좌석',
    StudioDecorationCategory.paper,
    1.85,
    .58,
    collection: '둘의 보관함',
  ),
  StudioDecorationSpec(
    'materialAirLetter',
    '접힌 항공 편지',
    StudioDecorationCategory.paper,
    .84,
    .62,
    collection: '둘의 보관함',
  ),
  StudioDecorationSpec(
    'materialWalkLedger',
    '산책 관찰 수첩',
    StudioDecorationCategory.paper,
    .76,
    .60,
    collection: '산책의 흔적',
  ),
  StudioDecorationSpec(
    'materialNamePatch',
    '이름 자수 패치',
    StudioDecorationCategory.sticker,
    1.75,
    .40,
    collection: '산책의 흔적',
  ),
];
