part of 'layer_builder.dart';

double _styleHorizontalPaddingImpl(String type) {
  switch (type) {
    case "round":
    case "roundGray":
    case "roundPink":
    case "roundBlue":
    case "roundMint":
    case "roundLavender":
    case "roundOrange":
    case "roundGreen":
    case "roundCream":
    case "roundNavy":
    case "roundRose":
    case "roundCoral":
    case "roundBeige":
    case "roundTeal":
    case "roundLemon":
    case "square":
    case "squareGray":
    case "squarePink":
    case "squareBlue":
    case "squareMint":
    case "squareLavender":
    case "squareOrange":
    case "squareGreen":
    case "squareCream":
    case "squareNavy":
    case "squareRose":
    case "squareCoral":
    case "squareBeige":
    case "squareTeal":
    case "squareLemon":
    case "roundSoft":
    case "roundSoftGray":
    case "roundSoftPink":
    case "roundSoftBlue":
    case "roundSoftMint":
    case "roundSoftLavender":
    case "roundSoftOrange":
    case "roundSoftGreen":
    case "roundSoftCream":
    case "roundSoftNavy":
    case "roundSoftRose":
    case "roundSoftCoral":
    case "roundSoftBeige":
    case "roundSoftTeal":
    case "roundSoftLemon":
    case "softPill2":
    case "softPill2Gray":
    case "softPill2Pink":
    case "softPill2Blue":
    case "softPill2Mint":
    case "softPill2Lavender":
    case "softPill2Orange":
    case "softPill2Green":
    case "softPill2Cream":
    case "softPill2Navy":
    case "softPill2Rose":
    case "softPill2Coral":
    case "softPill2Beige":
    case "softPill2Teal":
    case "softPill2Lemon":
      return 28;
    case "label":
    case "labelGray":
    case "labelPink":
    case "labelBlue":
    case "labelMint":
    case "labelLavender":
    case "labelOrange":
    case "labelGreen":
    case "labelWhite":
    case "labelCream":
      return 28;
    case "tag":
    case "tagGray":
    case "tagPink":
    case "tagBlue":
    case "tagMint":
    case "tagLavender":
    case "tagOrange":
    case "tagGreen":
    case "tagRed":
      return 24;
    case "labelSolid":
    case "labelSolidGray":
    case "labelSolidPink":
    case "labelSolidBlue":
    case "labelSolidMint":
    case "labelSolidRed":
    case "labelSolidGreen":
    case "labelSolidOrange":
    case "labelSolidLavender":
    case "labelSolidCream":
    case "labelGold":
    case "labelNeon":
    case "labelRose":
      return 32;
    case "labelOutline":
      return 28;
    case "bubble":
    case "bubbleGray":
    case "bubblePink":
    case "bubbleBlue":
    case "bubbleMint":
    case "bubbleLavender":
    case "bubbleOrange":
    case "bubbleGreen":
    case "bubbleCream":
    case "bubbleNavy":
    case "bubbleRose":
    case "bubbleCoral":
    case "bubbleBeige":
    case "bubbleTeal":
    case "bubbleLemon":
    case "bubbleCenter":
    case "bubbleCenterGray":
    case "bubbleCenterPink":
    case "bubbleCenterBlue":
    case "bubbleCenterMint":
    case "bubbleCenterLavender":
    case "bubbleCenterOrange":
    case "bubbleCenterGreen":
    case "bubbleCenterCream":
    case "bubbleCenterNavy":
    case "bubbleCenterRose":
    case "bubbleCenterCoral":
    case "bubbleCenterBeige":
    case "bubbleCenterTeal":
    case "bubbleCenterLemon":
    case "bubbleRight":
    case "bubbleRightGray":
    case "bubbleRightPink":
    case "bubbleRightBlue":
    case "bubbleRightMint":
    case "bubbleRightLavender":
    case "bubbleRightOrange":
    case "bubbleRightGreen":
    case "bubbleRightCream":
    case "bubbleRightNavy":
    case "bubbleRightRose":
    case "bubbleRightCoral":
    case "bubbleRightBeige":
    case "bubbleRightTeal":
    case "bubbleRightLemon":
    case "bubbleSquare":
    case "bubbleSquareGray":
    case "bubbleSquarePink":
    case "bubbleSquareBlue":
    case "bubbleSquareMint":
    case "bubbleSquareLavender":
    case "bubbleSquareOrange":
    case "bubbleSquareGreen":
    case "bubbleSquareCream":
    case "bubbleSquareNavy":
    case "bubbleSquareRose":
    case "bubbleSquareCoral":
    case "bubbleSquareBeige":
    case "bubbleSquareTeal":
    case "bubbleSquareLemon":
    case "bubbleSquareCenter":
    case "bubbleSquareCenterGray":
    case "bubbleSquareCenterPink":
    case "bubbleSquareCenterBlue":
    case "bubbleSquareCenterMint":
    case "bubbleSquareCenterLavender":
    case "bubbleSquareCenterOrange":
    case "bubbleSquareCenterGreen":
    case "bubbleSquareCenterCream":
    case "bubbleSquareCenterNavy":
    case "bubbleSquareCenterRose":
    case "bubbleSquareCenterCoral":
    case "bubbleSquareCenterBeige":
    case "bubbleSquareCenterTeal":
    case "bubbleSquareCenterLemon":
    case "bubbleSquareRight":
    case "bubbleSquareRightGray":
    case "bubbleSquareRightPink":
    case "bubbleSquareRightBlue":
    case "bubbleSquareRightMint":
    case "bubbleSquareRightLavender":
    case "bubbleSquareRightOrange":
    case "bubbleSquareRightGreen":
    case "bubbleSquareRightCream":
    case "bubbleSquareRightNavy":
    case "bubbleSquareRightRose":
    case "bubbleSquareRightCoral":
    case "bubbleSquareRightBeige":
    case "bubbleSquareRightTeal":
    case "bubbleSquareRightLemon":
      return 36;
    case "note":
    case "noteBlue":
    case "notePink":
    case "noteMint":
    case "noteLavender":
    case "noteOrange":
    case "noteGray":
    case "noteBeige":
    case "noteTorn":
    case "noteTornGray":
    case "noteTornPink":
    case "noteTornBlue":
    case "noteTornMint":
    case "noteTornLavender":
    case "noteTornOrange":
    case "noteTornCream":
    case "noteTornBeige":
    case "noteTornYellow":
    case "noteTornGold":
    case "noteTornRough":
    case "noteTornRoughGray":
    case "noteTornRoughPink":
    case "noteTornRoughBlue":
    case "noteTornRoughMint":
    case "noteTornRoughLavender":
    case "noteTornRoughOrange":
    case "noteTornRoughCream":
    case "noteTornRoughBeige":
    case "noteTornRoughYellow":
    case "noteTornRoughGold":
    case "noteTornSoft":
    case "noteTornSoftGray":
    case "noteTornSoftPink":
    case "noteTornSoftBlue":
    case "noteTornSoftMint":
    case "noteTornSoftLavender":
    case "noteTornSoftOrange":
    case "noteTornSoftCream":
    case "noteTornSoftBeige":
    case "noteTornSoftYellow":
    case "noteTornSoftGold":
    case "noteGrid":
    case "noteGridBlue":
    case "noteGridPink":
    case "noteGridMint":
    case "noteGridLavender":
    case "noteGridOrange":
    case "noteGridGray":
    case "noteGold":
    case "noteCream":
      return 36;
    case "tape":
    case "tapeYellow":
    case "tapePink":
    case "tapeMint":
    case "tapeLavender":
    case "tapeGray":
    case "tapeTorn":
    case "tapeTornGray":
    case "tapeTornPink":
    case "tapeTornMint":
    case "tapeTornLavender":
    case "tapeTornYellow":
    case "tapeTornRough":
    case "tapeTornRoughGray":
    case "tapeTornRoughPink":
    case "tapeTornRoughMint":
    case "tapeTornRoughLavender":
    case "tapeTornRoughYellow":
    case "tapeTornSoft":
    case "tapeTornSoftGray":
    case "tapeTornSoftPink":
    case "tapeTornSoftMint":
    case "tapeTornSoftLavender":
    case "tapeTornSoftYellow":
    case "tapeTornSolid":
    case "tapeTornSolidGray":
    case "tapeTornSolidPink":
    case "tapeTornSolidBlue":
    case "tapeTornSolidMint":
    case "tapeTornSolidLavender":
    case "tapeTornSolidOrange":
    case "tapeTornSolidGreen":
    case "tapeDots":
    case "tapeDotsPink":
    case "tapeDotsMint":
    case "tapeDotsLavender":
    case "tapeDotsOrange":
    case "tapeDotsGray":
    case "tapeKraft":
    case "tapeGold":
    case "tapeSolidWhite":
    case "tapeSolidGray":
    case "tapeSolidPink":
    case "tapeSolidBlue":
    case "tapeSolidMint":
    case "tapeSolidLavender":
    case "tapeSolidOrange":
    case "tapeSolidGreen":
    case "tapeDouble":
    case "tapeDoublePink":
    case "tapeDoubleMint":
    case "tapeDoubleBlue":
    case "tapeDoubleLavender":
    case "tapeDoubleGray":
      return 36;
    case "calligraphy":
    case "highlightYellow":
    case "highlightGreen":
    case "highlightPink":
    case "stampRed":
    case "stampBlue":
    case "quote":
    case "chalkboard":
    case "caption":
      return 32;
    case "noteGrid":
      return 36;
    case "sticker":
      return 32;
    default:
      return 24;
  }
}

/// 기본 텍스트와 동일한 레이아웃(maxWidth)을 쓰므로, 스타일은 텍스트 영역 + 패딩만 넉넉히 줌. 세로는 line height·다음줄까지 여유 확보.
const double _styleVerticalSafety = 20.0;

/// 기본은 좌우 패딩 4씩이라 콘텐츠 폭이 textSize.width+12. 스타일도 같은 콘텐츠 폭 쓰도록 가로 여유.
const double _styleHorizontalExtra = 12.0;

/// 찢어진 메모지(아래 톱니) step/amp – 키에 따라 일반(8, 2.5), 거친(12, 4), 부드러운(5, 1.2)
(double, double) _tornEdgeParamsImpl(String key) {
  if (key.contains('Rough')) return (12.0, 4.0);
  if (key.contains('Soft')) return (5.0, 1.2);
  return (8.0, 2.5);
}

/// 찢어진 테이프 키 → 단색 테이프 키 (tapeTorn*/tapeTornSolid* → tapeSolid*)
String? _tapeTornToSolidKeyImpl(String? key) {
  if (key == null) return 'tapeSolidWhite';
  final k = key
      .replaceFirst('tapeTornRough', 'tapeTorn')
      .replaceFirst('tapeTornSoft', 'tapeTorn');
  if (k.startsWith('tapeTornSolid')) {
    final resolved = k.replaceFirst('tapeTornSolid', 'tapeSolid');
    return resolved.isEmpty
        ? 'tapeSolidWhite'
        : (resolved == 'tapeSolid' ? 'tapeSolidWhite' : resolved);
  }
  switch (k) {
    case 'tapeTorn':
      return 'tapeSolidWhite';
    case 'tapeTornGray':
      return 'tapeSolidGray';
    case 'tapeTornPink':
      return 'tapeSolidPink';
    case 'tapeTornMint':
      return 'tapeSolidMint';
    case 'tapeTornLavender':
      return 'tapeSolidLavender';
    case 'tapeTornYellow':
      return 'tapeSolidOrange';
    default:
      return 'tapeSolidWhite';
  }
}

Size _calculateStyleSizeImpl(
  String type,
  LayerModel layer,
  TextPainter painter,
) {
  final textSize = painter.size;
  final hPad = _styleHorizontalPaddingImpl(type);
  final totalWidth = textSize.width + hPad + _styleHorizontalExtra;

  switch (type) {
    case "round":
    case "roundGray":
    case "roundPink":
    case "roundBlue":
    case "roundMint":
    case "roundLavender":
    case "roundOrange":
    case "roundGreen":
    case "roundCream":
    case "roundNavy":
    case "roundRose":
    case "roundCoral":
    case "roundBeige":
    case "roundTeal":
    case "roundLemon":
    case "square":
    case "squareGray":
    case "squarePink":
    case "squareBlue":
    case "squareMint":
    case "squareLavender":
    case "squareOrange":
    case "squareGreen":
    case "squareCream":
    case "squareNavy":
    case "squareRose":
    case "squareCoral":
    case "squareBeige":
    case "squareTeal":
    case "squareLemon":
    case "roundSoft":
    case "roundSoftGray":
    case "roundSoftPink":
    case "roundSoftBlue":
    case "roundSoftMint":
    case "roundSoftLavender":
    case "roundSoftOrange":
    case "roundSoftGreen":
    case "roundSoftCream":
    case "roundSoftNavy":
    case "roundSoftRose":
    case "roundSoftCoral":
    case "roundSoftBeige":
    case "roundSoftTeal":
    case "roundSoftLemon":
    case "softPill2":
    case "softPill2Gray":
    case "softPill2Pink":
    case "softPill2Blue":
    case "softPill2Mint":
    case "softPill2Lavender":
    case "softPill2Orange":
    case "softPill2Green":
    case "softPill2Cream":
    case "softPill2Navy":
    case "softPill2Rose":
    case "softPill2Coral":
    case "softPill2Beige":
    case "softPill2Teal":
    case "softPill2Lemon":
      return Size(totalWidth, textSize.height + 16 + _styleVerticalSafety);
    // 중앙 찢어진 스크래치 레이아웃 (고정 크기)
    case "tag":
    case "tagGray":
    case "tagPink":
    case "tagBlue":
    case "tagMint":
    case "tagLavender":
    case "tagOrange":
    case "tagGreen":
    case "tagRed":
    case "label":
    case "labelGray":
    case "labelPink":
    case "labelBlue":
    case "labelMint":
    case "labelLavender":
    case "labelOrange":
    case "labelGreen":
    case "labelWhite":
    case "labelCream":
      return Size(totalWidth, textSize.height + 12 + _styleVerticalSafety);
    case "labelSolid":
    case "labelSolidGray":
    case "labelSolidPink":
    case "labelSolidBlue":
    case "labelSolidMint":
    case "labelSolidRed":
    case "labelSolidGreen":
    case "labelSolidOrange":
    case "labelSolidLavender":
    case "labelSolidCream":
    case "labelOutline":
    case "labelGold":
    case "labelNeon":
    case "labelRose":
      return Size(totalWidth, textSize.height + 16 + _styleVerticalSafety);
    case "bubble":
    case "bubbleGray":
    case "bubblePink":
    case "bubbleBlue":
    case "bubbleMint":
    case "bubbleLavender":
    case "bubbleOrange":
    case "bubbleGreen":
    case "bubbleCream":
    case "bubbleNavy":
    case "bubbleRose":
    case "bubbleCoral":
    case "bubbleBeige":
    case "bubbleTeal":
    case "bubbleLemon":
    case "bubbleCenter":
    case "bubbleCenterGray":
    case "bubbleCenterPink":
    case "bubbleCenterBlue":
    case "bubbleCenterMint":
    case "bubbleCenterLavender":
    case "bubbleCenterOrange":
    case "bubbleCenterGreen":
    case "bubbleCenterCream":
    case "bubbleCenterNavy":
    case "bubbleCenterRose":
    case "bubbleCenterCoral":
    case "bubbleCenterBeige":
    case "bubbleCenterTeal":
    case "bubbleCenterLemon":
    case "bubbleRight":
    case "bubbleRightGray":
    case "bubbleRightPink":
    case "bubbleRightBlue":
    case "bubbleRightMint":
    case "bubbleRightLavender":
    case "bubbleRightOrange":
    case "bubbleRightGreen":
    case "bubbleRightCream":
    case "bubbleRightNavy":
    case "bubbleRightRose":
    case "bubbleRightCoral":
    case "bubbleRightBeige":
    case "bubbleRightTeal":
    case "bubbleRightLemon":
    case "bubbleSquare":
    case "bubbleSquareGray":
    case "bubbleSquarePink":
    case "bubbleSquareBlue":
    case "bubbleSquareMint":
    case "bubbleSquareLavender":
    case "bubbleSquareOrange":
    case "bubbleSquareGreen":
    case "bubbleSquareCream":
    case "bubbleSquareNavy":
    case "bubbleSquareRose":
    case "bubbleSquareCoral":
    case "bubbleSquareBeige":
    case "bubbleSquareTeal":
    case "bubbleSquareLemon":
    case "bubbleSquareCenter":
    case "bubbleSquareCenterGray":
    case "bubbleSquareCenterPink":
    case "bubbleSquareCenterBlue":
    case "bubbleSquareCenterMint":
    case "bubbleSquareCenterLavender":
    case "bubbleSquareCenterOrange":
    case "bubbleSquareCenterGreen":
    case "bubbleSquareCenterCream":
    case "bubbleSquareCenterNavy":
    case "bubbleSquareCenterRose":
    case "bubbleSquareCenterCoral":
    case "bubbleSquareCenterBeige":
    case "bubbleSquareCenterTeal":
    case "bubbleSquareCenterLemon":
    case "bubbleSquareRight":
    case "bubbleSquareRightGray":
    case "bubbleSquareRightPink":
    case "bubbleSquareRightBlue":
    case "bubbleSquareRightMint":
    case "bubbleSquareRightLavender":
    case "bubbleSquareRightOrange":
    case "bubbleSquareRightGreen":
    case "bubbleSquareRightCream":
    case "bubbleSquareRightNavy":
    case "bubbleSquareRightRose":
      return Size(totalWidth, textSize.height + 32 + _styleVerticalSafety);
    case "note":
    case "noteBlue":
    case "notePink":
    case "noteMint":
    case "noteLavender":
    case "noteOrange":
    case "noteGray":
    case "noteBeige":
    case "noteTorn":
    case "noteTornGray":
    case "noteTornPink":
    case "noteTornBlue":
    case "noteTornMint":
    case "noteTornLavender":
    case "noteTornOrange":
    case "noteTornCream":
    case "noteTornBeige":
    case "noteTornYellow":
    case "noteTornGold":
    case "noteTornRough":
    case "noteTornRoughGray":
    case "noteTornRoughPink":
    case "noteTornRoughBlue":
    case "noteTornRoughMint":
    case "noteTornRoughLavender":
    case "noteTornRoughOrange":
    case "noteTornRoughCream":
    case "noteTornRoughBeige":
    case "noteTornRoughYellow":
    case "noteTornRoughGold":
    case "noteTornSoft":
    case "noteTornSoftGray":
    case "noteTornSoftPink":
    case "noteTornSoftBlue":
    case "noteTornSoftMint":
    case "noteTornSoftLavender":
    case "noteTornSoftOrange":
    case "noteTornSoftCream":
    case "noteTornSoftBeige":
    case "noteTornSoftYellow":
    case "noteTornSoftGold":
    case "noteGrid":
    case "noteGridBlue":
    case "noteGridPink":
    case "noteGridMint":
    case "noteGridLavender":
    case "noteGridOrange":
    case "noteGridGray":
      return Size(
        (totalWidth / 12).ceil() * 12.0,
        ((textSize.height + 24) / 12).ceil() * 12.0,
      );
    case "noteGold":
    case "noteCream":
      return Size(totalWidth, textSize.height + 32);
    case "tape":
    case "tapeYellow":
    case "tapePink":
    case "tapeMint":
    case "tapeLavender":
    case "tapeGray":
    case "tapeTorn":
    case "tapeTornGray":
    case "tapeTornPink":
    case "tapeTornMint":
    case "tapeTornLavender":
    case "tapeTornYellow":
    case "tapeTornRough":
    case "tapeTornRoughGray":
    case "tapeTornRoughPink":
    case "tapeTornRoughMint":
    case "tapeTornRoughLavender":
    case "tapeTornRoughYellow":
    case "tapeTornSoft":
    case "tapeTornSoftGray":
    case "tapeTornSoftPink":
    case "tapeTornSoftMint":
    case "tapeTornSoftLavender":
    case "tapeTornSoftYellow":
    case "tapeTornSolid":
    case "tapeTornSolidGray":
    case "tapeTornSolidPink":
    case "tapeTornSolidBlue":
    case "tapeTornSolidMint":
    case "tapeTornSolidLavender":
    case "tapeTornSolidOrange":
    case "tapeTornSolidGreen":
    case "tapeDots":
    case "tapeDotsPink":
    case "tapeDotsMint":
    case "tapeDotsLavender":
    case "tapeDotsOrange":
    case "tapeDotsGray":
    case "tapeKraft":
    case "tapeGold":
    case "tapeSolidWhite":
    case "tapeSolidGray":
    case "tapeSolidPink":
    case "tapeSolidBlue":
    case "tapeSolidMint":
    case "tapeSolidLavender":
    case "tapeSolidOrange":
    case "tapeSolidGreen":
    case "tapeDouble":
    case "tapeDoublePink":
    case "tapeDoubleMint":
    case "tapeDoubleBlue":
    case "tapeDoubleLavender":
    case "tapeDoubleGray":
      return Size(totalWidth, textSize.height + 0 + _styleVerticalSafety);
    case "calligraphy":
    case "highlightYellow":
    case "highlightGreen":
    case "highlightPink":
    case "stampRed":
    case "stampBlue":
    case "quote":
    case "chalkboard":
    case "caption":
      return Size(totalWidth, textSize.height + 16 + _styleVerticalSafety);
    case "sticker":
      return Size(totalWidth, textSize.height + 20 + _styleVerticalSafety);
    default:
      return Size(textSize.width + 20, textSize.height + 10);
  }
}
