-- Align Supabase schema with Snapfit-BackEnd entity/service model.
-- This migration fills gaps found after inspecting Snapfit-BackEnd.

-- Templates: preserve backend newUntil behavior for "new" badges.
alter table public.templates
  add column if not exists new_until timestamptz;

-- Album pages: backend stores page_number plus several URL variants.
alter table public.album_pages
  add column if not exists page_number integer,
  add column if not exists image_url text,
  add column if not exists original_url text,
  add column if not exists preview_url text;

update public.album_pages
set page_number = page_index + 1
where page_number is null;

alter table public.album_pages
  alter column page_number set default 1;

create index if not exists album_pages_album_page_number_idx
on public.album_pages(album_id, page_number);

-- Album members: backend keeps pending invites on album_member as well.
alter table public.album_members
  add column if not exists id bigint generated by default as identity,
  add column if not exists status text not null default 'ACCEPTED',
  add column if not exists invited_by uuid references auth.users(id) on delete set null,
  add column if not exists invite_token text;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'album_members_role_check_v2'
      and conrelid = 'public.album_members'::regclass
  ) then
    alter table public.album_members
      add constraint album_members_role_check_v2
      check (role in ('OWNER','EDITOR','VIEWER'));
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'album_members_status_check'
      and conrelid = 'public.album_members'::regclass
  ) then
    alter table public.album_members
      add constraint album_members_status_check
      check (status in ('PENDING','ACCEPTED'));
  end if;
end $$;

create unique index if not exists album_members_invite_token_key
on public.album_members(invite_token)
where invite_token is not null;

-- Billing orders: separate subscription-payment state from print/order state.
create table if not exists public.billing_orders (
  id bigint generated by default as identity primary key,
  order_id text not null unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  plan_code text not null references public.billing_plans(plan_code),
  provider text not null,
  status text not null default 'READY' check (status in ('READY','APPROVED','FAILED','CANCELED')),
  amount integer not null check (amount >= 0),
  currency text not null default 'KRW',
  checkout_url text,
  reserve_id text,
  transaction_id text,
  fail_reason text,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger billing_orders_set_updated_at
before update on public.billing_orders
for each row execute function public.set_updated_at();

create index if not exists billing_orders_user_idx on public.billing_orders(user_id, created_at desc);
create index if not exists billing_orders_status_idx on public.billing_orders(status);

alter table public.billing_orders enable row level security;

create policy "billing_orders_own_or_admin_read"
on public.billing_orders for select
to authenticated
using (user_id = auth.uid() or public.is_admin());

create policy "billing_orders_service_admin_write"
on public.billing_orders for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Subscription entity parity.
alter table public.subscriptions
  add column if not exists last_order_id text;

-- Support inquiries: backend admin CS fields.
alter table public.support_inquiries
  add column if not exists category text not null default 'GENERAL',
  add column if not exists resolved_at timestamptz,
  add column if not exists resolved_by text;

create index if not exists support_inquiries_status_idx on public.support_inquiries(status);
create index if not exists support_inquiries_updated_idx on public.support_inquiries(updated_at desc);

-- Notification broadcast/read model from backend. Keep existing per-user notifications
-- table for simple user-specific messages, but add inbox/read for topic broadcast.
create table if not exists public.notification_inbox (
  id bigint generated by default as identity primary key,
  type text not null,
  title text not null,
  body text not null,
  target_topic text,
  deeplink text,
  payload_json jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.notification_reads (
  notification_id bigint not null references public.notification_inbox(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  read_at timestamptz not null default now(),
  primary key (notification_id, user_id)
);

alter table public.notification_inbox enable row level security;
alter table public.notification_reads enable row level security;

create policy "notification_inbox_authenticated_read"
on public.notification_inbox for select
to authenticated
using (true);

create policy "notification_inbox_admin_write"
on public.notification_inbox for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "notification_reads_own_read"
on public.notification_reads for select
to authenticated
using (user_id = auth.uid() or public.is_admin());

create policy "notification_reads_insert_own"
on public.notification_reads for insert
to authenticated
with check (user_id = auth.uid());

create policy "notification_reads_delete_own_or_admin"
on public.notification_reads for delete
to authenticated
using (user_id = auth.uid() or public.is_admin());

-- Order support: explicit quote/print package metadata is already on orders.
-- Add backend indexes for user/status/admin queries.
create index if not exists orders_user_created_idx on public.orders(user_id, created_at desc);
create index if not exists orders_status_idx on public.orders(status);
create index if not exists orders_updated_idx on public.orders(updated_at desc);
