-- Seed canonical store templates.
-- The IDs here are the source-of-truth identifiers referenced by the
-- client-side handoff JSON files. Inserting with explicit IDs is safe
-- because the table uses GENERATED BY DEFAULT AS IDENTITY.
--
-- After the insert we advance the sequence past the highest positive ID
-- so that future auto-generated rows never collide.

INSERT INTO public.templates (
  id,
  title,
  sub_title,
  description,
  cover_image_url,
  page_count,
  category,
  tags,
  weekly_score,
  is_new,
  is_best,
  is_premium,
  is_active
) VALUES
  (
    46,
    '제주의 기록',
    'signature jeju route magazine',
    '제주도 여행의 소중한 순간들을 담은 포토북 템플릿',
    'asset:assets/templates/jeju_travel/images/approved_stock/cover.png',
    12,
    '여행',
    ARRAY['여행', '제주도', '포토북'],
    80, false, true, false, true
  ),
  (
    48,
    '가족의 주말',
    'warm family weekend',
    '가족과 함께한 따뜻한 주말 이야기를 담은 포토북',
    'asset:assets/templates/family_weekend/images/sources/cover.png',
    12,
    '가족',
    ARRAY['가족', '주말', '포토북'],
    70, false, false, false, true
  ),
  (
    49,
    '우리의 기념일',
    'anniversary love notes',
    '커플의 소중한 기념일을 기록하는 포토북 템플릿',
    'asset:assets/templates/anniversary_days/images/sources/cover.png',
    12,
    '기념일',
    ARRAY['기념일', '커플', '100일'],
    75, false, true, false, true
  ),
  (
    50,
    'Wedding Editorial',
    'modern wedding book',
    '모던하고 세련된 웨딩 에디토리얼 포토북',
    'asset:assets/templates/wedding_editorial/images/approved_stock/cover.png',
    12,
    '웨딩',
    ARRAY['웨딩', '에디토리얼', '브라운'],
    90, false, true, true, true
  ),
  (
    51,
    'Scrapbook',
    'paper archive kit',
    '스크랩북 스타일의 콜라주 포토북 템플릿',
    'asset:assets/templates/scrapbook/images/sources/cover.png',
    12,
    '스크랩북',
    ARRAY['스크랩북', '콜라주', '다이어리'],
    65, false, false, false, true
  ),
  (
    -1115056,
    'SAVE THE DATE',
    'wedding invitation album',
    '웨딩 세이브더데이트 청첩장 포토북 템플릿',
    'asset:assets/templates/save_the_date/images/approved_stock/cover.png',
    12,
    '웨딩',
    ARRAY['웨딩', '세이브더데이트', '청첩장'],
    95, true, true, true, true
  ),
  (
    -8006,
    '화이트 에디토리얼',
    'white space magazine',
    '미니멀한 화이트 에디토리얼 스타일 포토북',
    'asset:assets/templates/minimal_editorial/images/generated/cover.png',
    12,
    '에디토리얼',
    ARRAY['미니멀', '에디토리얼', '화이트'],
    60, false, false, false, true
  ),
  (
    -8007,
    '필름 다이어리',
    'warm film diary',
    '필름 카메라 감성의 여행 다이어리 포토북',
    'asset:assets/templates/film_diary/images/generated/cover.png',
    12,
    '다이어리',
    ARRAY['필름', '다이어리', '여행'],
    55, false, false, false, true
  ),
  (
    -8008,
    '소프트 베이비북',
    'baby milestone book',
    '아기의 성장 과정을 담은 파스텔 톤 베이비북',
    'asset:assets/templates/soft_babybook/images/approved_stock/cover.png',
    12,
    '가족',
    ARRAY['베이비', '가족', '파스텔'],
    68, true, false, false, true
  )
ON CONFLICT (id) DO NOTHING;

-- Advance the identity sequence so future auto-generated IDs start
-- above 100 (safely beyond all hardcoded positive IDs).
SELECT setval(
  pg_get_serial_sequence('public.templates', 'id'),
  GREATEST(100, (SELECT COALESCE(MAX(id), 0) FROM public.templates WHERE id > 0))
);
