-- Store in-app purchase direction for mobile billing.
-- Google Play Billing / Apple StoreKit receipts are verified server-side and
-- then materialized into subscriptions.

create table if not exists public.store_purchases (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  platform text not null check (platform in ('GOOGLE_PLAY','APP_STORE')),
  product_id text not null,
  transaction_id text not null,
  original_transaction_id text,
  purchase_token text,
  receipt_hash text,
  status text not null default 'PENDING' check (status in ('PENDING','VERIFIED','FAILED','REFUNDED','EXPIRED')),
  plan_code text not null default 'SNAPFIT_PRO_MONTHLY' references public.billing_plans(plan_code),
  purchased_at timestamptz,
  expires_at timestamptz,
  raw_response jsonb,
  fail_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (platform, transaction_id)
);

create trigger store_purchases_set_updated_at
before update on public.store_purchases
for each row execute function public.set_updated_at();

create index if not exists store_purchases_user_idx on public.store_purchases(user_id, created_at desc);
create index if not exists store_purchases_status_idx on public.store_purchases(status);

alter table public.store_purchases enable row level security;

create policy "store_purchases_own_or_admin_read"
on public.store_purchases for select
to authenticated
using (user_id = auth.uid() or public.is_admin());

create policy "store_purchases_insert_own_pending"
on public.store_purchases for insert
to authenticated
with check (user_id = auth.uid() and status = 'PENDING');

create policy "store_purchases_admin_write"
on public.store_purchases for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Keep legacy billing providers unavailable by default; mobile payments should
-- use store receipt verification instead of Toss/NaverPay external checkout.
update public.billing_plans
set provider = 'APP_STORE_GOOGLE_PLAY'
where plan_code = 'SNAPFIT_PRO_MONTHLY';
