-- SnapFit Supabase baseline schema
-- Phase 1 migration for replacing the existing /api REST backend.

create extension if not exists pgcrypto with schema extensions;

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.is_admin()
returns boolean
language sql stable security definer set search_path = public as $$
  select coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false);
$$;

-- Profiles mirror auth.users and replace the current integer UserInfo model.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  name text not null default '',
  avatar_url text,
  provider text not null default 'supabase',
  terms_version text,
  privacy_version text,
  marketing_opt_in boolean not null default false,
  consented_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger profiles_set_updated_at before update on public.profiles for each row execute function public.set_updated_at();
alter table public.profiles enable row level security;
create policy "profiles_select_own_or_admin" on public.profiles for select to authenticated using (id = auth.uid() or public.is_admin());
create policy "profiles_insert_own" on public.profiles for insert to authenticated with check (id = auth.uid());
create policy "profiles_update_own_or_admin" on public.profiles for update to authenticated using (id = auth.uid() or public.is_admin()) with check (id = auth.uid() or public.is_admin());

create table if not exists public.templates (
  id bigint generated by default as identity primary key,
  title text not null,
  sub_title text,
  description text,
  cover_image_url text not null default '',
  preview_images text[] not null default '{}',
  page_count integer not null default 0 check (page_count >= 0),
  category text,
  tags text[] not null default '{}',
  weekly_score integer not null default 0,
  is_new boolean not null default false,
  is_best boolean not null default false,
  is_premium boolean not null default false,
  is_active boolean not null default true,
  template_json jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger templates_set_updated_at before update on public.templates for each row execute function public.set_updated_at();
create index if not exists templates_active_score_idx on public.templates (is_active, weekly_score desc, created_at desc);
alter table public.templates enable row level security;
create policy "templates_public_read_active" on public.templates for select to anon, authenticated using (is_active = true or public.is_admin());
create policy "templates_admin_write" on public.templates for all to authenticated using (public.is_admin()) with check (public.is_admin());

create table if not exists public.template_likes (
  template_id bigint not null references public.templates(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (template_id, user_id)
);
alter table public.template_likes enable row level security;
create policy "template_likes_read_own_or_admin" on public.template_likes for select to authenticated using (user_id = auth.uid() or public.is_admin());
create policy "template_likes_insert_own" on public.template_likes for insert to authenticated with check (user_id = auth.uid());
create policy "template_likes_delete_own" on public.template_likes for delete to authenticated using (user_id = auth.uid());

create table if not exists public.albums (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  title text not null default '',
  ratio text not null default '',
  cover_layers_json text not null default '',
  cover_image_url text,
  cover_thumbnail_url text,
  cover_original_url text,
  cover_preview_url text,
  cover_theme text,
  total_pages integer not null default 0,
  target_pages integer not null default 0,
  sort_order integer not null default 0,
  locked_by text,
  locked_by_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger albums_set_updated_at before update on public.albums for each row execute function public.set_updated_at();

create table if not exists public.album_pages (
  id bigint generated by default as identity primary key,
  album_id bigint not null references public.albums(id) on delete cascade,
  page_index integer not null default 0,
  layers_json jsonb not null default '[]'::jsonb,
  thumbnail_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (album_id, page_index)
);
create trigger album_pages_set_updated_at before update on public.album_pages for each row execute function public.set_updated_at();

create table if not exists public.album_members (
  album_id bigint not null references public.albums(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'EDITOR' check (role in ('OWNER','EDITOR','VIEWER')),
  created_at timestamptz not null default now(),
  primary key (album_id, user_id)
);

create table if not exists public.album_invites (
  token text primary key default encode(extensions.gen_random_bytes(24), 'hex'),
  album_id bigint not null references public.albums(id) on delete cascade,
  created_by uuid references auth.users(id) on delete set null,
  role text not null default 'EDITOR' check (role in ('EDITOR','VIEWER')),
  expires_at timestamptz,
  accepted_by uuid references auth.users(id) on delete set null,
  accepted_at timestamptz,
  created_at timestamptz not null default now()
);

create or replace function public.can_access_album(target_album_id bigint)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.albums a where a.id = target_album_id and (a.owner_id = auth.uid() or public.is_admin()))
      or exists (select 1 from public.album_members m where m.album_id = target_album_id and m.user_id = auth.uid());
$$;

alter table public.albums enable row level security;
alter table public.album_pages enable row level security;
alter table public.album_members enable row level security;
alter table public.album_invites enable row level security;
create policy "albums_read_member_or_admin" on public.albums for select to authenticated using (public.can_access_album(id));
create policy "albums_insert_own" on public.albums for insert to authenticated with check (owner_id = auth.uid());
create policy "albums_update_member_or_admin" on public.albums for update to authenticated using (public.can_access_album(id)) with check (public.can_access_album(id));
create policy "albums_delete_owner_or_admin" on public.albums for delete to authenticated using (owner_id = auth.uid() or public.is_admin());
create policy "album_pages_member_crud" on public.album_pages for all to authenticated using (public.can_access_album(album_id)) with check (public.can_access_album(album_id));
create policy "album_members_read_member_or_admin" on public.album_members for select to authenticated using (public.can_access_album(album_id));
create policy "album_members_owner_write" on public.album_members for all to authenticated using (exists (select 1 from public.albums a where a.id = album_id and (a.owner_id = auth.uid() or public.is_admin()))) with check (exists (select 1 from public.albums a where a.id = album_id and (a.owner_id = auth.uid() or public.is_admin())));
create policy "album_invites_owner_crud" on public.album_invites for all to authenticated using (exists (select 1 from public.albums a where a.id = album_id and (a.owner_id = auth.uid() or public.is_admin()))) with check (exists (select 1 from public.albums a where a.id = album_id and (a.owner_id = auth.uid() or public.is_admin())));

create table if not exists public.billing_plans (
  plan_code text primary key,
  title text not null,
  amount integer not null check (amount >= 0),
  currency text not null default 'KRW',
  period_days integer not null default 30,
  provider text not null default 'NAVERPAY',
  soft_limit_bytes bigint not null default 0,
  hard_limit_bytes bigint not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger billing_plans_set_updated_at before update on public.billing_plans for each row execute function public.set_updated_at();
insert into public.billing_plans(plan_code,title,amount,currency,period_days,provider,soft_limit_bytes,hard_limit_bytes) values
  ('FREE','SnapFit Free',0,'KRW',0,'NONE',104857600,157286400),
  ('SNAPFIT_PRO_MONTHLY','SnapFit Pro 월간 구독',4900,'KRW',30,'NAVERPAY',2147483648,3221225472)
on conflict (plan_code) do nothing;

create table if not exists public.subscriptions (
  user_id uuid primary key references auth.users(id) on delete cascade,
  plan_code text references public.billing_plans(plan_code),
  status text not null default 'INACTIVE',
  started_at timestamptz,
  expires_at timestamptz,
  next_billing_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger subscriptions_set_updated_at before update on public.subscriptions for each row execute function public.set_updated_at();

create table if not exists public.storage_quotas (
  user_id uuid primary key references auth.users(id) on delete cascade,
  plan_code text not null default 'FREE' references public.billing_plans(plan_code),
  used_bytes bigint not null default 0,
  soft_limit_bytes bigint not null default 104857600,
  hard_limit_bytes bigint not null default 157286400,
  measured_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger storage_quotas_set_updated_at before update on public.storage_quotas for each row execute function public.set_updated_at();

create table if not exists public.orders (
  order_id text primary key default ('ord_' || encode(extensions.gen_random_bytes(12), 'hex')),
  user_id uuid not null references auth.users(id) on delete cascade,
  album_id bigint references public.albums(id) on delete set null,
  title text not null default '주문',
  amount integer not null default 0,
  page_count integer,
  status text not null default 'PAYMENT_PENDING',
  payment_method text,
  recipient_name text,
  recipient_phone text,
  zip_code text,
  address_line1 text,
  address_line2 text,
  delivery_memo text,
  courier text,
  tracking_number text,
  print_vendor text,
  print_vendor_order_id text,
  print_package_json_url text,
  print_file_pdf_url text,
  print_file_zip_url text,
  print_asset_count integer,
  ordered_at timestamptz not null default now(),
  payment_confirmed_at timestamptz,
  print_package_generated_at timestamptz,
  print_submitted_at timestamptz,
  shipped_at timestamptz,
  delivered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger orders_set_updated_at before update on public.orders for each row execute function public.set_updated_at();

alter table public.billing_plans enable row level security;
alter table public.subscriptions enable row level security;
alter table public.storage_quotas enable row level security;
alter table public.orders enable row level security;
create policy "billing_plans_public_read_active" on public.billing_plans for select to anon, authenticated using (is_active = true or public.is_admin());
create policy "billing_plans_admin_write" on public.billing_plans for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "subscriptions_own_or_admin_read" on public.subscriptions for select to authenticated using (user_id = auth.uid() or public.is_admin());
create policy "subscriptions_admin_write" on public.subscriptions for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "storage_quotas_own_or_admin_read" on public.storage_quotas for select to authenticated using (user_id = auth.uid() or public.is_admin());
create policy "storage_quotas_admin_write" on public.storage_quotas for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "orders_own_or_admin_read" on public.orders for select to authenticated using (user_id = auth.uid() or public.is_admin());
create policy "orders_insert_own" on public.orders for insert to authenticated with check (user_id = auth.uid());
create policy "orders_owner_limited_update" on public.orders for update to authenticated using (user_id = auth.uid() or public.is_admin()) with check (user_id = auth.uid() or public.is_admin());

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null default 'general',
  title text not null,
  body text not null default '',
  deeplink text,
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create table if not exists public.support_inquiries (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  email text,
  subject text not null,
  message text not null,
  status text not null default 'OPEN',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger support_inquiries_set_updated_at before update on public.support_inquiries for each row execute function public.set_updated_at();
alter table public.notifications enable row level security;
alter table public.support_inquiries enable row level security;
create policy "notifications_own_or_admin_read" on public.notifications for select to authenticated using (user_id = auth.uid() or public.is_admin());
create policy "notifications_own_mark_read" on public.notifications for update to authenticated using (user_id = auth.uid() or public.is_admin()) with check (user_id = auth.uid() or public.is_admin());
create policy "notifications_admin_insert" on public.notifications for insert to authenticated with check (public.is_admin());
create policy "support_insert_authenticated" on public.support_inquiries for insert to authenticated with check (user_id = auth.uid() or user_id is null);
create policy "support_read_own_or_admin" on public.support_inquiries for select to authenticated using (user_id = auth.uid() or public.is_admin());
create policy "support_admin_update" on public.support_inquiries for update to authenticated using (public.is_admin()) with check (public.is_admin());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types) values
  ('avatars', 'avatars', true, 2097152, array['image/jpeg','image/png','image/webp']),
  ('album-assets', 'album-assets', false, 52428800, array['image/jpeg','image/png','image/webp','application/pdf','application/zip']),
  ('template-assets', 'template-assets', true, 52428800, array['image/jpeg','image/png','image/webp','application/json'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

create policy "avatars_public_read" on storage.objects for select to anon, authenticated using (bucket_id = 'avatars');
create policy "avatars_own_insert" on storage.objects for insert to authenticated with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "avatars_own_update" on storage.objects for update to authenticated using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text) with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "template_assets_public_read" on storage.objects for select to anon, authenticated using (bucket_id = 'template-assets');
create policy "template_assets_admin_write" on storage.objects for all to authenticated using (bucket_id = 'template-assets' and public.is_admin()) with check (bucket_id = 'template-assets' and public.is_admin());
