-- AI album draft point ledger and first-free usage tracking.
--
-- Policy intent:
-- - direct/manual album creation never touches points.
-- - AI album draft consumes points only after a reviewable draft succeeds.
-- - each user gets one successful AI draft free credit.
-- - failure states are not recorded here and must not mutate point balances.
-- - Flutter clients cannot directly change balances; they call the security-definer RPC.

create table if not exists public.point_wallets (
  user_id uuid primary key references auth.users(id) on delete cascade,
  balance integer not null default 0 check (balance >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists point_wallets_set_updated_at on public.point_wallets;
create trigger point_wallets_set_updated_at
before update on public.point_wallets
for each row execute function public.set_updated_at();

create table if not exists public.point_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount_delta integer not null,
  reason text not null check (
    reason in (
      'AI_ALBUM_DRAFT_FREE',
      'AI_ALBUM_DRAFT_CHARGE',
      'ADMIN_ADJUSTMENT',
      'POINT_PURCHASE'
    )
  ),
  idempotency_key text not null unique,
  related_entity_type text,
  related_entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists point_ledger_user_created_idx
on public.point_ledger(user_id, created_at desc);

create table if not exists public.ai_album_draft_usages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  draft_id text not null,
  point_cost integer not null default 300 check (point_cost >= 0),
  used_free_credit boolean not null default false,
  status text not null default 'SUCCEEDED' check (status in ('SUCCEEDED','VOIDED')),
  created_at timestamptz not null default now(),
  unique (user_id, draft_id)
);

create index if not exists ai_album_draft_usages_user_created_idx
on public.ai_album_draft_usages(user_id, created_at desc);

create table if not exists public.ai_album_free_draft_claims (
  user_id uuid primary key references auth.users(id) on delete cascade,
  draft_id text not null,
  claimed_at timestamptz not null default now()
);

alter table public.point_wallets enable row level security;
alter table public.point_ledger enable row level security;
alter table public.ai_album_draft_usages enable row level security;
alter table public.ai_album_free_draft_claims enable row level security;

drop policy if exists "point_wallets_own_or_admin_read" on public.point_wallets;
create policy "point_wallets_own_or_admin_read"
on public.point_wallets for select
to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists "point_wallets_admin_write" on public.point_wallets;
create policy "point_wallets_admin_write"
on public.point_wallets for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "point_ledger_own_or_admin_read" on public.point_ledger;
create policy "point_ledger_own_or_admin_read"
on public.point_ledger for select
to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists "point_ledger_admin_write" on public.point_ledger;
create policy "point_ledger_admin_write"
on public.point_ledger for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "ai_album_draft_usages_own_or_admin_read" on public.ai_album_draft_usages;
create policy "ai_album_draft_usages_own_or_admin_read"
on public.ai_album_draft_usages for select
to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists "ai_album_draft_usages_admin_write" on public.ai_album_draft_usages;
create policy "ai_album_draft_usages_admin_write"
on public.ai_album_draft_usages for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "ai_album_free_draft_claims_own_or_admin_read" on public.ai_album_free_draft_claims;
create policy "ai_album_free_draft_claims_own_or_admin_read"
on public.ai_album_free_draft_claims for select
to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists "ai_album_free_draft_claims_admin_write" on public.ai_album_free_draft_claims;
create policy "ai_album_free_draft_claims_admin_write"
on public.ai_album_free_draft_claims for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create or replace function public.record_ai_album_draft_success(
  p_draft_id text,
  p_point_cost integer default 300
)
returns table (
  used_free_credit boolean,
  charged_points integer,
  remaining_balance integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_existing public.ai_album_draft_usages%rowtype;
  v_wallet_balance integer;
  v_used_free boolean := false;
begin
  if v_user_id is null then
    raise exception 'record_ai_album_draft_success requires an authenticated user'
      using errcode = '28000';
  end if;

  if p_draft_id is null or btrim(p_draft_id) = '' then
    raise exception 'draft id is required'
      using errcode = '22023';
  end if;

  if p_point_cost is null or p_point_cost < 0 then
    raise exception 'point cost must be zero or positive'
      using errcode = '22023';
  end if;

  select *
  into v_existing
  from public.ai_album_draft_usages
  where user_id = v_user_id
    and draft_id = p_draft_id;

  if found then
    select coalesce(balance, 0)
    into v_wallet_balance
    from public.point_wallets
    where user_id = v_user_id;

    return query select
      v_existing.used_free_credit,
      case when v_existing.used_free_credit then 0 else v_existing.point_cost end,
      coalesce(v_wallet_balance, 0);
    return;
  end if;

  insert into public.point_wallets(user_id, balance)
  values (v_user_id, 0)
  on conflict (user_id) do nothing;

  v_used_free := not exists (
    select 1
    from public.ai_album_free_draft_claims
    where user_id = v_user_id
  );

  if v_used_free then
    insert into public.ai_album_free_draft_claims(user_id, draft_id)
    values (v_user_id, p_draft_id);

    insert into public.ai_album_draft_usages(
      user_id,
      draft_id,
      point_cost,
      used_free_credit
    ) values (
      v_user_id,
      p_draft_id,
      0,
      true
    );

    insert into public.point_ledger(
      user_id,
      amount_delta,
      reason,
      idempotency_key,
      related_entity_type,
      related_entity_id,
      metadata
    ) values (
      v_user_id,
      0,
      'AI_ALBUM_DRAFT_FREE',
      'ai_album_draft_free:' || v_user_id::text || ':' || p_draft_id,
      'ai_album_draft',
      p_draft_id,
      jsonb_build_object('point_cost', 0)
    );

    select balance
    into v_wallet_balance
    from public.point_wallets
    where user_id = v_user_id;

    return query select true, 0, v_wallet_balance;
    return;
  end if;

  select balance
  into v_wallet_balance
  from public.point_wallets
  where user_id = v_user_id
  for update;

  if v_wallet_balance < p_point_cost then
    raise exception 'insufficient points for AI album draft'
      using errcode = 'P0001';
  end if;

  update public.point_wallets
  set balance = balance - p_point_cost
  where user_id = v_user_id
  returning balance into v_wallet_balance;

  insert into public.ai_album_draft_usages(
    user_id,
    draft_id,
    point_cost,
    used_free_credit
  ) values (
    v_user_id,
    p_draft_id,
    p_point_cost,
    false
  );

  insert into public.point_ledger(
    user_id,
    amount_delta,
    reason,
    idempotency_key,
    related_entity_type,
    related_entity_id,
    metadata
  ) values (
    v_user_id,
    -p_point_cost,
    'AI_ALBUM_DRAFT_CHARGE',
    'ai_album_draft_charge:' || v_user_id::text || ':' || p_draft_id,
    'ai_album_draft',
    p_draft_id,
    jsonb_build_object('point_cost', p_point_cost)
  );

  return query select false, p_point_cost, v_wallet_balance;
end;
$$;

revoke all on function public.record_ai_album_draft_success(text, integer) from public;
grant execute on function public.record_ai_album_draft_success(text, integer) to authenticated;
