-- Operational event log for AI album and mobile billing rollout.
-- Stores low-cardinality status metadata only; never insert provider secrets,
-- receipts, purchase tokens, or raw model prompts/responses here.

create table if not exists public.ai_album_operational_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_type text not null check (event_type in (
    'AI_DRAFT_PROVIDER_RESULT',
    'AI_DRAFT_PROVIDER_ERROR',
    'POINT_PURCHASE_VERIFIED',
    'POINT_PURCHASE_DUPLICATE',
    'POINT_PURCHASE_FAILED',
    'SUBSCRIPTION_VERIFIED',
    'SUBSCRIPTION_FAILED'
  )),
  request_id text,
  provider text,
  platform text,
  product_id text,
  transaction_id text,
  point_delta integer,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists ai_album_operational_events_created_idx
on public.ai_album_operational_events(created_at desc);

create index if not exists ai_album_operational_events_type_created_idx
on public.ai_album_operational_events(event_type, created_at desc);

create index if not exists ai_album_operational_events_user_created_idx
on public.ai_album_operational_events(user_id, created_at desc)
where user_id is not null;

alter table public.ai_album_operational_events enable row level security;

drop policy if exists "ai_album_operational_events_admin_read" on public.ai_album_operational_events;
create policy "ai_album_operational_events_admin_read"
on public.ai_album_operational_events for select
to authenticated
using (public.is_admin());

drop policy if exists "ai_album_operational_events_admin_write" on public.ai_album_operational_events;
create policy "ai_album_operational_events_admin_write"
on public.ai_album_operational_events for all
to authenticated
using (public.is_admin())
with check (public.is_admin());
